### ISSUE TITLE
Possible type inference bug

### ISSUE THREAD

**Issue by psteckler** [ocaml/ocaml#9195] opened 2019-12-17 22:38 UTC
Here's some code that yields a type error in OCaml 4.07.1 and 4.08.1:

```ocaml
module type S0 = sig
  type t = string
  val x : int
end

module type S1 = sig
  type t
  val z : string

  module Stable : sig
    module V1 : sig end
    module Latest = V1
  end
                  
end

module type T = sig
  include S1
end

module Make_sig (M1 : S0) =
  struct
    module type M3 = sig
      include S1 with type t = M1.t
    end
  end
              
module Make (M1 : S0) (M2 : S1 with type t = M1.t) =
  struct
    module X () : Make_sig (M1).M3 = struct
    include M2
  end
end
```
In 4.08.1, `ocamlc` reports:
```
Error: Signature mismatch:
       Modules do not match:
         sig
           type t = M1.t
           val z : string
           module Stable :
             sig module V1 : sig  end module Latest : sig  end end
         end
       is not included in
         Make_sig(M1).M3
       In module Stable:
       Modules do not match:
         sig module V1 = Stable.V1 module Latest = Stable.Latest end
       is not included in
         sig module V1 : sig  end module Latest = V1 end
       In module Stable.Latest:
       Modules do not match:
         (module Stable.Latest)
       is not included in
         (module V1)
```
Changing `module Latest = V1` to `module Latest : module type of V1` allows compilation to succeed.

Not certain if this is a bug, but it's puzzling that a weaker specification of `Latest` makes things work.

Is there a better solution?

**Comment by Octachron** [comment] 2019-12-18 11:32
This is a duplicate of #8762 : inner module aliases are expanded in the type of functor argument (see #2051 for the reason why). Thus the type of `M2` in the functor is not `S with type t = M1.t` leading to your error.

**Closed as completed by Octachron** 2019-12-18 11:32 UTC
