### ISSUE TITLE
Types involved in coercion on let binding are dropped/mishandled

### ISSUE THREAD

**Issue by ncik-roberts** [ocaml/ocaml#12208] opened 2023-04-25 21:59 UTC
When writing a coercion on a non-function binding, like `let blah :> ty2 = ...` or `let blah : ty1 :> ty2 = ...`, two bad things happen:
* **Problem 1:** `ty1` is dropped altogether, so it's not typechecked at all.
* **Problem 2:** `ty2` is promoted to a `Pexp_constraint` instead of a `Pexp_coerce`, so no subtyping can happen.

**Problem 1:**
```
(* example1.ml *)
let blah : garbage undeclared types :> int = 3
```
The buggy behavior, exhibited in `trunk`, is:
```
$ ocamlc example1.ml -i
val blah : int
```
The correct behavior is:
```
$ ocamlc example1.ml -i
1 | let blah : garbage undeclared types :> int = 3
                                  ^^^^^
Error: Unbound type constructor types
```

**Problem 2:**
```
(* example2.ml *)
let x : [ `A ] = `A

let blah : unit -> [ `A ] :> unit -> [ `A | `B ] = fun () -> x
```

The buggy behavior, exhibited in `trunk`, is:
```
$ ocamlc example2.ml -i
3 | let blah : unit -> [ `A ] :> unit -> [ `A | `B ] = fun () -> x
                                                                 ^
Error: This expression has type [ `A ] but an expression was expected of type
         [ `A | `B ]
       The first variant type does not allow tag(s) `B
```
The correct behavior is:
```
$ ocamlc example2.ml -i
val x : [ `A ]
val blah : unit -> [ `A | `B ]
```

## Where it was introduced
This looks to have been introduced in https://github.com/ocaml/ocaml/pull/12119. I confirmed by running the tests before and after this change.

The problematic piece of code is https://github.com/ocaml/ocaml/pull/12119/files#diff-93662ded61d621a32c251e5ee798cff83d8bf25020fc47a5eae28b7c79de4284R2533-R2534. The old code called `mkexp_constraint` which inserts `Pexp_coerce`/`Pexp_constraint` appropriately.

**Comment by Octachron** [comment] 2023-04-25 22:00
Duplicate of #12188 .

**Closed as completed by Octachron** 2023-04-25 22:00 UTC
