### ISSUE TITLE
#12236 breaks backward-compatibility of type-directed disambiguation in optional arg defaults

### ISSUE THREAD

**Issue by ncik-roberts** [ocaml/ocaml#12668] opened 2023-10-16 11:09 UTC
This type-checks prior to #12236 but not after:

```
module M = struct
  type t = A | B
end

let f ?x:(_ : M.t = A) = ()
 
(* Error: Unbound constructor A *)
```
That's because, prior to #12236, optional argument defaults `?x:(PAT = EXPR)` were typechecked as though the user had written `let (PAT) = match x with None -> EXPR | Some x -> x in ...`. After #12236, this is typechecked more similarly to `match (match x with None -> EXPR | Some x -> x) with PAT -> ...`, i.e. `EXPR` is now type-checked before `PAT`.

### Some ideas for fixes

A quick, easy way to make this better would be to add a hack in the parser, similar to what we do with `let`, to duplicate the type annotation on the RHS, i.e. `?x:(_ : M.t = A)` would be elaborated to `?x:(_ : M.t = (A : M.t))`.
  * Benefits: easy
  * Downsides: hacky. Also it does not completely restore backward-compatibility because it's too sensitive to source syntax, e.g. `?x:((_ : M.t) = A)` would not type-check with this approach even though it did before #12236 because the parser-based rewrite would not apply.
 
A more invasive way to fix this would be to refactor `type_function` to type optional argument defaults more like `let` than like `match` (i.e. use `type_let` as a subroutine in some way).

**Comment by Octachron** [comment] 2023-10-16 11:34
Note that we are no longer duplicating type annotations on let bindings in the parser since 5.1. The `typ` constraint in  `let pat : typ = expr` is now directly record in the binding parsetree node without encoding. Currently, the typechecker duplicates the annotation later on, but that was intended as a temporary hack.

It sounds to me that it could make to use this option for optional arguments binding too.

**Comment by ncik-roberts** [comment] 2023-10-17 13:35
I did something like that in #12673, is that roughly what you were describing?

**Comment by Octachron** [comment] 2023-10-17 13:53
Indeed, that was what I have in mind in term of temporarily duplicating the annotation when typechecking.

**Comment by Octachron** [comment] 2023-10-27 07:41
I am closing the issue now that #12673 has been merged.

**Closed as completed by Octachron** 2023-10-27 07:41 UTC
