### ISSUE TITLE
The manual discusses the hash-sign syntax for polymorphic subvariants but merlin reports it as deprecated

### ISSUE THREAD

**Issue by nilsbecker** [ocaml/ocaml#11968] opened 2023-01-27 07:58 UTC
[The manual](https://v2.ocaml.org/releases/5.0/htmlman/polyvariant.html#s:polyvariant-advanced) describes polymorphic variant notation ``type t1 = [`T1] type t2 = [ #t1 | `T2]`` . when i use that notation in a program, merlin complains with a deprecation error. when i simply leave out the `#` the error disappears and the module appears to compile fine. in utop, the `#` notation is rejected. tested on 4.14.1

is this a doc bug?

**Comment by gasche** [comment] 2023-01-27 08:41
There are two places where `#` has been accepted for polymorphic variants ``type t = [ `A | `B ]``:
- in patterns, where `#t` means ``(`A | `B)``
- in types, where `#t` means ``[< `A | `B ]``, and can also be written `[< t]`.

Using `#t` in types is indeed deprecated, and the documentation should be fixed. Thanks!
Using `#t` in patterns is still supported.

**Comment by Octachron** [comment] 2023-01-27 09:25
@gasche @nilsbecker as far as I can see, the manual doesn't contain any use of the deprecated `#polyvar_definition` ? Where did you spot such uses ?

**Comment by gasche** [comment] 2023-01-27 09:37
Ah yes, I tried to find it and didn't, but just assumed that the example from @nilsbecker was located in a part of the manual I could not find.

(This issue let me realize the distinction between use-in-patterns and use-in-types, and now I need to update the Changes entry for 5.1 to clarify this. So at least the issue is useful in that.)

**Comment by nilsbecker** [comment] 2023-01-27 12:34
ah, that's right, defining a type and pattern matching on it are different indeed, i did not think of that (and did not find a mention in the docs). 

the link to the manual i posted above points to a section at the bottom of which `#` is used in a pattern match, so that's correct. failing to see the distinction of the uses of the syntax i then made up an example, which indeed does not appear in the manual.

but i agree that explicitly talking about the (dis)allowed syntax for type definitions in the manual is a good idea.

also, the fact that syntax for defining and pattern matching on a type is different is easy to miss for a less than perfectly attentive reader of the manual. it might be worthwhile to think about preventing the wrong but easily made assumption that the syntax is the same for both, by being more explicit in the manual.

**Comment by gasche** [comment] 2023-01-27 12:41
After grepping through the sources (`find . -name "*.etex" | xargs grep "#[a-z]" --color=always | less -R`), I couldn't find a use of the `#t` syntax for polymorphic variants in types. <https://v2.ocaml.org/releases/5.0/htmlman/types.html#sss:typexpr-sharp-types> mentions the syntax as deprecated, and it will be gone from the 5.1 manual that removed the feature altogther. I believe that the issue in fact requires no change to the manual. I will close here, and add the clarification to the Changes entry (on the 5.1 removal for this syntax) that was suggested by the discussion. Thanks!

**Closed as completed by gasche** 2023-01-27 12:41 UTC
Labels: documentation

**Comment by nilsbecker** [comment] 2023-01-27 12:51
[The user guide chapter](https://v2.ocaml.org/releases/5.0/htmlman/polyvariant.htm) does not show how to use a pre-existing polymorphic variant type in a new type definition, i.e. ``type t1 = `T1 type t2 = [`T2 | t1 ]`` . if it did, a reader might be made aware of the distinction in syntax between type definition and matching. just as a suggestion.

**Comment by gasche** [comment] 2023-01-27 12:57
Where did you learn about the `#t` syntax in types and/or how did you end up using it? You seem to suggest that we have to make extra work to avoid letting the user discover it by chance, but I'm skeptical, and I suspect that saying nothing about it is enough.

You point out that the user guide could mention a use-case where we do build a larger polymorphic variant by extending an existing variant. I don't think this is related to the `#t` syntax in types, but I agree that it is a good idea.

**Comment by nilsbecker** [comment] 2023-01-27 14:03
> Where did you learn about the `#t` syntax in types and/or how did you end up using it?

Hmm. I believe I just picked up the syntax `#t` on casual reading of the user guide without using it initially. Then recently in an unrelated context I wanted to build a type from smaller types, remembered "`#` is for including more constructors" and tried using it to avoid code repetition. Which, of course, was rejected. In my associative memory no distinction between type definition and pattern matching exists apparently ;) I think this is because in the more common case of non-polymorphic variants type definition and pattern matching are very similar.
