### ISSUE TITLE
Line number of parenthesized assert is the opening parenthesis

### ISSUE THREAD

**Issue by copy** [ocaml/ocaml#10852] opened 2022-01-05 20:49 UTC
The following example:

```ocaml
let () = (
    assert false
  )
```

Prints: `Exception: Assert_failure ("./test.ml", 1, 9).`

That is, the assertion is reported to be on line 1, when the actual assertion statement is on line 2.

**Comment by gasche** [comment] 2022-01-06 09:23
I looked into this. The crux of the problem is that the AST keeps a single node for `assert false` and for `( assert false )` (it is not a "concrete syntax tree" (CST) that tries to faithfully represent the code as written). Its location is the wider location of the two, and it is used as the payload of the `Assert_failure` constructor.

Yet there is hope: the parsetree provide a "location stack" for each AST node, a list of locations from the wider to the most precise. I think that on this example, getting the last element of the "location stack" would give us the more precise location of the `assert false` fragment. But the transformation from `assert false` to `raise Assert_failure(<loc>)` is not done on the parsetree, but on the typedtree, and currently the parsetree->typedtree step does *not* propagate the location-stack information, only the "main" location (the widest one).

So a fix would involve two steps:
- easy but tedious: propagation "location stacks" from the parsetree to the typedtree
- easy and short: refine the `assert_false` rewrite step to take the most precise location

**Comment by gasche** [comment] 2022-01-06 09:26
I don't have time to work on this right now. I also think this task should be accessible to someone with little knowledge of the compiler codebase, who wants to gets involved. (It involves touching many parts of the compiler frontend, but in easy ways; think of this as an non-supervised tour.)

**Comment by copy** [comment] 2022-01-06 23:23
Note that this also applies to regular assertions, not just the specially handled `assert false`.

I'll take it. The concept of location stacks is new to me, but at least the passing through of the location from Pexp_assert to Texp_assert and ultimately the generation of the raise expression in translcore.ml looks straightforward. 

> easy but tedious: propagation "location stacks" from the parsetree to the typedtree
> easy and short: refine the assert_false rewrite step to take the most precise location

I believe I understand both approaches. Unless there is another reason to have location stacks in the typed tree, I would avoid increasing the size of the typed tree and go with the latter approach.

**Comment by gasche** [comment] 2022-01-07 07:30
I think you need to perform the two steps in sequence, it's not an alternative: if you don't have the "location stack", you cannot take the "most precise location", you only have one location at hand which is the least precise.

**Comment by gasche** [comment] 2022-01-07 07:36
Your remark that all `assert` are affected made me realize that another, simple route would be possible: it should be possible to add a `Location.t` argument to the `Pexp_assert` constructor (in the parsetree) and `Texp_assert` (in the typedtree). This argument would be filled by the parser when `assert` is parsed, so it gets the most precise location. It seems redundant with the location which is present on any AST node, but it is not "widened" by other parsing constructs.

This approach touches more files (the parser also needs a change), but only their handling of "assert" specifically (whereas the previous proposal would change slightly the structure of all typedtree nodes). It's probably easier -- but one would need to learn about how to regenerate the Menhir parser after a change to the `.mly`, see parsing/HACKING.adoc.

One downside of the new proposal is that it changes the parsetree, and therefore breaks the compatibility with external AST consumers (ppx, etc.; though these days ppxes may be protected by having their AST version fixed by ppxlib).

**Comment by copy** [comment] 2022-01-15 06:13
How about a hybrid approach? A location argument is only added to the `Texp_assert` in the typedtree, and it's taken from the location stack when creating the `Texp_assert` from a `Pexp_assert`. The advantage is that the parsetree doesn't need to be changed. Note that this is the first use of the location stack in the compiler base (presumable it's used by third-party tools?).

By the way, it looks like locations in backtraces are also affected:

```ocaml
let () = (
    raise (Failure "foo")
  )
```

```
% ocamlc -g test.ml && OCAMLRUNPARAM=b ./a.out
Fatal error: exception Failure("foo")
Raised at Test in file "test.ml", line 1, characters 9-40
```

**Comment by gasche** [comment] 2022-01-15 10:50
Yes, I think that could work, and it's less invasive indeed than changing the parsetree.
(Yes, location stacks were added for ocamlformat I believe.)

I suspect that location in backtraces may be a bit more difficult to fix, as they use locations from various AST nodes. (I think the locations in backtrace come from the location of debug event, so one would need to look at how those are computed, and hope that a simple approach similar to the one you suggest exists). I would recommend focusing on `assert` nodes first to make progress.

**Comment by gasche** [comment] 2022-03-07 10:17
I'm taking the liberty to close this in favor of #10911, which is a satisfying solution to this problem. #10911 is not merged yet due to the sequential freeze, but it is morally done.

**Closed as completed by gasche** 2022-03-07 10:17 UTC
Labels: enhancement, good first issue
