### ISSUE TITLE
-dsource dumps invalid program

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#10623] opened 2021-09-09 03:41 UTC
version 4.10.2

Input:
```
let rec pp_ident :
          'loc .
           'loc
              -> 'b

  =
  ((
      fun poly_loc ->
        x)
  [@ocaml.warning "-A"]
  )
and show_ident :
  'loc .
    'a
  =
  fun poly_loc ->
    x

```

Output:
```
let rec (pp_ident : 'loc . 'loc -> 'b) = ((fun poly_loc -> x)
  [@ocaml.warning "-A"])
and show_ident : 'loc . 'a = fun poly_loc -> x
```

The parens around `pp_ident` produces invalid program

**Comment by gasche** [comment] 2021-09-09 06:32
I cannot reproduce with 4.12:

```
$ ocamlc -stop-after parsing -dsource test.ml
let rec pp_ident : 'loc . 'loc -> 'b = ((fun poly_loc -> x)
  [@ocaml.warning "-A"])
and show_ident : 'loc . 'a = fun poly_loc -> x
```

**Comment by gasche** [comment] 2021-09-09 06:34
This was #9778, first merged in 4.12.

**Closed as completed by gasche** 2021-09-09 06:34 UTC
