### ISSUE TITLE
Random failure of tests/intext_par.ml

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocaml#12057] opened 2023-03-01 14:14 UTC
The test `tests/intext_par.ml` fails on my machine with probability p=1/30 (in bytecode) and in CI with similarly low probability.

Reducing the number of domains reduces the probability of failure.

With only one domain, the failure doesn't happen.

The problem happens when marshaling objects.

This failure has been spotted in https://github.com/ocaml/ocaml/pull/12001#issuecomment-1429136380 and https://github.com/ocaml/ocaml/pull/12006#issuecomment-1427072335.

I'm looking into it.

**Comment by gasche** [comment] 2023-03-01 14:32
Closing as a duplicate of #12056 :-)

**Closed as not planned by gasche** 2023-03-01 14:32 UTC
Labels: bug
