### ISSUE TITLE
Tail-mod-cons produces erroneous results when the TMC call is inside an exception handler.

### ISSUE THREAD

**Issue by SylvainBoilard** [ocaml/ocaml#12957] opened 2024-02-03 21:02 UTC
Hello,

I believe I ran into a bug while playing around with the tail-modulo-cons extension. This code compiles without warnings with OCaml 5.1.1 (`tailcall` annotations added for clarity, no warnings either if you remove them):
```ocaml
let[@tail_mod_cons] rec test_1 = function
  | [] -> []
  | hd :: tl ->
     try int_of_string hd :: (test_1[@tailcall false]) tl
     with Failure _ -> -1 :: (test_1[@tailcall true]) tl

let result = test_1 ["1"; "2"; "foo"; "3"; "4"]
```
But the resulting `result` value is structured as such:
```
Block with size 2:
  Value 1
  Block with size 2:
    Value 2
    Block with size 2:
      Value -1
      Value 24029

[1; 2; -1; <???>]
```
Notice how the list is shorter than it should be, and how the last node is a strange value in place of either a block or the value 0. Calling `List.iter` on this list even causes a segmentation fault when the code is compiled with `ocamlc`. Removing the `tail-mod-cons` annotation does make the code produce correct results.

**Comment by nojb** [comment] 2024-02-03 21:37
Thanks for the report. Indeed there seems to be a miscompilation in this case. The `lambda` code of the "dps" (destination-passing style) transform of the function in your example is
```
      test_1_dps/280
        (function dst/287 offset/286[int] param/285 tail_mod_cons
          (if param/285
            (let (tl/288 =a (field 1 param/285))
              (try
                (makeblock 0 (int,*) (caml_int_of_string (field 0 param/285))
                  (apply test_1/269 tl/288 tailcall(false)))
               with exn/289
                (if (== (field 0 exn/289) (field 6 (global Stdlib!)))
                  (let (block/290 = (makemutable 0 (int,*) -1 24029))
                    (seq
                      (setfield_ptr(heap-init)_computed dst/287 offset/286
                        block/290)
                      (apply test_1_dps/280 block/290 1 tl/288 tailcall)))
                  (setfield_ptr(heap-init)_computed dst/287 offset/286
                    (reraise exn/289)))))
            (setfield_ptr(heap-init)_computed dst/287 offset/286 0))))
```
The problem is that in the body of the `try-with`, the code does not "fill" the destination `dst/287`, so the block is left filled with garbage.

A tentative fix is in #12958

**Comment by gasche** [comment] 2024-02-03 21:43
This is indeed a bug! The following patch fixes it, but I need to understand it better and audit the rest of the transformation for similar issues.

```diff
diff --git i/lambda/tmc.ml w/lambda/tmc.ml
index 5edbcdf8b5..a9bc1d1baa 100644
--- i/lambda/tmc.ml
+++ w/lambda/tmc.ml
@@ -644,8 +644,8 @@ let rec choice ctx t =
            not in tail-call position (after it returns
            we need to remove the exception handler),
            so it is not transformed here *)
-        let l1 = traverse ctx l1 in
-        let+ l2 = choice ctx ~tail l2 in
+        let+ l1 = Choice.lambda (traverse ctx l1)
+        and+ l2 = choice ctx ~tail l2 in
         Ltrywith (l1, id, l2)
     | Lstaticcatch (l1, ids, l2) ->
         (* In [static-catch l1 with ids -> l2],
```

**Closed as completed** 2024-02-04 01:19 UTC
Labels: bug

**Comment by gasche** [comment] 2024-02-04 01:24
@SylvainBoilard this should now be fixed (in development versions). Thanks again for the report!

**Comment by SylvainBoilard** [comment] 2024-02-04 01:29
Thank you for the quick fix, looking forward for the next release!
