### ISSUE TITLE
Join the efforts with Bootstrappable project

### ISSUE THREAD

**Issue by XVilka** [ocaml/ocaml#9002] opened 2019-10-01 10:13 UTC
There exist a [Bootstrappable](https://bootstrappable.org/) project that helps to coordinate efforts to keep the main Linux infrastructure bootstrappable. It comes along with [Reproducible Builds](https://reproducible-builds.org/) project for improving the deterministic and reproducible software building approach. Project comes with a [best practices](https://bootstrappable.org/best-practises.html) examples and some projects, like Haskell and JVM, [already part of it](https://bootstrappable.org/projects.html). Reproducible builds project offers some [helper tools](https://reproducible-builds.org/tools/) for developers to compare the builds, many projects [already participate in this initiative](https://reproducible-builds.org/who/) as well.

See [a great article](https://bootstrappable.org/projects/mes.html) on how to reduce the size of "binary seeds" to port the implementation on a computer of compatible architecture, but without existing tooling.

Also see [the blog post](https://elephly.net/posts/2017-01-09-bootstrapping-haskell-part-1.html) describing the Haskell experience to setup a bootstrappable infrastructure.

**Comment by gasche** [comment] 2019-10-01 10:22
The most serious attempt at getting rid of binary seeds (bytecode seeds) in OCaml's bootstrap is @Ekdohibs' [camlboot](https://github.com/Ekdohibs/camlboot) project -- I've hacked on it some, but it's not ready quite yet.

**Comment by gasche** [comment] 2019-10-01 10:24
See #7853 -- I think the present issue is partly a duplicate of that one.

**Comment by XVilka** [comment] 2020-12-16 07:26
Indeed, [camlboot](https://github.com/Ekdohibs/camlboot) receives recently a flurry of activity and looks very promising.

**Comment by XVilka** [comment] 2021-07-12 07:37
I am not sure the status of the `camlboot` right now, since it wasn't updated for quite a while:
- https://github.com/Ekdohibs/camlboot/pulls

But this issue probably might be closed.

**Comment by gasche** [comment] 2021-07-12 09:36
Let's close here, as it is now mostly a duplicate of #7853 indeed.

The current status of camlboot is as I described it in [this comment](https://github.com/ocaml/ocaml/issues/7853#issuecomment-859257065): OCaml 4.07 has been debootstrapped, but there is some tedious work remaining to upgrade to 4.12. (It's a non-trivial change.) Now one has actively worked on the implementation in the last couple months, but I hope to have another look at time sometimes next Autumn.

**Comment by gasche** [comment] 2021-07-12 09:37
Let's close here, as it is now mostly a duplicate of #7853 indeed.

The current status of camlboot is as I described it in [this comment](https://github.com/ocaml/ocaml/issues/7853#issuecomment-859257065): OCaml 4.07 has been debootstrapped, but there is some tedious work remaining to upgrade to 4.12. (It's a non-trivial change.) Now one has actively worked on the implementation in the last couple months, but I hope to have another look at time sometimes next Autumn.

**Closed as completed by gasche** 2021-07-12 09:37 UTC
