### ISSUE TITLE
[Android / Ocaml 5] undefined symbol: pthread_getaffinity_np

### ISSUE THREAD

**Issue by anzhi0708** [ocaml/ocaml#12101] opened 2023-03-12 06:42 UTC
### OPAM Packages Installed
<details>

```
/data/data/com.termux/files/usr/include % opam list                                         # Packages matching: installed
# Name        # Installed # Synopsis
base-bigarray base
base-threads  base
base-unix     base
cmdliner      1.0.4       Declarative definiti
ocaml         4.07.1      The OCaml compiler (
ocaml-config  1           OCaml Switch Configu
ocaml-system  4.07.1      The OCaml compiler (
ocamlfind     1.9.1       A library manager fo
seq           base        Compatibility packag
/data/data/com.termux/files/usr/include %
```

</details>

### Details
<details><summary> `neofetch --off` </summary>

```
u0_a248@localhost
-----------------                             OS: Android 11 aarch64
Host: Redmi 21091116AC
Kernel: 4.14.186-perf-gd65dbc980d48
Uptime: 1 day, 14 hours, 51 mins
Packages: 300 (dpkg), 1 (pkg)
Shell: zsh 5.9
CPU: MT6833P (8) @ 2.000GHz                   Memory: 2753MiB / 5635MiB
```
</details>

### uname -a
<details>

```

Linux localhost 4.14.186-perf-gd65dbc980d48 #1 SMP PREEMPT Fri Oct 28 22:22:47 CST 2022 aarch64 Android

```

</details>

### OPAM Version

2.0.3

***

## Error Message

<details><summary> `opam switch install 5.0.0` Error Message </summary>

```

(Skipping...)

# 2 warnings generated.
# gcc -O2 -fno-strict-aliasing -fwrapv -pthread -g -Wall -fno-common -ffunction-sections  -Wl,-E -landroid-shmem -o runtime/ocamlrun runtime/prims.o runtime/libcamlrun.a -lm -lexecinfo  -lpthread
# ld.lld: error: undefined symbol: pthread_getaffinity_np
# >>> referenced by domain.c:1795 (runtime/domain.c:1795)
# >>>               domain.b.o:(caml_recommended_domain_count) in archive runtime/libcamlrun.a
# clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
# make[2]: *** [Makefile:822: runtime/ocamlrun] Error 1
# make[2]: Leaving directory '/data/data/com.termux/files/home/.opam/5.0.0/.opam-switch/build/ocaml-base-compiler.5.0.0'

(Skipping...)

```

</details>

### $(grep -r pthread_get)
<details>

```bash

/data/data/com.termux/files/usr/include % grep -r pthread_get
npth.h:#define npth_getspecific pthread_getspecific
npth.h:   pthread_getspecific are standardized as async-signal-safe (what a
npth.h:   pthread_self and pthread_getspecific is probably portable
pthread.h:int pthread_getattr_np(pthread_t __pthread, pthread_attr_t* __attr);              pthread.h:int pthread_getcpuclockid(pthread_t __pthread, clockid_t* __clock);
pthread.h:int pthread_getschedparam(pthread_t __pthread, int* __policy, struct sched_param* __param);                                     pthread.h:void* pthread_getspecific(pthread_key_t __key);
pthread.h:pid_t pthread_gettid_np(pthread_t __pthread) __INTRODUCED_IN(21);                 pthread.h:int pthread_getname_np(pthread_t __pthread, char* __buf, size_t __n) __INTRODUCED_IN(26);
c++/v1/__threading_support:  return pthread_getspecific(__key);
bits/threads_inlines.h:  return pthread_getspecific(__key);                                 python3.11/pyconfig.h:/* Define to 1 if you have the `pthread_getcpuclockid' function. */
python3.11/cpython/pthread_stubs.h:PyAPI_FUNC(void *) pthread_getspecific(pthread_key_t key);
```
</details>

***
## \`opam config\` report

```

# opam config report
# opam-version      2.0.3
# self-upgrade      no
# system            arch=arm64 os=linux os-distribution=android os-version=11
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              1
# repositories      1 (http) (default repo at 25bba47d)
# pinned            0
# current-switch    default

```

***

## Note

- Native Termux, not proot-distro linux
- Ocaml & OPAM pre-compiled binary installed via the famous Termux 3rd party repo 'its-pointless'
- LDFLAGS="-landroid-shmem"
- With above configurations `opam switch install 4.14.1` was successful, now `opam switch list` looks like this:
```

#  switch   compiler
          description                         →  4.14.1   ocaml-base-compiler.4.14.1
          4.14.1                                 default  ocaml-system.4.07.1
          default
```

**Comment by gasche** [comment] 2023-03-12 08:54
Indeed, the Android implementation of `pthreads` does not provide `pthread_getaffinity_np`, see [this StackOverflow answer](https://stackoverflow.com/a/58348085/298143) for how to do something similar with Android -- we would need this to implement `caml_recommended_domain_count` under the Android libc.

On the other hand, I don't understand why the build fails here, because we have a configure check for the availability of `pthread_getaffinity_np`:

https://github.com/ocaml/ocaml/blob/d408cac30d4cbad5a125520c96a7a351d7950577/configure.ac#L1921-L1942

The behavior that I would expect is that these configure checks fail for Android, so where HAS_{GNU,BSD}_GETAFFINITY_NP are not defined, and the runtime code does not try to use this function at all.

The [documentation for AC_COMPILE_IFELSE](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Running-the-Compiler.html) says:

> This macro does not try to link; use AC_LINK_IFELSE if you need to do that (see [Running the Linker](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Running-the-Linker.html#Running-the-Linker)).

I believe that the problem here is that the absence of `pthread_getaffinity_np` creates a link-time error instead of a compile-time error, at least on Android system, so our configure check believes that the feature is supported.

I think that the proper fix would be to:

1. Make the configure check robust against linking error.
2. In addition, implement Android-specific logic in the configure script and in the implementation itself, to get proper behavior instead of the default "1 domain recommended" behavior on Android (which we would get if we just ensured that the current configure check fails).

**Comment by gasche** [comment] 2023-03-12 08:55
cc @dra27 @shindere @Engil, some of whom may want to tackle this issue.

**Comment by dra27** [comment] 2023-03-12 10:02
I'm somewhat puzzled, since two hours ago I posted two comments on this issue. I'm hoping I didn't post them on another issue by mistake...

My immediate suggestion was this patch:
```diff
diff --git a/configure.ac b/configure.ac
index c614da5a38..b614d48e00 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1911,7 +1911,8 @@ AC_CHECK_FUNC([ffs], [AC_DEFINE([HAS_FFS])])
 AC_CHECK_FUNC([_BitScanForward], [AC_DEFINE([HAS_BITSCANFORWARD])])

 ## pthread_getaffinity_np, args differ from GNU and BSD
-AC_COMPILE_IFELSE(
+AC_MSG_CHECKING([arguments for pthread_getaffinity_np])
+AC_LINK_IFELSE(
   [AC_LANG_PROGRAM(
     [[#define _GNU_SOURCE
       #include <sched.h>
@@ -1920,8 +1921,9 @@ AC_COMPILE_IFELSE(
       CPU_ZERO(&cs);
       CPU_COUNT(&cs);
       pthread_getaffinity_np(pthread_self(), sizeof(cs), &cs);]])],
-  [AC_DEFINE([HAS_GNU_GETAFFINITY_NP])],
-  [AC_COMPILE_IFELSE(
+  [AC_MSG_RESULT([gnu])
+  AC_DEFINE([HAS_GNU_GETAFFINITY_NP])],
+  [AC_LINK_IFELSE(
     [AC_LANG_PROGRAM(
       [[#include <pthread.h>
         #include <pthread_np.h>
@@ -1931,7 +1933,9 @@ AC_COMPILE_IFELSE(
         CPU_ZERO(&cs);
         CPU_COUNT(&cs);
         pthread_getaffinity_np(pthread_self(), sizeof(cs), &cs);]])],
-    [AC_DEFINE([HAS_BSD_GETAFFINITY_NP])])])
+    [AC_MSG_RESULT([BSD])
+    AC_DEFINE([HAS_BSD_GETAFFINITY_NP])],
+    [AC_MSG_RESULT([pthread_getaffinity_np not found])])])

 ## ZSTD compression library
```

**Comment by shindere** [comment] 2023-03-12 10:06
Well, either we are able, in configure, to make the check more robust,
or we will need to hard-code in configure the fact that on Android this
feature is not supported.

**Comment by gasche** [comment] 2023-03-12 10:07
We can make the check more robust (see the patch by David above), but we may also want to implement proper support (in the configure and in the runtime) for Android's way of counting the number of available CPUs.

**Comment by gasche** [comment] 2023-03-12 10:14
Regarding "the Android way": according to [the StackOverflow answer](https://stackoverflow.com/a/58348085/2981430), android supports `sched_getaffinity` from `sched.h`.

```c
int sched_getaffinity(pid_t pid, size_t cpusetsize, cpu_set_t *mask);
```

A [linux manpage](https://linux.die.net/man/2/sched_getaffinity) says:

> If pid is zero, then the mask of the calling process is returned.

So if I understand correctly, we could just call `sched_getaffinity` (with `pid=0`) and then `CPU_COUNT` from sched.h, and have a good approximation on any system that supports `sched_getaffinity` but not `pthread_getaffinity_np`. (In particular, one may not need to use `pthread_gettid_np` as suggested by the StackOverflow answer.)

**Comment by dra27** [comment] 2023-03-14 08:11
> I'm somewhat puzzled, since two hours ago I posted two comments on this issue. I'm hoping I didn't post them on another issue by mistake...

It turns out I'm going slightly mad - I posted the patch on https://github.com/ocaml/opam/issues/5477#issuecomment-1465129163.

**Comment by anzhi0708** [comment] 2023-03-14 10:15
> > I'm somewhat puzzled, since two hours ago I posted two comments on this issue. I'm hoping I didn't post them on another issue by mistake...
> 
> It turns out I'm going slightly mad - I posted the patch on [ocaml/opam#5477 (comment)](https://github.com/ocaml/opam/issues/5477#issuecomment-1465129163).

Sorry for confusing you mate! My bad. I should not have created multiple issues. I'm really sorry.

**Comment by shindere** [comment] 2023-03-14 14:39
Anji (2023/03/14 03:15 -0700):
> > > I'm somewhat puzzled, since two hours ago I posted two comments on this issue. I'm hoping I didn't post them on another issue by mistake...
> >
> > It turns out I'm going slightly mad - I posted the patch on [ocaml/opam#5477 (comment)](https://github.com/ocaml/opam/issues/5477#issuecomment-1465129163).
>
> Sorry for confusing you mate! My bad. I should not have created
> multiple issues. I'm really sorry.

Did you give David's patch a try? Does it work for you?

**Comment by anzhi0708** [comment] 2023-03-15 07:04
> Anji (2023/03/14 03:15 -0700):
> > > I'm somewhat puzzled, since two hours ago I posted two comments on this issue. I'm hoping I didn't post them on another issue by mistake... > > It turns out I'm going slightly mad - I posted the patch on [[ocaml/opam#5477](https://github.com/ocaml/opam/issues/5477) (comment)]([ocaml/opam#5477 (comment)](https://github.com/ocaml/opam/issues/5477#issuecomment-1465129163)). Sorry for confusing you mate! My bad. I should not have created multiple issues. I'm really sorry.
> Did you give David's patch a try? Does it work for you?

Umm, first of all, I'm a noob. And no, it did not work for me. This is how I applied the patch: I git clone OCaml repo, find `configure.ac`, manually modified it, and then `./configure --prefix=$PREFIX`, here are some error messages complaining about `pthread` functions.

---

<details>
 <summary> 
The Error Message from `make` </summary>

```
(Skipping...)

CCDEPS .dep/runtime/frame_descriptors.npic.d
  CCDEPS .dep/runtime/startup_nat.npic.d
  CCDEPS .dep/runtime/signals_nat.npic.d
make coldstart
make[1]: Entering directory '/data/data/com.termux/files/home/ocaml/ocaml'
make runtime-all
make[2]: Entering directory '/data/data/com.termux/files/home/ocaml/ocaml'
  GEN runtime/ld.conf
  CC runtime/addrmap.b.o
  CC runtime/afl.b.o
  CC runtime/alloc.b.o
  CC runtime/array.b.o
  CC runtime/backtrace.b.o
  CC runtime/bigarray.b.o
  CC runtime/callback.b.o
  CC runtime/codefrag.b.o
  CC runtime/compare.b.o
  CC runtime/custom.b.o
  CC runtime/debugger.b.o
  CC runtime/domain.b.o
runtime/domain.c:1870:7: error: call to undeclared function 'pthread_getaffinity_np'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
  if (pthread_getaffinity_np(pthread_self(), sizeof(cpuset), &cpuset) == 0)
      ^
runtime/domain.c:1870:7: note: did you mean 'pthread_getattr_np'?
/data/data/com.termux/files/usr/include/pthread.h:188:5: note: 'pthread_getattr_np' declared here
int pthread_getattr_np(pthread_t __pthread, pthread_attr_t* __attr);
    ^
1 error generated.
make[2]: *** [Makefile:969: runtime/domain.b.o] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml'
make[1]: *** [Makefile:209: coldstart] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml'
make: *** [Makefile:375: world.opt] Error 2

```

</details>

---

Excuse me for being a noob, I barely have any CS knowledge and have only used Python to make some GUI applications.

Btw, I successfully installed OCaml 5 inside Termux's proot-distro alpine linux instead of native Termux before I rooted my device.

**Comment by gasche** [comment] 2023-03-15 08:22
When you modify `configure.ac`, there needs to be a build step to derive the new `configure` script from it. `make configure` should do the job, assuming `autoconf` is installed on your machine.

**Comment by anzhi0708** [comment] 2023-03-15 10:17
> When you modify `configure.ac`, there needs to be a build step to derive the new `configure` script from it. `make configure` should do the job, assuming `autoconf` is installed on your machine.

Progress! `runtime/domain*` was compiled, but new error message (GC related?) appeared

```
(Skipping...)

  CC runtime/debugger.b.o
  CC runtime/domain.b.o
  CC runtime/dynlink.b.o
  CC runtime/extern.b.o
  CC runtime/fiber.b.o
  CC runtime/finalise.b.o
  CC runtime/floats.b.o
  CC runtime/gc_ctrl.b.o
  CC runtime/gc_stats.b.o
  CC runtime/globroots.b.o
  CC runtime/hash.b.o
  CC runtime/intern.b.o
  CC runtime/ints.b.o
  CC runtime/io.b.o
  CC runtime/lexing.b.o
  CC runtime/lf_skiplist.b.o
  CC runtime/main.b.o
  CC runtime/major_gc.b.o
runtime/major_gc.c:943:9: error: 'PAGE_MASK' macro redefined [-Werror,-Wmacro-redefined]
#define PAGE_MASK (~(uintnat)(BITS_PER_WORD-1))
        ^
/data/data/com.termux/files/usr/include/sys/user.h:39:9: note: previous definition is here
#define PAGE_MASK (~(PAGE_SIZE - 1))
        ^
1 error generated.
make[2]: *** [Makefile:969: runtime/major_gc.b.o] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml'
make[1]: *** [Makefile:209: coldstart] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml'
make: *** [Makefile:375: world.opt] Error 2
~/ocaml/ocaml $
```

Looks like the macro name `PAGE_MASK` conflicted with some header file from `sys/`, not sure what this `user.h` does

**Comment by gasche** [comment] 2023-03-15 10:29
You want to pass `--disable-warn-error` to `./configure` to disable this kind of inessential errors.

(We should investigate why one of the Android headers that we include also defines `PAGE_MASK`, or prefix the macro, or disable the warning.)

**Comment by anzhi0708** [comment] 2023-03-15 10:58
> You want to pass `--disable-warn-error` to `./configure` to disable this kind of inessential errors.
> 
> (We should investigate why one of the Android headers that we include also defines `PAGE_MASK`, or prefix the macro, or disable the warning.)

Thanks a lot, I retried with `LDFLAGS="-landroid-shmem" make` and now I'm figuring out what to do with this `libandroid-shmat` error:

```
  OCAMLC options.cmi
  OCAMLC options.cmo
  OCAMLC main.cmi
  OCAMLC main.cmo
  LINKC ocamltest
ld.lld: error: undefined symbol: libandroid_shmat
>>> referenced by afl.c:101 (runtime/afl.c:101)
>>>               afl.b.o:(caml_setup_afl) in archive ../stdlib/libcamlrun.a
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
File "_none_", line 1:
Error: Error while building custom runtime system
make[3]: *** [Makefile:138: ocamltest] Error 2
make[3]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml/ocamltest'
make[2]: *** [Makefile:1223: ocamltest] Error 2
make[2]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml'
make[1]: *** [Makefile:303: opt.opt] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/ocaml/ocaml'
make: *** [Makefile:376: world.opt] Error 2

```

**I ran into this `libandroid-shmat` problem before, and usually when I add `LDFLAGS="-landroid-shmem"`, the problem goes away**; this time I'm not sure what to do with it,

```
~/ocaml/ocaml $ apt search libandroid
Sorting... Done
Full Text Search... Done
libandroid-complex-math/stable,now 0.1 aarch64 [installed]
  A shared library providing libm complex math functions

libandroid-complex-math-static/stable,now 0.1 aarch64 [installed]
  Static libraries for libandroid-complex-math

libandroid-execinfo/stable,now 0.1-1 aarch64 [installed]
  Shared library for the backtrace system function

libandroid-execinfo-static/stable,now 0.1-1 aarch64 [installed]
  Static libraries for libandroid-execinfo

libandroid-glob/stable,now 0.6-2 aarch64 [installed]
  Shared library for the glob(3) system function

libandroid-glob-static/stable,now 0.6-2 aarch64 [installed]
  Static libraries for libandroid-glob

libandroid-posix-semaphore/stable,now 0.1-3 aarch64 [installed]
  Shared library for the posix semaphore system function

libandroid-posix-semaphore-static/stable,now 0.1-3 aarch64 [installed]
  Static libraries for libandroid-posix-semaphore

libandroid-shmem/stable,now 0.4 aarch64 [installed]
  System V shared memory emulation on Android using ashmem

libandroid-shmem-static/stable,now 0.4 aarch64 [installed]
  Static libraries for libandroid-shmem

libandroid-spawn/stable,now 0.3 aarch64 [installed]
  Shared library for the posix_spawn system function

libandroid-spawn-static/stable,now 0.3 aarch64 [installed]
  Static libraries for libandroid-spawn

libandroid-support/stable,now 28-3 aarch64 [installed]
  Library extending the Android C library (Bionic) for additional multibyte, locale and math support

libandroid-support-static/stable,now 28-3 aarch64 [installed]
  Static libraries for libandroid-support

libandroid-sysv-semaphore/stable,now 0.1 aarch64 [installed]
  A shared library providing System V semaphores

libandroid-sysv-semaphore-static/stable,now 0.1 aarch64 [installed]
  Static libraries for libandroid-sysv-semaphore

libandroid-wordexp/stable,now 0.1 aarch64 [installed]
  Shared library for the wordexp(3) system function

libandroid-wordexp-static/stable,now 0.1 aarch64 [installed]
  Static libraries for libandroid-wordexp

```

I'll try to start from the very beginning with `make clean`

**Comment by shindere** [comment] 2023-03-15 11:32
Anji (2023/03/15 03:58 -0700):
> > You want to pass `--disable-warn-error` to `./configure` to disable this kind of inessential errors.
> > 
> > (We should investigate why one of the Android headers that we include also defines `PAGE_MASK`, or prefix the macro, or disable the warning.)
> 
> Thanks a lot, I retried with `LDFLAGS="-landroid-shmem" make` and now I'm figuring out what to do with this `libandroid-shmat` error:

It wold be better to add this at configuretime, so yoru current
configure line plus:

  ./configure LDFLAGS="-landroid-shmem"

And you could also try to add the `--without-afl` option to this same
configure invocation.

Btw, is there an (easy) way to reproduce, on a Linux box, say? Or does
this require a phone with termux installed. I'm wondering how easy it is
to set-up such a phone and to ssh into it to experiment, if one can not
experiment on a regular laptop / workstation.

**Comment by anzhi0708** [comment] 2023-03-15 13:02
Thanks you guys! It works now.

After running `./configure --prefix=$PREFIX --disable-warn-error --without-afl LDFLAGS="-landroid-shmem"` 

and `make`, `make install`, everything works now.

```bash
~/ocaml/ocaml $ $PREFIX/bin/ocaml --version
The OCaml toplevel, version 5.1.0+dev1-2022-06-09
```

And I wrote a simple `.ml` to test `Domain.spawn` and no error was printed

<details>
<summary> The code </summary>

```ocaml
let money = ref 0 in

let t1 = Domain.spawn (
  fun _ ->
    for i = 1 to 100 do
      money := !money + 1
    done
)
in

let t2 = Domain.spawn (
  fun _ ->
    for i = 1 to 100 do
      money := !money - 1
    done
) in

Domain.join t1; Domain.join t2;

print_int !money;
print_endline "";


let rec fib (n: int) =
  match n with
  | 0 | 1 -> n
  | x when x < 0 -> failwith "Negative number!"
  | x -> fib (n - 1) + fib (n - 2)
in

let t1 = Domain.spawn (fun _ -> fib 30) in
let t2 = Domain.spawn (fun _ -> fib 30) in
let r1 = Domain.join t1 in
let r2 = Domain.join t2 in
Printf.printf "result1: %d; result2: %d\n" r1 r2;
```
</details>

```bash
~/ocaml $ export TIMEFORMAT="%P%"; time $PREFIX/bin/ocaml ./hello_domains.ml
0
result1: 832040; result2: 832040
165.43%
```

**The CPU usage is `163%`, I guess that means multi-threading is working as expected**
(I was expecting variable `money` to not equal to `0`, obviously it was my code and my programming skills to blame)

**Comment by anzhi0708** [comment] 2023-03-15 13:07
> Anji (2023/03/15 03:58 -0700):
> > You want to pass `--disable-warn-error` to `./configure` to disable this kind of inessential errors. > > (We should investigate why one of the Android headers that we include also defines `PAGE_MASK`, or prefix the macro, or disable the warning.) Thanks a lot, I retried with `LDFLAGS="-landroid-shmem" make` and now I'm figuring out what to do with this `libandroid-shmat` error:
> It wold be better to add this at configuretime, so yoru current configure line plus: ./configure LDFLAGS="-landroid-shmem" And you could also try to add the `--without-afl` option to this same configure invocation. Btw, is there an (easy) way to reproduce, on a Linux box, say? Or does this require a phone with termux installed. I'm wondering how easy it is to set-up such a phone and to ssh into it to experiment, if one can not experiment on a regular laptop / workstation.

I used to install Termux on a Android virtual machine (within Virtual Box). I could not remember all the details, but I guess I found Termux's `.apk` file online and installed it on the Android virtual machine. As I can remember, it worked well.

I guess all you need is an Android iso file to install it with VirtualBox? Plus Termux APK probably. If you really want to do that, I'll find an Termux APK for you :3

**Comment by anzhi0708** [comment] 2023-03-15 13:23
Thanks you all for your kindness and replying. OCaml is such a beautiful language and appreciate you guys' work.

If you guys don't mind, I'll close this issue.

**Comment by shindere** [comment] 2023-03-15 17:36
Anji (2023/03/15 06:23 -0700):
> Thanks you all for your kindness and replying. OCaml is such a beautiful language and appreciate you guys' work.
> 
> If you guys don't mind, I'll close this issue.

Hmm, sorry if Imissed something but my  understanding is that the patch
that did fix the issue has not been merged yet, not mentionning the
problems whichwere revealed with the codee that triggers warnings.

So my impression is that this should issue should be re-opened until
things get clarified and trunk compiles cleanly without the need for any
patch and without the code triggering any warning.

**Comment by gasche** [comment] 2023-03-15 17:40
Yes, the detection failure issue is not actually fixed upstream.

Also, disabling pthread_getaffinity_np means that `Domain.recommended_domain_count ()` is always `1` on Android, which is suboptimal and could somewhat easily be fixed -- see my message above https://github.com/ocaml/ocaml/issues/12101#issuecomment-1465149419 for the details.

**Comment by anzhi0708** [comment] 2023-03-15 20:02
> Hmm, sorry if Imissed something but my understanding is that the patch that did fix the issue has not been merged yet, not mentionning the problems whichwere revealed with the codee that triggers warnings. 

Yeah, you're right :3


> Also, disabling pthread_getaffinity_np means that `Domain.recommended_domain_count ()` is always `1` on Android, which is suboptimal and could somewhat easily be fixed -- see my message above [#12101 (comment)](https://github.com/ocaml/ocaml/issues/12101#issuecomment-1465149419) for the details.

Umm, I tried this API on my device and the output was 8

```
~ $ opam switch list
#  switch  compiler
          description
   4.14.1  ocaml-base-compiler.4.14.1
          4.14.1
→  5.1.0
          My cool OCaml
~ $ ocaml
OCaml version 5.1.0+dev1-2022-06-09
Enter #help;; for help.

# Domain.recommended_domain_count()
  ;;
- : int = 8
#
```

(Also I used a silly method to add the manually compiled switch `5.1.0+dev` to `opam switch`)

But the problem is even with switch `4.14.1` one could not install `utop` with `opam` because something related to `pthread` was also missing in those packages, like, for `utop`, the **macro** called "PTHREAD_CANCLE" or something.

I'm not sure if those packages are maintained by someone else, if so, they probably don't know about header file problems on Android platform.

**Comment by gasche** [comment] 2023-03-15 20:28
Ah, it looks like the value comes from this code path before the `1` fallback:

```
#ifdef _SC_NPROCESSORS_ONLN
  if (n == -1)
    n = sysconf(_SC_NPROCESSORS_ONLN);
#endif /* _SC_NPROCESSORS_ONLN */
```

According to people on the internet, this approach is known to produce unreliable results on ARM systems including Android phones, but it works sometimes:

https://github.com/seanmonstar/num_cpus/issues/34
https://github.com/dotnet/coreclr/pull/18053

This is a separate issue, and I am now convinced that there may be no need to add a code path specifically for Android, so the configure patch is enough as a first step. Thanks for testing on your machine!

**Comment by anzhi0708** [comment] 2023-03-16 00:09
Thanks u all :3

**Closed as completed** 2023-04-18 04:38 UTC
