### ISSUE TITLE
[Typo] Console error message `ocaml_deprecated_auto_include`

### ISSUE THREAD

**Issue by anzhi0708** [ocaml/ocaml#12122] opened 2023-03-21 10:46 UTC
### OCaml Version

- 5.1.0+dev1-2022-06-09 on Android Termux
- 5.0.0 on macOS Big Sur

### Screenshot

[Screenshot](https://global.discourse-cdn.com/business7/uploads/ocaml/optimized/2X/5/5f7a4b12d940f9296a6748f5298ee96f73fbaebb_2_689x440.png)

(Take a closer look at the console output's content, some words were missing and this makes the output message confusing)

### How to Reproduce

- OCaml >= 5.0.0
- `rlwrap ocaml`
- `Unix.sleep 1;;`
- Note: Change the columns & rows of your terminal emulator and try again

**Comment by nojb** [comment] 2023-03-21 10:51
Sorry, I don't see what the typo is in the error message; could you please explain? Thanks!

**Comment by nojb** [comment] 2023-03-21 10:52
> (Take a closer look at the console output's content, some words were missing and this makes the output message confusing)

I think this is an issue with your terminal emulator. I cannot reproduce locally:

![image](https://user-images.githubusercontent.com/113560/226585173-075b2849-998b-4705-ab1f-141be0fdec44.png)

**Comment by nojb** [comment] 2023-03-21 10:56
There doesn't seem to be anything to fix here; closing. Feel free to open a new issue if you deem it necessary.

**Closed as completed by nojb** 2023-03-21 10:56 UTC

**Comment by anzhi0708** [comment] 2023-03-21 11:25
> Sorry, I don't see what the typo is in the error message; could you please explain? Thanks!

Umm, weird, cuz I opened another terminal and tried again, the problem was gone; yet I tried both on Android & macOS, the typo issue was there. As you can see, the problem I discovered before was this part of the message:

![截屏2023-03-21 20 18 43](https://user-images.githubusercontent.com/57821133/226590873-de62ca48-650c-4389-ba9d-91fe92844613.png)

It says "has been ded to the search path"; some part of the output was overwritten by user's input.

OH I THINK I KNOW THE PROBLEM NOW

> Umm, weird, cuz I opened another terminal and tried again, the problem was gone; 

This was because I tried inside of a **fullscreen** terminal, not one with window mode; the screen buffer was big enough to display everything.

```python
4nji@Gra ~> rlwrap ocaml
OCaml version 5.0.0
Enter #help;; for help.

# Unix.sleep 1;;
Alert ocaml_deprecated_auto_include:
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
# Unix.sleep 1;;ded to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
Error: Reference to undefined global `Unix'
#
4nji@Gra ~> python3 -c 'import os; print(os.get_terminal_size())'
os.terminal_size(columns=65, lines=17)
4nji@Gra ~>
```

If you use a terminal with not-that-big size buffer, you'll see the bug; this also explains why Termux had the same issue because Android smartphones all have quite small terminal sizes.

@nojb
