### ISSUE TITLE
Aliased exn type is not extensible

### ISSUE THREAD

**Issue by bobzhang** [ocaml/ocaml#9147] opened 2019-11-27 23:53 UTC
```
# Sys.ocaml_version;;
- : string = "4.08.1"
# type u = exn;;
type u = exn
# type u += A of int;;
Error: Type definition u is not extensible
# type exn += A of int;;
type exn += A of int

```
Note I think it is actually more helpful to make exn distinct from open types (exn is important), but this inconsistency is intentional?

**Comment by Octachron** [comment] 2019-11-28 09:01
This behavior is not specific to `exn` at all, you need to declare the aliased type u as extensible itself:

```OCaml
type u = exn = ..
type u += A of int
```

This should be precised in more detail in the manual.

**Comment by gasche** [comment] 2019-11-28 09:11
I find the behavior a bit surprising; when is it the right thing to do to close extensibility on aliasing, and why is it the default? (Could we have a syntax for closing extensibility if the other option was the default?).
cc @lpw25 @garrigue


I tend of think of `let/type/module/exception/etc. a = b`, when `a` and `b` are names in the appropriate syntactic category, as creating an alias that can be used in the exact same way the original name could, and any part of the system that breaks this expectation adds friction.

**Comment by trefis** [comment] 2019-11-28 10:04
How is that different from not reexporting labels / constructors?

**Comment by lpw25** [comment] 2019-11-28 10:07
The behaviour is indeed modeled on the behaviour of records and variants:
```ocaml
# type t = T;;
type t = T
# type s = t;;
type s = t
# type r = s = T;;
Line 1, characters 0-14:
1 | type r = s = T;;
    ^^^^^^^^^^^^^^
Error: This variant or record definition does not match that of type s
       Their kinds differ.
# type r = t = T;;
type r = t = T
```

**Comment by gasche** [comment] 2019-11-28 10:08
If I understand it correctly, your point is the following. If you alias a variant type, you don't automatically get the variant constructors in scope, you still have to  go through old type to access them (and old-type-variants are compatible with the alias type).  With exensible types, you don't automatically get the power to extend the lias, you still have to go through the old type to extend it (and newly-extended constructors are compatible with the alias type).

**Comment by xavierleroy** [comment] 2020-04-09 09:41
Is there any action required here?  I'd like to close this report.

**Comment by lpw25** [comment] 2020-04-09 16:52
This is the intended behaviour and I don't think there is a strong reason to change it, so I'm closing.

**Closed as completed by lpw25** 2020-04-09 16:52 UTC
