### ISSUE TITLE
Reason messages

### ISSUE THREAD

**Issue by ShalokShalom** [ocaml/ocaml#8633] opened 2019-04-22 10:54 UTC
Hi there :)

Do you consider improving your error messages?

Since 2 years ago, there was already a contribution which is obviously still not applied.

Is there a specific reason?

**Comment by gasche** [comment] 2019-04-22 12:38
Hi @ShalokShalom,

I'm not sure what you mean here, and what the issue is about.

1. Yes, we consider improving our error messages, and in fact we improve them regularly.
2. Are you talking about OCaml error messages or Reason error messages? For the latter, this is not the right repository to ask the question (but then again, you should probably give more details if you ask the question someplace else), the present repository is the OCaml compiler distribution.
3. I don't know which "contribution which was there since 2 years ago"  you mean, would you like to clarify?

Unless I misunderstood something, it looks like this issue is off-topic for the ocaml/ocaml repository and can be closed. I'm waiting for a clarification first.

**Comment by ShalokShalom** [comment] 2019-04-22 21:34
https://reasonml.github.io/blog/2017/08/25/way-nicer-error-messages.html

**Comment by gasche** [comment] 2019-04-23 08:37
Here is what I reverse-engineered from your messages (please make an effort to be more clear next time; handling issues is time-consuming): you are wondering if the work done to improve the Reason error messages will be integrated back into the OCaml compiler.

Here would be my answer: as of today, we received no contribution from the Reason people to backport this work upstream into the OCaml compiler. This may be due to the fact that they are not interested, or that they did not think of doing it, or that they assumed that we would do it (see below), or (most likely) that the difference between the frontend implementations makes it not-so-easy to backport without basically redoing the work. The reason frontend is a clean re-implementation of a language frontend, the OCaml frontend has more history and cruft, so some changes are not easy to do there (we are working on restructuring it, piece by piece).

We (OCaml maintainers) could of course have taken the initiative of backporting changes coming from the Reason frontend, but (1) each of us has different priorities and is already full of other things to work on and (2) it's not motivating to backport work of people who don't seem terribly interested in contributing to an upstreaming effort (maybe they are, but they don't know how to say it; or rather, they are probably too busy to work on it).

Finally: there have been regular efforts to improve the quality of OCaml error messages, mostly by @Octachron (working on typing error messages and clarity of warning texts) and @Armael (working on location printing, quoting the source code with an error, and contextual hints with the recent help of @Julow) in the past few releases. So there is active work in this general direction, it's just rather independent from the Reason work.

**Closed as completed by gasche** 2019-04-23 08:37 UTC

**Comment by ShalokShalom** [comment] 2019-04-23 13:06
Sorry, I thought its obvious. 2 years ago, someone told me that it is already possible to use with Bucklescript.

OCaml gets a lot of new drive in the last couple of years, so does functional programming in general.

Open source projects are known the be carried by less people and most of the time, they do this as a hobby.

Honestly, this seems to suggest that inviting new possible contributors is top priority. 

For everyone. 

Call me crazy, spending two to three decades on perfectionising a language and having error messages who are an error on their own seems counter intuitive.

I appreciate your investment into this project and also your reverse engineering my messages ;)

I hope the situation changes soon.
The huge adoption and positive feedback by languages like Elm, Reason and Eta shows that the world is ripe for sane messages in 2019.

Maybe OCaml is too. ^-^

**Comment by gasche** [comment] 2019-04-23 13:56
To be clear, the OCaml error messages *are* improving quite a bit these days (4.08 will be better than 4.07 which was better than 4.06 etc.), it's just that this work was done independently from the fine work on the Reason frontend.

(The Reason frontend is using technologies that were first developed in Merlin for OCaml, so in that sense it serves as a nice experiment for their integration in a compiler frontend rather than an interactive editor.)

**Comment by ShalokShalom** [comment] 2019-04-24 03:08
Nice to see. :D 

I may be ignorant about some implications: 

While the messages itself are surely difficult to pull off, the formating, coloring etc is supposedly simple?

I love the OCaml integration in vscode, which is also based on Merlin. (reasonml-vscode)

Thanks for the nice work :)
