### ISSUE TITLE
Compiler crash instead of error (with exception using inline record, and rectypes on)

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml/ocaml#10027] opened 2020-11-16 17:07 UTC
The following file
~~~ocaml
exception Foo of { foo : int }
let chaos _ = ()

let infer_inductive   =
  try ()
  with Foo u -> chaos u
~~~
compiled with -rectypes produces 
~~~
Fatal error: exception File "typing/env.ml", line 764, characters 26-32: Assertion failed
~~~

Tested with ocaml 4.09.1

**Comment by gasche** [comment] 2020-11-16 18:18
Thanks for the report! I can reproduce in the current development trunk. To be investigated...

**Comment by dra27** [comment] 2020-11-16 18:19
Indeed - it's been present since day 1 (i.e. 4.03) as well

**Comment by SkySkimmer** [comment] 2020-11-16 18:21
There was also a similar error with code that should compile https://github.com/coq/coq/pull/12653#issuecomment-728190478
But it seems to have disappeared between 4.05 and 4.09 so I didn't make a small test case.

**Comment by Keryan-dev** [comment] 2021-01-14 11:58
I dug into the code (in truck) to find a reason for this and learn a bit about typing/.

First, the minimal example I found where the bug occurs:
```ocaml
exception Foo of { foo : unit }

let infer =
  try ()
  with Foo u -> ()
```
This code should compile without errors (and does without -rectypes).

It seem the bug occurs only with an exception case on a constructor containing an inlined record. It does not appears when the data of the constructor is discarded (`Foo _ ->`) or opened (`Foo {foo} ->`).

An `assert false` is fired in the following case of Env.find_type:
https://github.com/ocaml/ocaml/blob/b890021a0bc624045cc33a5a8902610f7cef7bb1/typing/env.ml#L1007-L1010
which comes from a early series of tests, triggered by -rectypes, on the constructor starting in Ctype.occur:
https://github.com/ocaml/ocaml/blob/35bf02588380f03a7352049cc139f57ca42ae2cf/typing/ctype.ml#L1812-L1814
in particular, this code path contains one of the few calls (all are linked to -rectypes) to:
https://github.com/ocaml/ocaml/blob/b890021a0bc624045cc33a5a8902610f7cef7bb1/typing/ctype.ml#L334-L337
Obviously, `Foo` is not a known constructor in `Env.initial_safe_string`, hence the `assert false`.

I don't know how to fix this, as I don't understand (yet) how the bug does not occur with other patterns for the data of `Foo`. I feel this code path ought to be avoided all together, as it appears to be the case with other patterns.

Anyhow, I'm surprised to see Ctype.in_pervasives relying on a raise of `Not_found` given how many catches to `assert false` there is in Env.find_type. Maybe the fact that `Foo` is seen in Env.find_type as `LocalExt "Foo"` instead of `Regular(PIdent "Foo")` is the problem, since the Regular case is the only one to actually raise an exception ?

**Comment by SkySkimmer** [comment] 2022-01-17 08:47
Please stop closing bugs that are still present.

**Comment by gasche** [comment] 2022-01-17 09:04
I also dislike the github bot, but I think the intent is to remind people about issues (and push them towards closing the low-importance ones); keeping the issue open but forgotten by everyone is not a much better outcome. So yes, we need to fix this bug :-)

**Comment by gasche** [comment] 2023-01-13 14:03
I can reproduce the issue in 5.0 but not in trunk. I suspect that #11568 fixed the issue. I propose to wait a bit before closing, until one of:
- someone has the energy to check that #11568 fixes the issue
- or we release 5.1 and @SkySkimmer can confirm that the issue is gone for real in his real-world use-case as well

**Comment by SkySkimmer** [comment] 2023-01-13 14:16
There's no real world use case left because we stopped using rectypes. If you can't reproduce it should be fine to close.

**Comment by gasche** [comment] 2023-01-13 14:29
At least we can all  sleep soundly knowing that the tree fell in the forest.

**Closed as completed by gasche** 2023-01-13 14:29 UTC
Labels: bug
