### ISSUE TITLE
Toplevel show directive to use correct rec_status

### ISSUE THREAD

**Issue by wyn** [ocaml/ocaml#9094] opened 2019-11-06 10:35 UTC
Currently the toplevel show directive uses a rec_status of 
'Trec_first' or 'Trec_not' regardless of whether recursion is present.

**Comment by damiendoligez** [comment] 2020-04-03 11:15
Your report is not very explicit. Is this the problem you're trying to report ?
```
# type t = A of t;;
type t = A of t
# #show t;;
type nonrec t = A of t
```

**Comment by gasche** [comment] 2020-04-03 12:43
In fact there is some context information missing: this issue was filed in the context of #9086, specifically [this comment thread](https://github.com/ocaml/ocaml/pull/9086#discussion_r341810673). And yes, @damiendoligez repro case is an example of the issue. (The reason it was filed away instead of solved is that we didn't see an easy fix at the time of implementing the feature.)

**Comment by wyn** [comment] 2020-04-04 11:37
Hello, yes sorry, looking back it is rather terse.

I'd be happy to look into it again - we left it because we thought it was a lot of work for not so much gain but my reasons for wanting to help are more about learning the ocaml code base - I  dont really mind what I work on.

**Comment by yallop** [comment] 2020-05-09 05:47
I'm closing this as it's a duplicate of #7453.  (@wyn: if you're still interested in working on this, could we continue discussion under #7453?)

**Closed as completed by yallop** 2020-05-09 05:47 UTC
