### ISSUE TITLE
OCaml 5.0: segfault between alpha0 and alpha1

### ISSUE THREAD

**Issue by anmonteiro** [ocaml/ocaml#11485] opened 2022-08-10 04:14 UTC
I'm tracking a segfault in `ocaml-ssl` caused somewhere between 5.0.0-alpha0 and b82821134.

I'm still investigating further (and trying to produce a minimal example), but the segfault seems to originate from a call to `caml_raise_with_arg` here:

https://github.com/savonet/ocaml-ssl/blob/3799dca10f3db5a36bb3ad5ee3a38035a571acdc/src/ssl_stubs.c#L1462

I've confirmed that my code works with 5.0.0-alpha0, but not with 5.0.0-alpha1.

**Comment by gasche** [comment] 2022-08-10 07:37
Are you observing the segfault with bytecode, native code, or both?

**Comment by gasche** [comment] 2022-08-10 07:38
Note: building your program with the debug runtime (`-runtime-variant d`) might help by turning the segfault into an assertion failure.

**Comment by anmonteiro** [comment] 2022-08-10 09:35
I'll try that in the morning. In the meantime, I've managed to bisect to this commit: https://github.com/ocaml/ocaml/commit/4a58209d0b44cf422ec9aeb6c1b63dc215ba29f6

**Comment by gasche** [comment] 2022-08-10 16:26
(cc @gadmm)

Assuming this commit/PR you are pointing at (#11272) is correctly implemented and not buggy itself, it may provoke failures in code that was incorrect before, but would luckily work most of the time. (Arguably this is an advantage of reliably failing instead of having obscure failure scenarios.) Those "expected" extra failures would come from code that accesses the runtime state (Caml_state fields) without owning the (domain) runtime lock.

I don't see how specifically the `caml_raise_with_arg` you point out could be the place for an "expected extra failure", as it is just after `caml_leave_blocking_section` that should take the domain runtime lock again. Could you maybe assert that `Caml_state` is not `NULL` right before line 1461 (right after `caml_leave_blocking_section`) to rule this option out?

**Comment by gadmm** [comment] 2022-08-10 17:35
Since this is public code, do you have instructions to reproduce that you can share?

**Comment by anmonteiro** [comment] 2022-08-10 18:05
Running the Piaf client tests is how I found out about this e.g. this CI run https://github.com/anmonteiro/piaf/runs/7755250937?check_suite_focus=true

it might be a little hard to set everything there (which is why I want to create a minimal example), but I’m traveling today so won’t be able to put something together very soon

**Comment by anmonteiro** [comment] 2022-08-10 18:07
The caml_raise_with_arg clue might be misleading. I need to do further investigation. 

Sorry for the lack of detail here, and feel free not to follow up until I do in fact put something together that’s more concrete.

**Comment by gadmm** [comment] 2022-08-11 00:30
> Assuming this commit/PR you are pointing at (https://github.com/ocaml/ocaml/pull/11272) is correctly implemented and not buggy itself, it may provoke failures in code that was incorrect before, but would luckily work most of the time. (Arguably this is an advantage of reliably failing instead of having obscure failure scenarios.) Those "expected" extra failures would come from code that accesses the runtime state (Caml_state fields) without owning the (domain) runtime lock.

Right, and it is unknown whether some programs in the wild actually try to erroneously access `Caml_state` without the domain lock. If this is the case then we could improve the failure mode, so that they do not all start their investigation with the tedious task of bisecting the OCaml history.

Seeing that you are debugging with custom OCaml versions, here is a branch that adds an assertion when dereferencing `Caml_state`: https://github.com/gadmm/ocaml/tree/caml_state_assertion. To activate the assertion, run with the debug runtime as explained by Gabriel (or, replace CAMLassert with assert from <assert.h>). This will tell us whether the bug is in the program or in OCaml.

(Programs that _meaningfully_ dereference `Caml_state` without holding the domain lock interest me, but this does not seem possible by looking at the `Caml_state` fields present in OCaml 4.)

I agree with @gasche though that the code you showed does not seem to use `Caml_state` incorrectly. What is the nature of your clue regarding `caml_raise_with_arg`?

**Comment by anmonteiro** [comment] 2022-08-11 02:23
The `caml_raise_with_arg` clue was misleading indeed. Upon further investigation, this seems to be where I'm hitting the segfault: https://github.com/savonet/ocaml-ssl/blob/3799dca10f3db5a36bb3ad5ee3a38035a571acdc/src/ssl_stubs.c#L806-L814

I also put together a "minimal" repro -- it needs `dune` and `ocaml-ssl`, and a few certificates.

I've verified the following:
- happens in bytecode and native
- the segfault happens somewhere in the call to `CAMLlocal3`
- `Caml_state` is, in fact, `NULL`, before `CAMLlocal3`
- in SSL, `alpn_select_cb` is set in this part of the code: https://github.com/savonet/ocaml-ssl/blob/3799dca10f3db5a36bb3ad5ee3a38035a571acdc/src/ssl_stubs.c#L844-L849

@gadmm next, I'll try out your custom branch and report back. Thanks for the pointers!


EDIT: Forgot to link the repro gist: https://gist.github.com/anmonteiro/b1b17885b283292fb5fe9c7be9fa577e

**Comment by gasche** [comment] 2022-08-11 05:21
I think the issue is in this code indeed:

```c
static int alpn_select_cb(SSL *ssl,
                          const unsigned char **out,
                          unsigned char *outlen,
                          const unsigned char *in,
                          unsigned int inlen,
                          void *arg)
{
  CAMLparam0();
  CAMLlocal3(protocol_list, selected_protocol, selected_protocol_opt);

  caml_leave_blocking_section();
  [...]
  caml_enter_blocking_section();

  return SSL_TLSEXT_ERR_OK;
}
```

This function first registers local roots and then it re-acquires the runtime lock. This is unsafe, as registering local roots requires (~mutates) the runtime state.

I believe that you could rewrite this to start with a pure C function (no CAML{param,local,return}) that takes the runtime lock / leaves the blocking section, and immediately call a CAMLprim-style function with the meat of the implementation inside, so that `CAMLparam3` is only called while the runtime is held.

```c
static int alpn_select_cb(SSL *ssl,
                          const unsigned char **out,
                          unsigned char *outlen,
                          const unsigned char *in,
                          unsigned int inlen,
                          void *arg)
{
  int res;
  caml_leave_blocking_section();
  res = caml_alpn_select_cb(out, outlen, in, intlen, arg);
  caml_enter_blocking_section();
  return res;
}

CAMLprim int caml_alpn_select_cb(
  const unsigned char **out,
  unsigned char *outlen,
  const unsigned char *in,
  unsigned int inlen,
  void *arg)
{
  CAMLparam0();
  CAMLlocal3(protocol_list, selected_protocol, selected_protocol_opt);

  int len;

  protocol_list = build_alpn_protocol_list(in, inlen);
  selected_protocol_opt = caml_callback(*((value*)arg), protocol_list);

  if(selected_protocol_opt == Val_none)
  {
    CAMLreturn(SSL_TLSEXT_ERR_NOACK);
  }

  selected_protocol = Field(selected_protocol_opt, 0);
  len = caml_string_length(selected_protocol);
  *out = String_val(selected_protocol);
  *outlen = len;

  CAMLreturn(SSL_TLSEXT_ERR_OK);
}
```

Edit: there were also no CAMLreturn in the existing code, I added them above.

Note: unrelated to your specific bug, but looking at this code I'm a bit nervous about how the callback returns `String_val(...)` to the caller: as far as I understand this is a pointer into GC-owned memory, do you expect it to remain valid for the C side to use? I would rather have expected the code to perform a copy into a malloc-ed string, but I don't know who is in charge of freeing the memory owned by this callback.
Edit: if I understand correctly, in fact the output is expected to be a sub-string of the `in` parameter, rather than newly-allocated memory.

**Comment by gasche** [comment] 2022-08-11 05:48
Note: I believe that the issue here lies in the library C code that is taking liberties with the FFI correctness rules, so I propose to close this issue -- not as a way to close the discussion, I'm happy to help investigate and debug, but to mark that there does not seem to be a bug in the compiler distribution.

**Comment by gadmm** [comment] 2022-08-11 05:56
Indeed you have found the bug. It is also super unsafe to use `CAMLparam` without the runtime lock, so that's a win for #11272.

Let's keep this issue open while we discuss what can be improved:
- Does adding an assert which runs in debug mode helps? It could also be an unconditional assertion for `Caml_state` used by programmers, alongside some faster implementation without assertion for the runtime.
- Your example makes me think of arbitrary numbers of ways code accessing `Caml_state` could be accidentally correct: if the program uses `enter/leave_blocking_section` but actually does not use systhreads. For backwards-compatibility I could refine the implementation by not setting `Caml_state` to `NULL` if there are no systhreads, one domain and no backup threads. This makes sense: releasing the domain lock has no effect in this case, it is as if it is still held. Is this change welcome?

**Comment by gasche** [comment] 2022-08-11 09:07
Unless I misunderstand, this faulty code for example (registering local roots without owning the runtime lock) is not only unsafe in presence of OCaml's systhreads, but any parallelism in the C+OCaml program, for example use of pthreads from the C side (if OCaml code runs as a plugin within a larger application). Maybe those situations are rarely-used in practice that it's okay to neglect them?

My understanding of your question:
- there is buggy FFI code in the wild that should be fixed (because it is unsafe), and is much more likely to crash in multicore programs than in sequential programs
- the question is when we force people to fix their code: when they move from 4.x to 5.x, or when they move from a sequential to a multicore program?

Your suggestion to not set Caml_state to NULL in probably-sequential scenarios makes sense in the general context of 5.x design decisions that have gone largely towards preserving backwards-compatibility for sequential programs. Even if we apply it, there *is* a clear way for code authors to debug their code, by linking systhreads. But it makes the semantics more complex, and I'm worried that it will make reasoning about Caml_state NULLness more difficult, weakening the justification for the change in the first place.

For example in our use-case of OCaml/Rust FFI, you check Caml_state to know if we hold the runtime lock (otherwise we need more locking), but is it actually correct to assume that no locking is necessary simply because your heuristic suggests that the program is sequential? What if the Rust part drives the concurrency of the application?

Remark: We don't know yet the amount of affected FFI code out there. We are lucky that @anmonteiro ran ocaml-ssl tests with 5.x. Are there many more mistakes of this nature in the wild, or just a few? (We have the option to wait a bit more as 5.x gets rolled out, and make a compatibility change later if it turns out to be necessary in practice.)

In any case, I think we should put effort into making it very easy for code authors to debug the issue when they get bitten by it. We should definitely ensure that the debug runtime has as much assertions (and clear error messages) as necessary in this scenario, and document how to enable it in real-world scenario (for example runtime/HACKING.adoc should document how to enable it from Dune). I don't know if there is something else that we should consider doing, outside the debug mode.

**Comment by anmonteiro** [comment] 2022-08-11 20:07
> This function first registers local roots and then it re-acquires the runtime lock. This is unsafe, as registering local roots requires (~mutates) the runtime state.

@gasche so `CAMLlocal*` registers local roots. Does `CAMLparam*` also do the same? I wasn't aware of this failure mode. Maybe I need to go back and re-read the "Interfacing OCaml with C" Chapter.

EDIT: @gadmm mentions: 
> Indeed you have found the bug. It is also super unsafe to use CAMLparam without the runtime lock, so that's a win for https://github.com/ocaml/ocaml/pull/11272.

**Comment by anmonteiro** [comment] 2022-08-11 20:14
Update: as a naive verification that @gasche is correct, moving the call to acquire the runtime system to the very top of the function body makes the code work.

**Comment by gadmm** [comment] 2022-08-11 20:46
> We should definitely ensure that the debug runtime has as much assertions (and clear error messages) as necessary in this scenario, and document how to enable it in real-world scenario (for example runtime/HACKING.adoc should document how to enable it from Dune).

@anmonteiro We are interested in feedback in this area.

@gasche CAMLassert does not have a custom error message. It is easy to implement but it makes me think that CAMLassert is not really destined for users. Hence why I was thinking of checking outside of debug mode with a caml_fatal_error instead (which also has a customizable hook). Since the runtime is already written around the assumption that Caml_state might be slow, and the potential impact concerns micro-architectural effects (such as code size), running benchmarks is the only way to know if this is too costly.

**Comment by gadmm** [comment] 2022-08-11 20:47
> Does CAMLparam* also do the same?

It sets up for CAMLlocal and accesses `Caml_state`.

**Comment by gadmm** [comment] 2022-08-11 20:52
> But it makes the semantics more complex, and I'm worried that it will make reasoning about Caml_state NULLness more difficult, weakening the justification for the change in the first place.

* Regarding unregistered C threads, `Caml_state` will remain `NULL` for those.
* The point is that the reasoning is the same. Indeed it is safe to access `Caml_state` in this situation; it is as if the domain lock is still held (in OCaml 4: indeed no lock is released when calling `enter_blocking`; in OCaml 5: a lock is released but this has no impact, as there can be no races anyway). For ocaml-boxroot, this behaves correctly.

**Comment by gasche** [comment] 2022-08-12 06:10
I'm moving to close this: there is no fix required in the compiler codebase, and ocaml-ssl has been fixed. We don't need to let a "segfault" issue open that will worry other maintainers. We can of course keep discussing.

**Closed as completed by gasche** 2022-08-12 06:10 UTC

**Comment by gasche** [comment] 2022-08-12 06:49
> Hence why I was thinking of checking outside of debug mode with a caml_fatal_error instead (which also has a customizable hook). Since the runtime is already written around the assumption that Caml_state might be slow, and the potential impact concerns micro-architectural effects (such as code size), running benchmarks is the only way to know if this is too costly.

Sure, we could try that, and run Sandmark benchmarks. Would you want to take care of proposing a PR?

**Comment by gasche** [comment] 2022-08-12 14:35
@gadmm your arguments are convincing that your proposal to "keep the lock in the no-threads single-domain scenario" is an extension of the 4.x semantics. (Do you plan to just keep Caml_state around, or actually elide the domain_lock as well?) I think you could send a separate PR for this for broader discussion with other people.

**Comment by anmonteiro** [comment] 2022-08-12 19:46
> @anmonteiro We are interested in feedback in this area.

I don't know if I'm qualified to provide feedback here, but a compiler mode that can tell me whether my FFI is unsafe would be great.

**Comment by xavierleroy** [comment] 2022-08-14 16:14
> a compiler mode that can tell me whether my FFI is unsafe would be great.

The problem is in the C stub code, so the OCaml compiler cannot do anything about it.  However, it is likely that a static analyzer operating on the C stub code could find the bug, see https://doi.org/10.1145/1064978.1065019 .

**Comment by gadmm** [comment] 2022-08-23 19:56
@gasche At #11506, I introduce run-time checks that the domain lock is held. Instead of checking unconditionally whenever Caml_state is called, I only introduce checks at key C API entry points, notably `CAMLparam`. In many cases (e.g. CAMLprim functions called from OCaml), checking is unnecessary. This avoids having to run Sandmark benchmarks.

I think this is a much better failure mode than a segfault.
