### ISSUE TITLE
More detailed error messages

### ISSUE THREAD

**Issue by anzhi0708** [ocaml/ocaml#11721] opened 2022-11-13 02:44 UTC
Hello, as a Ocaml beginner, I really wish Ocaml to print more detailed error information like Python 3.11 instead of simple "Error: Syntax error"

:3

**Comment by dra27** [comment] 2022-11-13 12:55
It turns out that displaying a more precise error message in this case is surprisingly difficult! There is significant ongoing work to improve this which is mentioned in https://github.com/ocaml/ocaml/issues/5068

I’m going to close this as a duplicate of that issue, but the current message is definitely not something we intend to keep.

**Closed as not planned by dra27** 2022-11-13 12:55 UTC
Labels: feature-wish
