### ISSUE TITLE
[5.3] typechecker crash while typing objects

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#13495] opened 2024-09-29 09:59 UTC
```
nojebar@PERVERSESHEAF:~/tmp$ cat bug.ml
class type gui =
  object
    method sub: 'b. 'b -> 'b
  end

class virtual local_sub =
  object
    method virtual sub: 'b. 'b -> 'b option
  end

class virtual ['a] compound_gui =
  object (_: #gui)
    constraint 'a = #local_sub
  end
nojebar@PERVERSESHEAF:~/tmp$ opam exec --switch 4.14.2 -- ocaml bug.ml
nojebar@PERVERSESHEAF:~/tmp$ opam exec --switch 5.1.0 -- ocaml bug.ml
nojebar@PERVERSESHEAF:~/tmp$ opam exec --switch 5.2.0 -- ocaml bug.ml
nojebar@PERVERSESHEAF:~/tmp$ opam exec --switch 5.3.0+trunk -- ocaml bug.ml
>> Fatal error: Ctype.unify_univar: univar not in scope
Fatal error: exception Misc.Fatal_error
```
(The example is extracted from a much larger codebase.)

**Comment by gasche** [comment] 2024-09-29 10:12
Amusing hostname! :-)

Curated backtrace:

```
Raised at Misc.fatal_errorf.(fun) in file "utils/misc.ml", line 22, characters 14-31
Called from Ctype.unify_univar_for in file "typing/ctype.ml", line 1986, characters 6-37
Called from Ctype.eqtype in file "typing/ctype.ml", line 4200, characters 14-61
Called from Ctype.eqtype in file "typing/ctype.ml", line 4165, characters 14-54
[...]
Called from Ctype.equal in file "typing/ctype.ml", line 4353, characters 6-78
Called from Ctype.is_equal in file "typing/ctype.ml", line 4358, characters 8-34
Called from Typedecl_variance.compute_variance_type.check.(fun) in file "typing/typedecl_variance.ml", line 201, characters 16-49
Called from Stdlib__Map.Make.fold in file "map.ml", line 329, characters 19-42
Called from Typedecl_variance.compute_variance_type.check in file "typing/typedecl_variance.ml", lines 199-202, characters 8-20
[...]
Called from Typedecl_variance.compute_variance_type in file "typing/typedecl_variance.ml", line 228, characters 4-42
Called from Typedecl_variance.compute_variance_decl in file "typing/typedecl_variance.ml", line 325, characters 10-55
Called from Typedecl_variance.check_decl in file "typing/typedecl_variance.ml", line 373, characters 9-79
Called from Typedecl_properties.compute_property.compute_fixpoint in file "typing/typedecl_properties.ml", lines 63-65, characters 6-26
Called from Typedecl_variance.update_class_decls in file "typing/typedecl_variance.ml", line 428, characters 4-68
Called from Typeclass.type_classes in file "typing/typeclass.ml", line 1858, characters 8-54
Called from Typeclass.class_declarations in file "typing/typeclass.ml", line 1885, characters 4-66
```

**Comment by gasche** [comment] 2024-09-29 10:14
The problem is reproducible in the 5.3 maintenance branch, it is not more recent than the 5.3 branching, so we can bisect it between 5.2 and 5.3.

**Comment by Octachron** [comment] 2024-09-29 10:20
The fatal error is from #12920 .

**Comment by gasche** [comment] 2024-09-29 13:23
My understanding is that the bug is in the code that checks variance of type declarations, in the case where some type variables of the type are introduced through constraints (and not bound as type parameters of the declaration).

https://github.com/ocaml/ocaml/blob/d540076b95b99d1bd1d04850ff3b76cf251864f3/typing/typedecl_variance.ml#L176-L203

The fatal error arises from `Ctype.is_equal env false [ty] [t]`, where I *think* that `ty` is one of the toplevel type expressions whose variance is checked, and `t` is a subexpression (with its variance) in one of the, ahem, probably one of the constraining types that are being checked. `t` being a subexpression (from `tvl2`, accumulated by the `compute_variance` call earlier), it may be under `Tpoly` nodes, that is, its univar scope may be distinct from the one in `ty`, and I think that explains why we see the fatal error.

The fix probably involves understanding this code better, and then thinking of how to change it so that we don't compare types that have distinct univar scopes, or figuring how we want to compare types in distinct scopes. (We could collect the `Tpoly` variables as we traverse subexpressions in `compute_variance`.)

(I haven't tried looking at which hidden type declaration is being variance-checked in this example and why it involves univars, which would also be useful.)

**Comment by gasche** [comment] 2024-10-01 07:04
(I think that it would be helpful to get @garrigue on this issue, maybe to suggest a fix or at least to explain more clearly what the code is doing and why.)

**Comment by garrigue** [comment] 2024-10-03 05:19
The code here is a transcription of the explanation in https://www.math.nagoya-u.ac.jp/~garrigue/papers/injectivity2.pdf, particularly the last paragraph of section 2. Namely, since injectivity annotations are on type parameters, in presence of constraints a first approximation is to check that all type variables appearing inside the parameter are injective in the body. However, this does not cover the case where the variable is under a non-injective type constructor inside the parameter. To handle that case we need to check the occurrences of this constructor (with the same parameters), hence the use of `is_equal`. However, this leads to compare types coming from different contexts. So the sound thing would be just to ignore that specific type in case of errors. I will try to come up with a fix in that direction, i.e. a more precise handling of failure rather than a fatal error.

**Closed as completed** 2024-11-07 05:00 UTC
Labels: bug

**Comment by nojb** [comment] 2024-11-07 05:02
Thanks for the fix @garrigue!
