### ISSUE TITLE
Feature request: Make empty types subtype of any other type

### ISSUE THREAD

**Issue by tperami** [ocaml/ocaml#9459] opened 2020-04-17 17:03 UTC
My problem is that `type empty = |` is not a subtype of other types when it could perfectly be:

```ocaml 
val x : empty 
(* ... *)
let y : int = x
```

Currently the output is : 

```
Error: This expression has type empty but an expression was expected of type int
```

But it could perfectly be allowed (at type level) in theory

## Why is it useful?

In my current use-case I have some AST-like type with optional features like:

```ocaml
type 'a ast = Feature of 'a | Normal of int | Operation of 'a t * 'a t
```

The two types used in my code are `int ast` when I want the feature and `empty ast` when I do not want it. In theory any member of type `empty ast` could be directly converted in `int ast` and I 
have a function that does this
```ocaml
let conv : empty ast -> 'any ast = Obj.magic
```

However it is really annoying to have to write such function using `Obj.magic` and writing it in a type-safe way would mean copying the entire object in memory. On the other hand using `conv` is entirely safe. 

Making `empty` a subtype of any other type would mean that I can send an `empty ast` to any function that uses a `int ast` without even needing to call `conv`. 
I could use polymorphic variant and accept the runtime and memory overhead but it seems inappropriate for just one on/off switch.

**Comment by yallop** [comment] 2020-04-17 17:38
> ```ocaml
> let conv : empty ast -> 'any ast = Obj.magic
> ```

This *[edit: i.e. writing functions like `conv`]* isn't a good idea.  Here's a program that uses a very similar function:

```ocaml
type empty = |
let conv : empty list ref -> 'any list ref = Obj.magic

let s = ref []
let () = begin
    conv s := [0];
    print_endline (List.hd (!(conv s)))
end
```

And here's what happens when the program is run:

```bash
$ ocaml conv.ml 
Segmentation fault
```

> I could use polymorphic variant

That's a better idea.

**Comment by gasche** [comment] 2020-04-17 19:49
You don't need to use polymorphic variants or `Obj.magic`, you can *implement* `conv` in your example:

```ocaml
type empty = | 

type 'a ast = Feature of 'a | Normal of int | Operation of 'a ast * 'a ast

let rec conv : empty ast -> 'a ast = function
  | Feature _ -> .
  | Normal n -> Normal n
  | Operation (a, b) -> Operation (conv a, conv b)
```

See [refutation cases](https://caml.inria.fr/pub/docs/manual-ocaml/gadts.html#p:gadt-refutation-cases) in the manual for the "dot" syntax.

**Comment by gasche** [comment] 2020-04-17 19:51
Finally: in OCaml we try to be very strict about limiting the use of subtyping in the source language, because it is not inferred very well and generally our programs favor nice polymorphism over nice subtyping. In particular there is no "width subtyping" for ordinary variant datatypes, only in polymorphic variants (which come with extra complexity). I don't think that there is any plan to add subtyping to ordinary variant datatypes, or even to add it only in the empty setting.

For this reason, and given that alternatives are available, I propose to close the issue.

**Comment by tperami** [comment] 2020-04-20 10:15
@yallop `ast` is a covariant type whereas `ref` is not, this means that even after the proposed changes, your function `conv` will still not be able to type because it is wrong on a memory safety point of view. On the other hand my `conv` is currently memory-safe and will be made type-safe by the proposed change because the `ast` type constructor is a plain immutable variant type and so it is covariant.

@gasche Yes, I know that you can write conv in a type-safe way, but as I said previously, if you have a big tree of type `empty ast`, the type-safe version of `conv` will make a full copy of it and there is no other way in the type-safe world because `empty ast` and `'a ast` for a different `'a` are considered incompatible by the type checker currently.

I'm not asking for variant subtyping at all, That wouldn't fit into OCaml (I think). I'm just asking for a true bottom type being a subtype of any other. I do not propose to force that `empty ast <: int ast`, I propose that, because `empty` is a bottom type then `empty <: 'a` holds for any 'a and thus we have `empty <: int` and thus as `ast` is covariant, `empty ast <: 'a ast` follows. On the other hand I realized that doing this for all empty types but having a reflexive transitive sub-typing would mean merging all empty types which may not be desirable. A way to avoid this would be to provide a true `bot` type in the language and make that only this one has the sub-typing property.

I also though of representing the `empty ast` type as `forall 'a. 'a ast` but to my knowledge there is no way of writing such a type in the OCaml type system. On the other hand in that case if would just be a matter of type variable instantiation and not subtyping. 

Finally, I though that because subtyping for objects and polymorphic variant was already implemented, this would not be a big addition, but if you think this is going to affect any kind of trade-off you made with polymorphism or type-inference, and could become a big and annoying change, then I'm happy to bury this issue and to to continue using `conv` when needed`

For a final remark, one of the main reason I can't use polymorphic variant is because the actual `ast` type is large and generated by an external tool and I only control the top-level type parameters (I can add a type parameter `'a` at the top and then say a given constructor has type `'a`).

**Comment by yallop** [comment] 2020-04-20 10:27
> @yallop `ast` is a covariant type whereas `ref` is not, this means that even after the proposed changes, your function conv will still not be able to type

My point is that it's not a good idea to write `conv` using `Obj.magic`, precisely because it depends on covariance, but doesn't check covariance.  Even if `ast` is covariant when `conv` is written, if the definition of `ast` changes so that it is no longer covariant, then `conv` will silently become unsafe.

Thinking about it a bit more, though, you could improve your `magic`-based implementation of `conv` by adding a check that `ast` is covariant to catch this problem:

```ocaml
   let conv : empty ast -> 'any ast = 
     let module M : sig type +'a t end = struct type 'a t = 'a ast end in
     Obj.magic
```

> I also though of representing the `empty ast` type as `forall 'a. 'a ast` but to my knowledge there is no way of writing such a type in the OCaml type system.

You can write the following:
```ocaml
type empty_ast = {ast: 'a. 'a ast} [@@unboxed]
```
although I think you'll run into problems with this approach if `ast` is used within its own definition.

**Comment by tperami** [comment] 2020-04-20 10:47
@yallop I see your point, and the method to check the covariance is actually really useful, thank you for that. I was also wondering about maintenance of that, and this is a great solution.

The problem of writing `empty ast` as a record is that it disallows any polymorphic function that takes a `'a ast` to run on `empty_ast` without the user doing `.ast` access whereas with `empty ast` it works directly and I have a lot of function that have polymorphic types over `ast` value (like `map`, `iter`, ...)

**Comment by gasche** [comment] 2020-04-20 12:01
Indeed, the `empty` variant is not a bottom type.

Obj.magic will make your life miserable in many ways. If you are using it here to avoid a copy of a datastructure, you will reach for it in many other places and eventually pay for it. I believe that the reasonable thing is to do a copy here.

> I also though of representing the empty ast type as forall 'a. 'a ast but to my knowledge there is no way of writing such a type in the OCaml type system.

```ocaml
type poly_ast = { ast : 'a . 'a ast }
```

**Comment by alainfrisch** [comment] 2020-04-20 12:29
> On the other hand I realized that doing this for all empty types but having a reflexive transitive sub-typing would mean merging all empty types which may not be desirable.

I don't think that sub-typing needs to be antisymmetric.  It's ok to have two types subtype of each other without being equal (in terms of the "unification" equality).  Whether we want to make all empty types subtype of all types is another question, but I believe it is sound to do it (it would be a special case of making a sum type subtype of another sum type which only adds more constructors).

**Comment by garrigue** [comment] 2020-04-20 13:23
Indeed, I do not see anything wrong in allowing subtyping between empty types and other types, as long as we don't introduce weird inlining optimisations, such as changing the deep representation of types that contain empty cases. We are already relying on this subtyping for the relaxed value restriction, so this should be perfectly sound.
This said, while I'm sometimes wondering why we made the choice of defining empty types as generative, this would clearly break (at least partially) this generativity, since they would become equal at all covariant (or contravariant) positions.
So we come back to the question: **Why are empty types generative ?**

**Comment by alainfrisch** [comment] 2020-04-20 13:29
>  since they would become equal at all covariant (or contravariant) positions.

Equal in what sense?  They would remain different for the type equality, no?  Subtyping is an explicit operation which behaves like an automatically generated copying function (optimized to be compiled as the identity), no?

**Comment by yallop** [comment] 2020-04-20 13:31
Empty types are generative because they're variants.  If they weren't generative there'd be a discontinuity leading to complicated properties like "`'a t` is injective in `'a` for variant types *unless `t` is empty*".

**Comment by garrigue** [comment] 2020-04-20 13:44
@alainfrisch I mean that they would become undistinguishable in some situations.
I do not see it as a problem, rather why do we need to distinguish them to start with.

@yallop I understand why empty types end up being generative. But my question is rather, is there any advantage in their being generative, and what would be the problem in their being undistinguishable, from a practical point of view.

Note that I am not suggesting to really enforce this identification: there are many ways to define empty types, include some for which the emptiness could be impossible to check.

**Comment by DemiMarie** [comment] 2020-11-01 20:26
@gasche I don’t think that making a copy is always the reasonable choice.  In particular, it can harm the asymptotic performance of some algorithms.  @yallop’s solution is guaranteed to be safe, and could be wrapped in a library.

**Comment by gasche** [comment] 2020-11-02 09:45
I have seen the impact of this reasoning in large, complex codebases with weird uses of Obj.magic with comments explaining why they were "guaranteed to be safe", often to encode GADTs (before they were introduced in the language). Sure you can do this, but this amounts to trusting programmers to reason correctly about an advanced, complex and not-so-well-specified corner of the language. In my experience, sometimes this trust is justified, sometimes it isn't, and the few cases were it isn't can end up costing a lot of time and effort down the road (as in: fixing a segfault in a XML parsing library that used Obj.magic for reasons that sounded "guaranteed to be safe" to the people who wrote the code, and started segfaulting years after they stopped actively maintaining it.)

I'm happy to let people make the decisions, but I think it is also interesting to discuss changes/improvements to the language that make them unnecessary. In this particular case, I'm not convinced by the idea of using subtyping with empty variants: variants are generative types, the subtyping relation only relates a variant to itself with different parameters, and treating the empty variant specially sounds dangereous to me. I see several directions in which one could try to go, in the *long* term:

- If we decide that we really care about empty types and their subtyping relation, we could have a built-in empty type (we could call it `void` to troll both C and Haskell people) which really is a subtype of other types.
- We could aim for better support of higher-order quantification, so that people write `(forall 'a. 'a ast)` instead of `empty ast` and the problem goes away.
- The explicit `conv` function I implemented in https://github.com/ocaml/ocaml/issues/9459#issuecomment-615433952 has the very specific structure of an identity function: with a hint from the user, the compiler could easily prove that it returns its input unchanged, and turn it into a no-op. Many other such functions show up when you start using more typeful programming (in Mezzo for example "freezing" functions have this structure), and I am skeptical that OCaml's builtin subtyping will ever be made flexible enough to accomodate all of them. So this could be of interest for other use-cases.

I am not sure about the case of identity-looking functions on types with mutable fields. (Say `Normal of { mutable v : int }` in the example above; no type parameter in mutable position.) The approach of "implementing coercions" (as functions recognized as identities after the fact) does not scale to this case, as the copy becomes observable. But I think that `Normal _ as v -> v` should be able to generalize the type of `v` correctly, this would need checking.

**Comment by tperami** [comment] 2020-11-02 11:08
If I may have an opinion, all the three option sound good to me. The last one sounds especially good to me because it may be able to work in more cases, like when you enforce rules at type-level without changing the structure behind (for example converting a read-write array in a read-only array). However it sound a bit more complex to implement than the sub-typing solution.

My specific remarks are:
- If we go with sub-typing, I agree that having an explicit type `void` that has the property of being a sub-type of other types without having to "detect" that a type is empty will make this much more understandable. I was originally proposing it only for types explicitly defined as `type t = |` because it is already obvious and explicit that the type is empty.
- Generic forall sounds complicated to manage well with understandable rules. I'm not a type-system expert but it also sounds a bit undecidable. For example when doing `Operation(a,b)` with `a b : (forall 'a. 'a ast)` we want to infer a new `(forall 'a. 'a ast)`, or on the other hand, preserving the forall when you do a match destruction. But if you thinks it is doable, it may be interesting for a wider class of problems. Nevertheless it seems that this solution will require much more work that this issue alone is worth.
- No-op functions could be made easier to use and more enforceable by adding a explicit attribute `[@noop]` to them and then the compiler would accept them only if it manages to prove that the function is indeed a no-op. That allow developer to be able to rely on the optimization for software where performance is important, and be warned if the compiler suddenly cannot prove that the function is a no-op and drops the optimization. 
Furthermore this allow to do it with only intra-procedural reasoning for the compiler: If a external function is called and also has the attribute `[@noop]` the compiler can assume it is a no-op for the current function analysis. Otherwise it assumes it is not a no-op. This also true when proving that a recursive function is a no-op. Recursive call can be assumed to be no-op by induction. This proof by induction would only be true if the function terminates, so it would be able to replace an infinite loop by a no-op. This seems fine to me but it may not agree with the official semantics of OCaml about non-terminating programs.
Finally if this appear everywhere including in mli interfaces, this may make programmer less afraid of making and using API with multiple types representing the same thing with the same data-structure but different access right, because they are certain that when calling a no-op function, it will really do nothing (and be inlined to oblivion). 
However no-op propagation can be complex in high-order programing, for example, in theory `List.map f` where `f` is no-op should also be a no-op but it is not trivial to enforce. While with subtyping, if `empty <: 'a` then `empty ast <: 'a ast` and thus `empty ast list <: 'a ast list`, therefore the no-op cast can be deduced easily.

**Comment by stedolan** [comment] 2020-11-02 11:41
Here is another proposal. We currently allow:

    type t = |

as the 0-constructor case of variants. We could also allow

    type t = [<]

as the 0-constructor case of polymorphic variants. (This type could equivalently be written as either `[]` or `[<]`, but I propose the latter to avoid conflicts with the type that has the empty list as its only constructor).

This type is a structural type rather than a generative, nominal one, so I don't think there are the same problems with adding a subtyping rule from `[<]` to `'a`. Most of the machinery for this type is already in the typechecker, but the parser doesn't currently allow the empty polymorphic variant.

**Comment by gadmm** [comment] 2020-11-02 12:50
In [Cong et al. (2019)](http://dl.acm.org/citation.cfm?doid=3352468.3341643), the empty type is treated specially to optimise into jumps the calls to functions that do not return. This is necessary for an efficient representation of continuations as functions. Would such an optimisation in OCaml for functions of type `t -> empty` require `empty = |` to be generative?

**Comment by stedolan** [comment] 2020-11-02 12:58
> Would such an optimisation in OCaml for functions of type t -> | require it to be generative?

I don't see why it would. I don't see how that optimisation has anything to do with generativity, could you explain?

**Comment by gadmm** [comment] 2020-11-02 13:00
Thanks, that's a good enough answer for me. I didn't have anything specific, but I wanted to make sure that this was considered.

**Comment by gasche** [comment] 2020-11-02 16:00
Before we embark in deep changes to the type-system, I think it would be important to know that we really have an important use-case -- otherwise there are many uses of our time that would benefit OCaml just as well or more. Sure, in the abstract, nobody likes copying values, but do we have a specific use-case where better support for such a feature would make a strong difference for the application at hand?

Regarding no-op functions. Note that there is a strong relation between subtyping and identity functions: identity functions are the *semantic* behavior underlying subtyping as a static mechanism. The subtyping relation gives a family of identify functions `fun (x : a) -> (x : b)`, but in theory we could also *inject* any identity function as a subtyping coercion. (This is well-known by several participants to this thread, but I'm providing context.) This has benefits, in particular it can be plugged in covariant position within a bigger type context. But it also makes the subtyping relation harder to work with. (In particular injecting `type empty = |` into anything is clearly sound in a core language by this reasoning, but that doesn't mean it wouldn't blow up in our face as unexpected interactions or just type-system complexity.) The a-posteriori recognition of identity functions that I proposed above is a compromise that is simple to design and implement, and gets part of the benefits (an implicit coercion, but only at the toplevel).

**Comment by Drup** [comment] 2020-11-02 16:10
There is one difference: coercions compose well up to data-structure/high order functions when abstraction is involved, while identity function generally do not. In particular, having to write `List.map some_identity_with_fancy_typing` always makes me very sad (and yes, I do have concrete examples, in tyxml notably). You might argue that the optimizer could recognize this, but I doubt we are there yet.

That being said, a `@noop` annotation on functions that makes the optimizer warns if it can't make it the identity (in the style of the `@tailrec` annotation) would definitely be useful.

**Comment by gasche** [comment] 2020-11-02 16:13
This is what I meant with

> This has benefits, in particular it can be plugged in covariant position within a bigger type context.

Thanks for the clarification.

**Comment by garrigue** [comment] 2020-11-03 01:14
Again, I do not see why this proposal generates so much opposition. This is trivial to implement, and would give modest benefits to users. I don't see where it would blow up the complexity: subtyping is already costly in ocaml, this is why it has to be done explicitly. Actually, this case is very similar to private type abbreviations, except that it doesn't require the supertype to be known.
Also, the original AST example doesn't look absurd to me. Not having to introduce a GADT does have advantages.
(If I were the one who introduced empty types, I suppose this subtyping would have been there from the beginning, since it is pretty natural.)

**Comment by lpw25** [comment] 2020-11-03 09:29
Personally, I would find it odd to allow empty variants to be coerced without also allowing other types to coerced based on their representation. If we were to allow:
```ocaml
type t = A | B
type s = A
let f x = (x : s :> t)
```
then the empty type coercing to anything would be unsurprising. I think either you take into account a data type's representation for coercions or you don't: doing it only in one special case is just weird.

(Note that I am using the word *representation* here in the sense [used by the OCaml manual](https://caml.inria.fr/pub/docs/manual-ocaml/typedecl.html) rather than the broader sense of how the type is laid out in memory)

**Comment by mikeshulman** [comment] 2021-09-20 17:11
Nothing seems to have happened on this for a while, but I wanted to register my opposition to it as well.  I agree with what @lpw25 said last: there's a lot of virtue in the consistency of treating empty types just like any other variant type, not least because it reduces user surprise.  Moreover, there's an alternative mentioned above by @stedolan that would actually make things *more* consistent rather than less, namely introduce user syntax such as `[<]` (or perhaps `[|]`, to align with "`type empty = |`") for the empty *polymorphic* variant (which apparently [already exists](https://discuss.ocaml.org/t/empty-polymorphic-variant-type/8467/4) in the compiler).  It seems to me that this would solve the problem in the original issue for any concrete type such as `int`, at the expense of replacing it by a polymorphic variant wrapper such as ``[`Int of int]``:

```ocaml
type +'a ast = Feature of 'a | Normal of int | Operation of 'a ast * 'a ast
let conv : [<] ast -> [ `Int of int ] ast = fun x -> (x :> [ `Int of int ] ast)
```

(Naively, it seems to me like it ought to be possible to write a generic `conv : [<] ast -> [>] ast` as well, but I can't get OCaml to accept anything of the sort, so maybe not.)

**Comment by DemiMarie** [comment] 2021-09-20 17:28
Perhaps the empty polymorphic variant could be made an actual bottom type?  That has the advantage of being unique (since polymorphic variants are structural).

**Comment by mikeshulman** [comment] 2021-09-20 17:31
I agree that that would be better than doing the same with a non-polymorphic empty variant, but I still wouldn't like it.

**Comment by DemiMarie** [comment] 2021-09-20 17:43
> I agree that that would be better than doing the same with a non-polymorphic empty variant, but I still wouldn't like it.

Why is that?

> ```ocaml
> type +'a ast = Feature of 'a | Normal of int | Operation of 'a ast * 'a ast
> let conv : [<] ast -> [ `Int of int ] ast = fun x -> (x :> [ `Int of int ] ast)
> ```

I am not a fan of this approach: ``[ `Int of int ] ast`` consumes more memory and has more indirections than a plain `int ast`, and so this solution comes with a performance penalty.  I would not at all be surprised if that penalty is significant.

@yallop’s solution (which is fully safe to use) is my preferred solution with current OCaml.

**Comment by mikeshulman** [comment] 2021-09-20 17:45
Because unexpected special cases are inconsistent and can surprise the user, leading to hard-to-find bugs.  An empty variant should be just a variant that has no constructors.  Similarly for an empty polymorphic variant.

**Comment by garrigue** [comment] 2021-09-21 02:38
There is a problem with this approach: empty polymorphic variant types are currently treated as errors by the type-checker, to avoid letting the user write meaningless code. Allowing it would make polymorphic variants less usable.
On the other hand, there is some demand for allowing them as phantom type parameters.

Honestly, I'm a bit dumbfounded by this discussion, and still don't understand why we need to have multiple empty types in the language. Is there any concrete application for this distinction?
I.e., for normal sum types, it is clear enough that generativity has some role in avoiding mix-ups, but empty types denote impossible situations. Is anybody using them to distinguish between failures for instance?

**Comment by mikeshulman** [comment] 2021-09-21 05:36
Well, personally speaking, I'm a mathematician, and at least in the kind of mathematics I do (category theory and type theory), it's a general rule that no matter how tempting it is to make special cases for empty sets, if you do you'll regret it later.  (-:

In this particular instance, to me the issue is not that there are applications that *require* generative empty types, but that generativity is the *logical* behavior (since empty types are variants and variants are generative); thus people will naturally assume it to hold, and get bitten if it turns out not to.  For instance, I have used empty types as "dummy indices" for constructors of a GADT.  Sure, I could also use unit types, but I expected empty types to work, and chose them as a way of emphasizing that the elements of the types don't matter, only their identities.

OCaml has a beautiful and powerful type system, one of whose virtues is that it is well-organized and logical, making it easier to remember how each type works and use them correctly.  Please don't spoil it by introducing *ad hoc* special cases, even if they would be occasionally useful.

In what way would empty polymorphic variants make polymorphic variants less usable?

**Comment by garrigue** [comment] 2021-09-21 06:05
Actually, your example precisely gives a reason why distinguishing empty types is confusing: once you leave the current module, in ocaml you have no way to distinguish types for sure other than their structural definitions (i.e. variants are not really generative).
This is why, for GADT indices, you should never write
```ocaml
type zero
type 'a succ
```
but rather
```ocaml
type zero = Zero
type 'a succ = Succ
```
If you use empty types for `zero` and `succ` you will exactly get the same problem, and you have no way to distinguish them by value constructor names.
(Actually my proposal of nominal types would allow that, but it's another story)

**Comment by mikeshulman** [comment] 2021-09-21 14:52
Yes, I've noticed that too.  If I understand correctly, the empty types are technically generative, but a module signature has no way to indicate that an empty type was newly generated, so that outside the module you can't rely on its generatedness.  If this is unavoidable, I could see this as an argument for going all the way and having only one empty type, but in that case I think it would be better to deprecate the syntax `type empty = |`, which *looks* generative, in favor of having the unique empty type predefined.

I still wouldn't want the empty type to be a subtype of everything, though.

**Comment by DemiMarie** [comment] 2021-09-21 17:40
What about a dedicated bottom type, that is (by design) the subtype of every other type?

**Comment by mikeshulman** [comment] 2021-09-21 17:54
I worry that the more subtyping relations there are, especially ones that are special-cased to deal with particular types rather than instances of a general principle, the more complicated and harder to understand a language will be.  But what do I know?  I'm just a mathematician.

I admit I would be much less bothered by a dedicated predefined bottom that is a subtype of everything, than by adding such a subtyping rule for arbitrary empty types that *look* generative and *look* like a special case of ordinary variants.  In that case one could plausibly argue that "bottom is a subtype of everything" *is* a "general principle".

**Comment by DemiMarie** [comment] 2021-09-21 19:32
> I admit I would be much less bothered by a dedicated predefined bottom that is a subtype of everything, than by adding such a subtyping rule for arbitrary empty types that _look_ generative and _look_ like a special case of ordinary variants. In that case one could plausibly argue that "bottom is a subtype of everything" _is_ a "general principle".

Having arbitrary empty types be bottom is a bad idea IMO, but the same cannot be said for the (unique) empty polymorphic variant.

**Comment by DemiMarie** [comment] 2022-09-26 13:53
I still think the empty polymorphic variant should be a true bottom type.  It is already a subtype of all other polymorphic variants.

**Comment by garrigue** [comment] 2022-09-28 10:11
> I still think the empty polymorphic variant should be a true bottom type. It is already a subtype of all other polymorphic variants.

It is not, for the good reason that it is not a valid type.
If you allow the empty polymorphic variant as a valid inferred type, it becomes easy to unintentionally create functions that accept no input.

**Comment by DemiMarie** [comment] 2022-10-29 21:51
> I have seen the impact of this reasoning in large, complex codebases with weird uses of Obj.magic with comments explaining why they were "guaranteed to be safe", often to encode GADTs (before they were introduced in the language). Sure you can do this, but this amounts to trusting programmers to reason correctly about an advanced, complex and not-so-well-specified corner of the language. In my experience, sometimes this trust is justified, sometimes it isn't, and the few cases were it isn't can end up costing a lot of time and effort down the road (as in: fixing a segfault in a XML parsing library that used Obj.magic for reasons that sounded "guaranteed to be safe" to the people who wrote the code, and started segfaulting years after they stopped actively maintaining it.)

@yallop’s solution _is_ guaranteed to be safe, though.

```ocaml
   type empty = |
   let conv : empty ast -> 'any ast = 
     let module M : sig type +'a t end = struct type 'a t = 'a ast end in
     Obj.magic
```

is safe for *any* type `ast`: if `ast` is covariant, then the use of `Obj.magic` is safe, and if it is _not_ covariant, the code won’t compile.  The only way to break this is to come up with a value of type `empty`, but doing so is _already_ unsound.  I agree that asking individual users to write this is a bad idea, but a better solution would be to either provide a bottom type as a language feature or to provide @yallop’s solution as a standard library functor:

```ocaml
type empty = |
module type Covariant = sig type +'a t end
module type Safe_coerce = sig
   type +'a t
   type nonrec empty = empty
   external coerce: empty t -> 'a t = "%identity"
end
module Make(X: Covariant): Safe_coerce with type +'a t = 'a X.t = struct
   type +'a t = 'a X.t
   type nonrec empty = empty
   external coerce: empty t -> 'a t = "%identity"
end
```

This uses `%identity` internally, but its interface is perfectly safe, and that is what matters.  Since `Safe_coerce.coerce` is manifestly `%identity`, this should be zero-cost at runtime.

**Closed as completed** 2023-01-26 13:47 UTC
