### ISSUE TITLE
New (4.11) failure in Int64 code on 32 bit platforms

### ISSUE THREAD

**Issue by rwmjones** [ocaml/ocaml#9460] opened 2020-04-17 21:54 UTC
It's not the greatest code in the world, but ...

https://github.com/libguestfs/libnbd/blob/0475bfe04a527051c0a37af59a733c4c8554e427/ocaml/tests/test_400_pread.ml#L21-L36

... this code is supposed to create a `Bytes` containing this pattern of data: http://libguestfs.org/nbdkit-pattern-plugin.1.html#DESCRIPTION

It works in 4.10 (all architectures).  It also works on 4.11 (at commit 88a1bceb1b) on 64 bit architectures.

However on armv7 and i686 it appears to produce a complete zero buffer, and I have no idea why.

Note I'm also using the https://github.com/nojb/ocaml riscv patches on top, but I'm not sure if they could affect this.

**Comment by rwmjones** [comment] 2020-04-17 21:56
Because we're using a bit of a mongrel OCaml compiler here, this is the exact version we're using:

https://pagure.io/fedora-ocaml/commits/fedora-33-4.11.0-pre

**Comment by nojb** [comment] 2020-04-18 06:14
> Note I'm also using the https://github.com/nojb/ocaml riscv patches on top, but I'm not sure if they could affect this.

I confirm they should not have any effect on the reported issue.

**Comment by gasche** [comment] 2020-04-18 07:28
Could you turn this into a repro case that can be run without calling `ndbkit`, possibly using a simpler loop that also does not give the wrong result, or writing the test by comparison to the version using "4.08 endian functions" you mention? If you can have a self-contained test, I can add it to the testsuite and integrate it in the CI.

**Comment by yallop** [comment] 2020-04-18 07:31
This appears to have been introduced by #9316 (cc @stedolan)

**Comment by rwmjones** [comment] 2020-04-18 07:43
The comment relates to the fact that we want this package to be compilable with quite old OCaml (4.05 IIRC).  But a self-contained test might be something as simple as this (untested except on amd64):
```
let expected =
  let b = Bytes.create 16 in
  for i = 0 to 16/8-1 do
    let i64 = ref (Int64.of_int (i*8)) in
    for j = 0 to 7 do
      let c = Int64.shift_right_logical !i64 56 in
      let c = Int64.to_int c in
      let c = Char.chr c in
      Bytes.unsafe_set b (i*8+j) c;
      i64 := Int64.shift_left !i64 8
    done
  done;
  (Bytes.to_string b) ;;
Printf.printf "expected = %S%!\n" expected ;;
assert (expected = "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\008")
```

**Comment by xavierleroy** [comment] 2020-04-18 08:46
Looking at the C-- output, the mutable let-bound variable corresponding to `i64` in the source is given C-- type `int` even if we're on a 32-bit platform.  This is wrong, ~~since `int64` values are not unboxed on a 32-bit platform, so the type should be `val` in this case~~  since on a 32-bit platform `i64` is unboxed as a pair of 32-bit integers.

**Comment by gasche** [comment] 2020-04-18 08:56
Thanks @rwmjones. I added a regression test in #9462, which will be eventually merged as a regression test.
(I would recommend people writing a fix to start from this branch.)

**Comment by gasche** [comment] 2020-04-18 08:57
@rwmjones out of curiosity, why are you testing 4.11+dev right now? It is unusual (and clearly quite useful) that you would try OCaml versions that are not released or in beta yet.

**Comment by lthls** [comment] 2020-04-18 08:58
I have a fix for this, but it assumes that the only thing wrong is the cmm type of the unboxed `int64`.
If as @xavierleroy said this is not supposed to happen, then we need another fix.

**Comment by xavierleroy** [comment] 2020-04-18 09:08
@lthls my comment was incorrect, and I edited it.  It's OK to unbox `i64` on a 32-bit platform, but its type is not `int` in this case.

**Comment by rwmjones** [comment] 2020-04-18 09:09
Rawhide is a bit of a free-for-all and although we normally stick with released versions, in this case I want to get nojb's riscv64 port going again which hasn't worked (for us) since Fedora 31.  The easiest way to do that was to start with the proposed pull request.

**Comment by lthls** [comment] 2020-04-18 09:11
Ok, I'll rebase my fix on @gasche 's regression test PR and submit it.

**Closed as completed** 2020-04-20 09:34 UTC
Labels: bug, high-priority
