### ISSUE TITLE
Top-level printer crash with recursively-constrained type

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml#9873] opened 2020-09-03 07:51 UTC
This looks somewhat related to #9866 (cc @garrigue):

In 4.11.1:
```
# type 'a t = 'b constraint 'a = ('b * 'b) t ;;
Line 1, characters 0-42:
1 | type 'a t = 'b constraint 'a = ('b * 'b) t ;;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: In this definition, a type variable cannot be deduced
       from the type parameters.
```

In `trunk`:
```
# type 'a t = 'b constraint 'a = ('b * 'b) t ;;
type 'a t = 'b constraint 'a = ('b * 'b) t
# ([|Some 3L|], [|None|] :  _ t  );;
Segmentation fault
```

**Comment by garrigue** [comment] 2020-09-03 08:17
Unfortunately, #9870 does not fix that one. Pandora box ?

**Comment by garrigue** [comment] 2020-09-03 09:51
Fixed in #9870. The cause was a use of `Ctype.apply` which does not handle properly constrained parameters.
Maybe Ctype.apply itself should be removed in most cases.

**Comment by garrigue** [comment] 2020-09-03 09:53
Note that the bug was in the printer, not the type-checker, but the faulty function is exported from the type checker (it is very seldom used, hopefully on types without constraints).

**Comment by garrigue** [comment] 2020-09-03 11:47
Actually the problem is not in the printer; using #9870 we get:
```
# fun () -> (1,2 : _ t);;
- : unit -> (int * int) t t = <fun>
```
which is clearly wrong. I'm starting to get completely lost. Somehow the type checker seems to believe parameters are regular too... Now looking into how to get rid of those strange type definitions.

**Comment by Octachron** [comment] 2021-04-12 11:44
I am closing this issue as a duplicate of #9866 (which is still open for recursive module).

**Closed as completed by Octachron** 2021-04-12 11:44 UTC
