### ISSUE TITLE
OCaml (4.09) Test Failure

### ISSUE THREAD

**Issue by drikosev** [ocaml/ocaml#9240] opened 2020-01-10 17:49 UTC
Hello,

The OCaml tests have one failure on macOS 10.13 and I cannot run 
them during installation of the package (an automated procedure). 

The failed test is this:
   tests/output-complete-obj/'test.ml' with 1.2.1.1 [testing 'test.ml' with 1.2.1.1]

The Summary is this:
 2473 passed,
     33 skipped,
       1 failed,
     94 not started,
       0 unexpected errors,
 2601 considered.

Thanks in advance,
Ev. Drikos

**Comment by Octachron** [comment] 2020-01-13 10:07
There should be a log file in ` tests/_ocamltest/tests/output-complete-obj/test/test.log`. Could you link, or copy, its contents?  (The tests run fine on macOS 10.13 in our internal CI).

**Comment by drikosev** [comment] 2020-01-13 10:25
Hello,

Thank you for your response. If all tests pass on your system, the
problem should be on my installation or the tools I use. In any case
the contents of file "test.log" are below.


Regards,
Ev. Drikos

-----------------------------------------
These are the contents of file test.log:

Specified modules: test.ml
Source modules: test.ml
Running test libunix with 1 actions
Running action 1/1 (libunix)
Action 1/1 (libunix) passed (libunix available)
Running test setup-ocamlc.byte-build-env with 1 actions
Running action 1/1 (setup-ocamlc.byte-build-env)
Action 1/1 (setup-ocamlc.byte-build-env) passed
Running test ocamlc.byte with 1 actions
Running action 1/1 (ocamlc.byte)
Compiling program test.ml.bc.o from modules  test.ml
Commandline: /Users/suser/pc/ocaml/ocaml-4.09.0/runtime/ocamlrun /Users/suser/pc/ocaml/ocaml-4.09.0/ocamlc -use-runtime /Users/suser/pc/ocaml/ocaml-4.09.0/runtime/ocamlrun -I /Users/suser/pc/ocaml/ocaml-4.09.0/runtime -nostdlib -I /Users/suser/pc/ocaml/ocaml-4.09.0/stdlib -w a -output-complete-obj -o test.ml.bc.o test.ml
  Redirecting stdout to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlc.byte/ocamlc.byte.output 
  Redirecting stderr to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlc.byte/ocamlc.byte.output 
Action 1/1 (ocamlc.byte) passed
Running test script with 1 actions
Running action 1/1 (script)
Script should write its response to /var/folders/6s/vys1lxb13z54387yjnfgpsjr0000gn/T/ocamltest-0bfc86.response
Commandline: /usr/local/bin/gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -fno-builtin-memcmp -Wall -fno-tree-vrp -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE -Wl,-no_compact_unwind -I/Users/suser/pc/ocaml/ocaml-4.09.0/runtime -o test.ml_bc_stub.exe test.ml.bc.o -lm test.ml_stub.c
  Redirecting stdout to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlc.byte/ocamlc.byte.output 
  Redirecting stderr to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlc.byte/ocamlc.byte.output 
Action 1/1 (script) passed
Running test run with 1 actions
Running action 1/1 (run)
Commandline: ./test.ml_bc_stub.exe
  Redirecting stdout to program-output 
  Redirecting stderr to program-output 
Action 1/1 (run) passed
Running test setup-ocamlopt.byte-build-env with 1 actions
Running action 1/1 (setup-ocamlopt.byte-build-env)
Action 1/1 (setup-ocamlopt.byte-build-env) passed
Running test ocamlopt.byte with 1 actions
Running action 1/1 (ocamlopt.byte)
Compiling program test.ml.exe.o from modules  test.ml
Commandline: /Users/suser/pc/ocaml/ocaml-4.09.0/runtime/ocamlrun /Users/suser/pc/ocaml/ocaml-4.09.0/ocamlopt -I /Users/suser/pc/ocaml/ocaml-4.09.0/runtime -nostdlib -I /Users/suser/pc/ocaml/ocaml-4.09.0/stdlib -w a -output-complete-obj -o test.ml.exe.o test.ml
  Redirecting stdout to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlopt.byte/ocamlopt.byte.output 
  Redirecting stderr to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlopt.byte/ocamlopt.byte.output 
Action 1/1 (ocamlopt.byte) passed
Running test script with 1 actions
Running action 1/1 (script)
Script should write its response to /var/folders/6s/vys1lxb13z54387yjnfgpsjr0000gn/T/ocamltest-a2e194.response
Commandline: /usr/local/bin/gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -fno-builtin-memcmp -Wall -fno-tree-vrp -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE -Wl,-no_compact_unwind -I/Users/suser/pc/ocaml/ocaml-4.09.0/runtime -o test.ml_stub.exe test.ml.exe.o -lm -lpthread test.ml_stub.c
  Redirecting stdout to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlopt.byte/ocamlopt.byte.output 
  Redirecting stderr to /Users/suser/pc/ocaml/ocaml-4.09.0/testsuite/_ocamltest/tests/output-complete-obj/test/ocamlopt.byte/ocamlopt.byte.output 
Action 1/1 (script) failed ()

**Comment by Octachron** [comment] 2020-01-13 10:35
It seems that this is the call to gcc that is failing, you might get a better error message by calling the command yourself in `testsuite/_ocamltest/tests/output-complete-obj/test/ocamlopt.byte`

**Comment by drikosev** [comment] 2020-01-13 10:41
Here is the command I run along with the error message:

miniserver:ocamlopt.byte suser$ /usr/local/bin/gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -fno-builtin-memcmp -Wall -fno-tree-vrp -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE -Wl,-no_compact_unwind -I/Users/suser/pc/ocaml/ocaml-4.09.0/runtime -o test.ml_stub.exe test.ml.exe.o -lm -lpthread test.ml_stub.c
Undefined symbols for architecture x86_64:
  "_caml_system__code_end", referenced from:
      _segv_handler in test.ml.exe.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
miniserver:ocamlopt.byte suser$

**Comment by drikosev** [comment] 2020-01-13 22:24
Hello Mr Florian Angeletti,

Your response helped me to find a solution.

The tests pass if I compile OCaml with the default system compiler installed at /usr/bin.

Just for the record, the test fails when I compile OCaml with a GNU compiler installed 
either at /usr/local  (ie gcc-4.8.5) or at /opt/local (ie gcc-8.2). Whereas, on CentOS-7.6
where gcc-4.8.5 is the default system compiler the tests pass. 

Here is my page where I'd initially documented the problem, maybe not so useful:
https://github.com/drikosev/pc/commit/a4c937358c88659f599a88b0389adf1e6f042b1a 

Regards,
Ev. Drikos

**Comment by Octachron** [comment] 2020-01-15 08:13
If it works on clang and not gcc, it might be a problem of configuration.
cc @shindere .

**Comment by shindere** [comment] 2020-02-17 14:39
@drikosev: sorry for the inconvenience.

My guess is that `configure` gets confused, trying to use the specified
compiler (the one not installed at the standard place) and libraries
that are installed and thus take precedence over the ones that go with
the non-installed compiler and should thus be used with it.

The problem seems however hard to debug since we can not reproduce it
here, and perhaps a bit marginal, too.

I am thus closing this issue at the moment, but please feel very free to
reopen it if the problem becomes really annoying for your use case. If
yo do so, it would be helpful to proivde instructions to help us
reproduce the problem.

**Closed as completed** 2020-02-17 14:39 UTC
