### ISSUE TITLE
4.13.1 rejects this use of GADT

### ISSUE THREAD

**Issue by Ngoguey42** [ocaml/ocaml#10984] opened 2022-02-02 18:16 UTC
With `main.ml` containing:
```ml
type _ layout = A : int layout | B : string layout

let create : type a. a layout -> a = function A -> 42 | B -> "42"

let iter : type a. a layout -> unit =
 fun la ->
  let _ = match la with A -> create la | B -> "" in
  ()
```

running `ocamlc -i main.ml` on OCaml 4.11.1 gives:
```ml
type _ layout = A : int layout | B : string layout
val create : 'a layout -> 'a
val iter : 'a layout -> unit
```

while running `ocamlc -i main.ml` on OCaml 4.13.1 gives:
```
File "main.ml", line 7, characters 46-48:
7 |   let _ = match la with A -> create la | B -> "" in
                                                  ^^
Error: This expression has type a but an expression was expected of type a
       This instance of a is ambiguous:
       it would escape the scope of its equation
```

**Comment by Ngoguey42** [comment] 2022-02-02 18:21
It occurred in Irmin. This simple change fixed the problem: https://github.com/mirage/irmin/compare/35c4e31fc453fb9f5ab2e7dd454213f5f12d319b..798579e9374d53c8786b9ad6203f774a94f5ecd0

**Comment by gasche** [comment] 2022-02-02 20:37
We know that the behavior of GADT pattern-matching changed in 4.12 and 4.13, sometimes requiring more annotations than before (because some principality guarantee that the designers expect were not in fact met by the previous implementation, which accepted non-principal programs when it should not.) It's very hard for non-experts like me to tell whether a given inference change on a program is a bug or not, but most of them are not, simply "fixes" which affect some users. I would recommend just using an annotation in any case of trouble; in your example, `let _ : <annot> = ...` should suffice.

**Comment by garrigue** [comment] 2022-02-03 01:00
More specifically, there is actually no guarantee whatsoever that a program that uses GADTs will be typable in a future version of ocaml if it is not typable with the `-principal` option, as the algorithm lacks principality in its handling of GADTs, and minor changes can break the typing of some programs.
It appears that this program causes already a typing error in 4.12 when compiled with the `-principal` option, so this is not strictly speaking a regression.

**Comment by gasche** [comment] 2022-02-03 01:16
Indeed, 4.12 or earlier (4.11, etc.) reject the proposed program when `-principal` is used. For this reason, we are confident that it is not a bug, so I'm closing this issue.

**Closed as completed by gasche** 2022-02-03 01:16 UTC
