### ISSUE TITLE
compression of cmi files

### ISSUE THREAD

**Issue by JuliaLawall** [ocaml/ocaml#13330] opened 2024-07-24 08:14 UTC
Since 5.1.0, cmi files have been compressed.  How can they be uncompressed, or how can information otherwise be retrieved from them?

**Comment by nojb** [comment] 2024-07-24 08:24
You can disable compression by passing `--without-zstd` to the `configure` script. For reading information from them, other devs will correct me if I'm wrong, but I think compression is transparently handled by `Marshal`, so nothing special needs to be done.

**Comment by Octachron** [comment] 2024-07-24 08:26
Indeed nothing changed from the user side, one can use either ocamlobjinfo of the `Cmi_format` module from compiler-libs to read compressed cmi.

Compression is handled not by Marshall but by the `Compression` module of compiler-libs (which install compression/decompression functions in the corresponding hooks in `extern.c`.

**Comment by xavierleroy** [comment] 2024-07-26 15:31
I suggest using function `Cmi_format.read_cmi` from compiler-libs to read a .cmi file.  It will take care of compression transparently, and is compatible with older versions of OCaml.

**Comment by Octachron** [comment] 2024-07-26 15:36
I am closing the issue in the absence of reactions from @JuliaLawall .

**Closed as completed by Octachron** 2024-07-26 15:36 UTC
Labels: feature-wish

**Comment by JuliaLawall** [comment] 2024-07-26 16:03
I actually responded to all of the above emails, but it seems that responding by email is not supported here?

Anyway, it's not clear to me how to be able to use cmi_format.  Where should I find it?  Is there any specific compiler command line needed to use it?

I tried ocamlobjinfo, but that only reported on the exported modules and I wanted the imported ones.

**Comment by shindere** [comment] 2024-07-26 16:08
JuliaLawall (2024/07/26 09:03 -0700):
> I actually responded to all of the above emails, but it seems that
> responding by email is not supported here?

It's definitely supported (I'm currently usingthis feature to respond to
your message)

Have you checked that the email address you used to respond is one of
those that are boudn to your GitHub account?

> Anyway, it's not clear to me how to be able to use cmi_format.  Where
> should I find it?  Is there any specific compiler command line needed
> to use it?

I think it's part of compilerlibs that gets installed with the compiler.

The way to use it will depend on the build system you are using...

**Comment by xavierleroy** [comment] 2024-07-26 16:16
>  Is there any specific compiler command line needed to use it?

`ocamlopt -I +compiler-libs ocamlcommon.cmxa` should do the job.  Or whichever Dune equivalent.

**Comment by JuliaLawall** [comment] 2024-07-26 16:21
Thanks, @xavierleroy.  That works fine.

I also responded by email to Sebastien, to ocaml/ocaml <reply+AAD2ZGV5RRVJD6OL56DGE4OEV6VSHEVBNHHJBJ3GWE@reply.github.com>, but it didn't show up here either...

**Comment by glondu** [comment] 2024-07-27 03:47
> I tried ocamlobjinfo, but that only reported on the exported modules and I wanted the imported ones.

@JuliaLawall, could you tell us more about this? With 5.2.0, I see the imported ones.

**Comment by JuliaLawall** [comment] 2024-07-27 06:15
My mistake, @glondu it's the other way around.  ocamlobjinfo is giving the imported modules, but I want the ones that are defined by the mli file.
[coccilib.cmi.gz](https://github.com/user-attachments/files/16398450/coccilib.cmi.gz)
I attached the cmi file.  I would like Iteration to be included in the output.

**Comment by glondu** [comment] 2024-07-27 07:17
> I want the ones that are defined by the mli file

I observe no changes that were caused by the compression of cmi files here. The module defined by the cmi file is available in "Unit name". If you want details about (sub-)modules defined inside the module, then indeed you'll have to use compiler-libs.

**Comment by JuliaLawall** [comment] 2024-07-27 08:59
Thanks for the feedback.

**Comment by Octachron** [comment] 2024-07-27 10:11
There is also `cmitomli` available on opam which can print the signature contained inside a cmi.

**Comment by JuliaLawall** [comment] 2024-07-31 08:57
I get Error: Unbound module Cmi_format on OCaml 3.12, but not on eg OCaml 4.09.  Did something change in the meantime?  How could I have found this out by myself?

Thanks.

**Comment by nojb** [comment] 2024-07-31 09:12
> I get Error: Unbound module Cmi_format on OCaml 3.12, but not on eg OCaml 4.09. Did something change in the meantime? 

Many things changed between the 3.12 and 4.09 releases :) `Cmi_format` was introduced in 4.01 at the same time as `-bin-annot` (see c3b08c91496360d974973cea5cf809b1d8b8e83d).

> How could I have found this out by myself?

Perusing the Git log is one way.

**Comment by JuliaLawall** [comment] 2024-07-31 09:20
Thanks.  I was trying to look at the documentation: https://ocaml.org/p/ocaml-base-compiler/4.07.1/doc/Cmi_format/index.html but if I select 3.12.0 I get a 404 error: https://ocaml.org/p/ocaml-base-compiler/3.12.0/doc/Cmi_format/index.html  It wasn't clear what to do next to see if it just didn't exist or was available in some other way.  For other modules, I have a man page, like man Str, and that often indicates when things were introduced, but I don't have such a man page for Cmi_format.

**Comment by shindere** [comment] 2024-08-19 09:07
JuliaLawall (2024/07/31 02:21 -0700):
> For other modules, I have a man page,
> like man Str, and that often indicates when things were introduced,
> but I don't have such a man page for Cmi_format.

Likely because `Cmi_format` is part of compilerlibs, for which, Ithink,
we do not provide manual pages.
