### ISSUE TITLE
Fix regression with `-o` when compiling C files

### ISSUE THREAD

**Issue by nojb** [ocaml/ocaml#10610] opened 2021-09-06 15:05 UTC
*A friendly reminder that we shouldn't forget about this regression introduced in #9960 that needs to be fixed before 4.13 is released.*

There are two issues with this patch:

1. It broke previous behaviour of `ocaml` when you *don't* pass `-o`:
```
(before) ocamlc foo.c --> calls "$cc -c foo.c"
(after) ocamlc foo.c --> calls "$cc -o foo.o -c foo.c"
```
This causes problems when people use:
```
ocamlc -ccopt '-o whatever' foo.c
```
which was necessary before this PR.

2. The `-o` flag to `ocaml{c,opt}` is ignored if `-c` is not passed as well when compiling C files.

_Originally posted by @nojb in https://github.com/ocaml/ocaml/issues/9960#issuecomment-889663598_

cc @shindere

**Comment by shindere** [comment] 2021-09-06 15:18
I didn't forget, thanks!

**Comment by shindere** [comment] 2021-09-08 10:56
I checked that #10619 does fix the reported problems.

May main concern is tomake sure it does not introduce others.

I made a mistake in the PR title, writing #9660 rather than #9960. Would
somebody please be kind enough and fix that?

**Comment by nojb** [comment] 2021-09-08 10:58
> Would somebody please be kind enough and fix that?

Fixed.

**Comment by Octachron** [comment] 2021-09-08 12:51
@nojb concerning your second point, as far as I can see, this behavior has been constant since at least OCaml 4.04? In particular,
```bash
ocamlopt -o exe a.c b.ml
```
generates an executable named `exe`.

**Comment by nojb** [comment] 2021-09-08 13:10
> @nojb concerning your second point, as far as I can see, this behavior has been constant since at least OCaml 4.04? In particular,

Indeed, that seems to be the case...

**Comment by shindere** [comment] 2021-09-08 13:56
Nicolás Ojeda Bär (2021/09/08 06:10 -0700):
> > @nojb concerning your second point, as far as I can see, this behavior has been constant since at least OCaml 4.04? In particular,
>
> Indeed, that seems to be the case...

How about just

```
ocamlc -o hello hello.c
```

In my tests this was generating an object file, not an executable. And
my understanding was that my patch in #9960 did change this, and htat I
needed to fix that, too.

Taht's why I added the "else" part. But I forgot to re-run the testsuite
after that. Before I added the "else" part, with just the other part of
hte patch, the testsuite was happy.

**Comment by Octachron** [comment] 2021-09-08 14:01
The issue is that without `-c` the object file is not the final target of the compilation command, and thus
```bash
ocamlc -o anything hello.c
``` 
generates `hello.o` since at least OCaml 4.00.

**Comment by shindere** [comment] 2021-09-08 14:06
Everything seems clear to me now, thanks.

I pushed a version of the code that does not try to fix a problem that
does actually not exist, many thanks to you, @Octachron, for having
spotted that.

**Comment by gasche** [comment] 2021-09-08 14:37
Would it be possible to have tests in the testsuite for the behaviors that we have decided to preserve?

**Comment by Octachron** [comment] 2021-09-09 09:35
It does not seem trivial to add test for the C compilation command, but it might it be a good idea on the medium term.

Since #10619 fixed the regression with out-of-thin-air `-o ` flag, I am closing this specific issue. @nojb , do you think that the not obvious behavior with `ocamlc -o anything hello.c` warrants an issue?

**Closed as completed by Octachron** 2021-09-09 09:35 UTC

**Comment by nojb** [comment] 2021-09-09 15:39
> @nojb , do you think that the not obvious behavior with `ocamlc -o anything hello.c` warrants an issue?

Done! https://github.com/ocaml/ocaml/issues/10625
