### ISSUE TITLE
[@inline never] attribute may be ignored

### ISSUE THREAD

**Issue by markghayden** [ocaml/ocaml#10993] opened 2022-02-06 01:13 UTC
It seems functions marked as [@inline never] may be still be inlined in Ocaml 4.13.0.

The particular pattern where we noticed this was when you have ML code with a small "add" function that calls a "grow" function if no space is available.  Being small, "add" may benefit from inlining.  "grow" may be large and the uncommon case, so it may be best not to inline it.  "grow" is an internal function and is not exported from the module.

Even if marked [@inline never], the "grow" function appears to be inlined to the "add" function (overriding the attribute).  This makes some since because un-exported, single-use functions should normally benefit from inlining.  However, when "add" is inlined, "grow" is carried along and also inlined, which may be undesirable.

A work-around appears to be to export "grow" from the module interface, which seems to prevent it from being inlined.

A test case is attached.  A non-operational bucket.ml class and caller in test.ml.  When "grow" is not in the bucket.mli, it gets inlined into the call-site for "add".  When "grow" is in the bucket.mli, the "add" function is inlined but "grow" is not (the desired behavior).  Of course, you should not have to break the abstraction to achieve this.  You can examine the included test.s to see that the inlining of "grow" occurs at the "add" call-site in test.ml.

bucket.mli:

`type 'a t ;;

val add: 'a t -> 'a -> unit ;;

(* If this is uncommented the grow will not be included in the add function.
 *)
(*val grow: 'a t -> 'a -> unit ;;*)
`

bucket.ml:

`type 'a t = {
  mutable arr: 'a array ;
  mutable len: int ;
} ;;

(* We do not want this inlined.
 *)
let [@inline never] grow s v =
  let len0 = Array.length s.arr in
  let len1 = len0 lsl 1 in
  let arr1 = Array.make len1 v in
  Array.blit s.arr 0 arr1 0 s.len ;
  s.len <- len1 ;
  s.arr <- arr1 ;
;;

(* We want this inlined.
 *)
let [@inline] add s item =
  if s.len >= Array.length s.arr then
    grow s item ;
  s.arr.(s.len) <- item ;
  s.len <- succ s.len
;;`

[noinline.zip](https://github.com/ocaml/ocaml/files/8009210/noinline.zip)

**Comment by lpw25** [comment] 2022-02-06 07:32
This is an instance of the "local functions" optimisation rather than the usual inlining optimisation. It can be prevented by annotating `grow` with `[@local never]`. For this reason, at Jane Street we have [ppx_cold](https://github.com/janestreet/ppx_cold), which just interprets `[@cold]` as `[@inline never][@local never][@specialise never]`.

I've been meaning to add `[@cold]` to the compiler itself, but haven't got around to it. I think there is value in having both it and the various `never`s -- sometimes you want to precisely control a particular optimisation whilst sometimes you want to specify a semantic property and have the compiler do the best thing based on that.

**Comment by markghayden** [comment] 2022-02-06 12:06
Thanks for the explanation.  [@cold] would be a nice addition.  However, I think a lot of people would expect [@inline never] should be sufficient to prevent inlining since the 'never' seems definitive.  If the current behavior won't be changed, maybe it could be renamed?

**Comment by gasche** [comment] 2022-02-06 13:15
We discussed this at some length in #8563, which is basically a duplicate of the present issue, and also in the original PR that implemented the local-function optimization: https://github.com/ocaml/ocaml/pull/2143#issuecomment-438214943. I'm not saying a new discussion isn't useful (we gain some extra information that other users at hit by this issue), but we could start by re-reading those.

Question: why is `add` marked `[@inline]` in the first place? Doesn't the inliner do the right thing without the explicit annotation?

**Comment by lpw25** [comment] 2022-02-06 14:41
FWIW I'm actually surprised that the local functions optimisation applies here, where the function (i.e.`grow`) is being called inside a nested non-local function (i.e.`add`) rather than just from a call site within its enclosing function (the module entry function). I've previously argued that `[@inline never]` should disable duplicating code, as that is a reasonable definition of inlining. I think this behaviour could be considered an instance of that and reasonably be prevented by `[@inline never]`, unlike other applications of the "local functions" optimisation which do not cause the code to be duplicated.

**Comment by markghayden** [comment] 2022-02-06 15:01
Thanks for pointing out #8563.  I agree it is a duplicate or very similar.  I searched for similar reports but hadn't found this one.  The suggestion there that [@inline never] should imply [@local never] could make sense.

The 'add' is marked 'inline' because it is isn't inlined otherwise, at least with '-O3'.  Maybe a large -inline value would trigger that.

I agree with lpw25 that '[@inline never]' should not result in the function body being duplicated.  Or if it is duplicated, only in ways that are guaranteed to not cause code size to significantly increase; maybe the compiler can simplify a call to the point that inlining makes sense.  I think this is a reasonable expectation.

**Comment by lthls** [comment] 2023-02-08 08:46
Thanks to the bot for the reminder that nobody has reviewed #11383 yet.

**Comment by Octachron** [comment] 2023-10-18 13:55
Closing as #11383 was merged.

**Closed as completed by Octachron** 2023-10-18 13:55 UTC
