### ISSUE TITLE
More precise error message when large functions and/or modules types cannot be unified

### ISSUE THREAD

**Issue by vicuna** [ocaml/ocaml#7860] opened 2018-10-07 11:33 UTC
**Original bug ID:** 7860
**Reporter:** @samoht
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** typing
**Monitored by:** @nojb

## Bug description

It would be nice if the compiler would be able to "zoom" in the diff between two complex structures (modules/functions) which cannot unify.

For instance, I've just got the following error on 4.07.1:

```
File "src/irmin-mirage/irmin_mirage.ml", line 1:
Error: The implementation src/irmin-mirage/irmin_mirage.ml
       does not match the interface src/irmin-mirage/.irmin_mirage.objs/irmin_mirage.cmi:
       ...
       At position module Git : sig module KV_RW(G)(C) : <here> end
       Values do not match:
         val connect :
           ?depth:int ->
           ?branch:value ->
           ?root:key ->
           ?conduit:Conduit_mirage.t ->
           ?resolver:Resolver_lwt.t ->
           ?headers:Cohttp.Header.t -> author:value -> git -> value -> t io
       is not included in
         val connect :
           ?depth:int ->
           ?branch:value ->
           ?root:key ->
           ?conduit:Conduit_mirage.t ->
           ?resolver:Resolver_lwt.t ->
           ?headers:Cohttp.Header.t -> author:value -> G.t -> value -> t io
       File "src/irmin-mirage/irmin_mirage.mli", line 106, characters 4-230:
         Expected declaration
       File "src/irmin-mirage/irmin_mirage.ml", line 219, characters 4-230:
         Actual declaration
```

The actual issue is that `G.t` and `git` cannot unify and it would be nice if the compiler could tell me that directly (and maybe point to the definition of these types).

**Comment by yawaramin** [comment] 2019-04-18 03:52
This seems to be a duplicate of #7574

**Comment by yallop** [comment] 2019-04-18 07:19
Indeed -- thanks, @yawaramin.

**Closed as completed by yallop** 2019-04-18 07:19 UTC
Labels: typing
