### ISSUE TITLE
4.11.1: underlinking build issue

### ISSUE THREAD

**Issue by kloczek** [ocaml/ocaml#10222] opened 2021-02-14 08:43 UTC
When ocaml is build with `-Wl,-z,defs` in LDFLAGS it fails in linking of `libcamlrun_shared.so`
```
make: *** No targets specified and no makefile found.  Stop.
[tkloczko@barrel redhat-rpm-config-180-]$ [tkloczko@barrel ocaml-4.11.1]$ make -k
make coldstart
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.1'
make -C runtime  all
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.1/runtime'
/usr/bin/gcc -shared -o libcamlrun_shared.so interp_bpic.o misc_bpic.o stacks_bpic.o fix_code_bpic.o startup_aux_bpic.o startup_byt_bpic.o freelist_bpic.o major_gc_bpic.o minor_gc_bpic.o memory_bpic.o alloc_bpic.o roots_byt_bpic.o globroots_bpic.o fail_byt_bpic.o signals_bpic.o signals_byt_bpic.o printexc_bpic.o backtrace_byt_bpic.o backtrace_bpic.o compare_bpic.o ints_bpic.o eventlog_bpic.o floats_bpic.o str_bpic.o array_bpic.o io_bpic.o extern_bpic.o intern_bpic.o hash_bpic.o sys_bpic.o meta_bpic.o parsing_bpic.o gc_ctrl_bpic.o md5_bpic.o obj_bpic.o lexing_bpic.o callback_bpic.o debugger_bpic.o weak_bpic.o compact_bpic.o finalise_bpic.o custom_bpic.o dynlink_bpic.o spacetime_byt_bpic.o afl_bpic.o unix_bpic.o bigarray_bpic.o main_bpic.o memprof_bpic.o domain_bpic.o skiplist_bpic.o codefrag_bpic.o -Wl,--as-needed -Wl,-z,defs -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -lm -ldl  -lpthread
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/ccqvBoBZ.lto.o: in function `caml_build_primitive_table_builtin':
<artificial>:(.text+0xebdf): undefined reference to `caml_builtin_cprim'
/usr/bin/ld: /tmp/ccqvBoBZ.lto.o: in function `caml_build_primitive_table':
<artificial>:(.text+0x1e309): undefined reference to `caml_names_of_builtin_cprim'
/usr/bin/ld: <artificial>:(.text+0x1e343): undefined reference to `caml_builtin_cprim'
/usr/bin/ld: /tmp/ccqvBoBZ.lto.o: in function `caml_main':
<artificial>:(.text+0x23ef3): undefined reference to `caml_names_of_builtin_cprim'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:298: libcamlrun_shared.so] Error 1
make[2]: Target 'all' not remade because of errors.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.1/runtime'
make[1]: *** [Makefile:151: coldstart] Error 2
```
When  the same is done without -Wl,-z,defs` everything is OK.
```
[tkloczko@barrel ocaml-4.11.1]$ cd runtime/
{tkloczko@barrel runtime]$ /usr/bin/gcc -shared -o libcamlrun_shared.so interp_bpic.o misc_bpic.o stacks_bpic.o fix_code_bpic.o startup_aux_bpic.o startup_byt_bpic.o freelist_bpic.o major_gc_bpic.o minor_gc_bpic.o memory_bpic.o alloc_bpic.o roots_byt_bpic.o globroots_bpic.o fail_byt_bpic.o signals_bpic.o signals_byt_bpic.o printexc_bpic.o backtrace_byt_bpic.o backtrace_bpic.o compare_bpic.o ints_bpic.o eventlog_bpic.o floats_bpic.o str_bpic.o array_bpic.o io_bpic.o extern_bpic.o intern_bpic.o hash_bpic.o sys_bpic.o meta_bpic.o parsing_bpic.o gc_ctrl_bpic.o md5_bpic.o obj_bpic.o lexing_bpic.o callback_bpic.o debugger_bpic.o weak_bpic.o compact_bpic.o finalise_bpic.o custom_bpic.o dynlink_bpic.o spacetime_byt_bpic.o afl_bpic.o unix_bpic.o bigarray_bpic.o main_bpic.o memprof_bpic.o domain_bpic.o skiplist_bpic.o codefrag_bpic.o -Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -lm -ldl  -lpthread
[tkloczko@barrel runtime]$
```

**Comment by dra27** [comment] 2021-02-14 13:26
Is this a 4.11.1-specific problem for you? This should happen with any version of OCaml.

If linking with a bytecode runtime, you need to provide `caml_names_of_builtin_cprim` and `caml_builtin_cprim` (the precompiled `ocamlrun`, etc. all link `prims.o` - custom runtimes in the bytecode compiler generate the symbol table. What is it you're trying to do?

**Comment by kloczek** [comment] 2021-02-14 14:33
I'm only pointing on incosistency in ABI. Only this and nothing more.

**Comment by xavierleroy** [comment] 2021-02-19 14:21
The 'libcamlrun` library is a bit unusual in that it refers to a table of functions that should be defined by the main program it is linked with.  In static linking scenarios, it's quite natural, but less so with dynamic linking, indeed.

I don't know if anyone is using `libcamlrun_shared.so`.  Executables produced by `ocamlc -custom` use the static library `libcamlrun.a` by default.   It looks like `libcamlrun_shared.so` is being built only for consistency with `libasmrun_shared.so`.

At any rate, the observed behavior is by design, not by mistake, so I'll close this issue.

**Closed as completed by xavierleroy** 2021-02-19 14:21 UTC
