### ISSUE TITLE
fail to build 4.07.1+musl+static+flambda

### ISSUE THREAD

**Issue by aryx** [ocaml/ocaml#9131] opened 2019-11-20 20:14 UTC
Here is the trace:
<pre>opam switch create 4.07.1+musl+static+flambda

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Gathering sources</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
[<font color="#4E9A06">ocaml-variants.4.07.1+musl+static+flambda</font>] found in cache

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Processing actions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#4E9A06">∗</font> installed <b>base-bigarray</b>.base
<font color="#4E9A06">∗</font> installed <b>base-threads</b>.base
<font color="#4E9A06">∗</font> installed <b>base-unix</b>.base
<font color="#CC0000">[ERROR]</font> The compilation of ocaml-variants failed at &quot;/home/pad/.opam/opam-init/hooks/sandbox.sh build make -j7 world&quot;.

<font color="#CC0000">#===</font> <b>ERROR</b> <b>while compiling ocaml-variants.4.07.1+musl+static+flambda</b> <font color="#CC0000">==========#</font>
<font color="#C4A000">#</font> <font color="#C4A000">context</font>     2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#b0cb7bc2
<font color="#C4A000">#</font> <font color="#C4A000">path</font>        ~/.opam/4.07.1+musl+static+flambda/.opam-switch/build/ocaml-variants.4.07.1+musl+static+flambda
<font color="#C4A000">#</font> <font color="#C4A000">command</font>     ~/.opam/opam-init/hooks/sandbox.sh build make -j7 world
<font color="#C4A000">#</font> <font color="#C4A000">exit-code</font>   2
<font color="#C4A000">#</font> <font color="#C4A000">env-file</font>    ~/.opam/log/ocaml-variants-12980-6d07ae.env
<font color="#C4A000">#</font> <font color="#C4A000">output-file</font> ~/.opam/log/ocaml-variants-12980-6d07ae.out
<font color="#C4A000">### output ###</font>
<font color="#C4A000"># </font>[...]
<font color="#C4A000"># </font>/usr/bin/ld: spacetime.pic.o: relocation R_X86_64_32 against `.rodata.str1.8&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: afl.pic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: unix.pic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: bigarray.pic.o: relocation R_X86_64_32S against `.rodata&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: final link failed: Nonrepresentable section on output
<font color="#C4A000"># </font>collect2: error: ld returned 1 exit status
<font color="#C4A000"># </font>Makefile:208: recipe for target &apos;libcamlrun_shared.so&apos; failed
<font color="#C4A000"># </font>make[1]: *** [libcamlrun_shared.so] Error 1
<font color="#C4A000"># </font>make[1]: *** Waiting for unfinished jobs....
<font color="#C4A000"># </font>make[1]: Leaving directory &apos;/home/pad/.opam/4.07.1+musl+static+flambda/.opam-switch/build/ocaml-variants.4.07.1+musl+static+flambda/byterun&apos;
<font color="#C4A000"># </font>Makefile:389: recipe for target &apos;coldstart&apos; failed
<font color="#C4A000"># </font>make: *** [coldstart] Error 2

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Error report</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">┌─ </font>The following actions <font color="#CC0000">failed</font>
<font color="#CC0000">│ </font><font color="#06989A">λ</font> build <b>ocaml-variants</b> 4.07.1+musl+static+flambda
<font color="#CC0000">└─ </font>
<font color="#06989A">┌─ </font>The following changes have been performed (the rest was aborted)
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-bigarray</b> base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-threads</b>  base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-unix</b>     base
<font color="#06989A">└─ </font>

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>ocaml-variants.4.07.1+musl+static+flambda troubleshooting</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">=&gt; </font>A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
# Run <b>eval $(opam env)</b> to update the current shell environment
Switch initialisation failed: clean up? (&apos;n&apos; will leave the switch partially installed) [Y/n] Y
<font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~</b></font>$ opam switch create 4.07.1+musl+static+flambda
</pre>

**Comment by gasche** [comment] 2019-11-20 20:29
(It would be useful to check that the problem still exists with a more recent OCaml version, for example 4.09 or trunk.)

**Comment by aryx** [comment] 2019-11-20 20:54
same with 4.09:
<pre><font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~</b></font>$ opam switch create 4.09.0+musl+static+flambda

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Gathering sources</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
[<font color="#4E9A06">ocaml-variants.4.09.0+musl+static+flambda</font>] found in cache

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Processing actions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#4E9A06">∗</font> installed <b>base-bigarray</b>.base
<font color="#4E9A06">∗</font> installed <b>base-threads</b>.base
<font color="#4E9A06">∗</font> installed <b>base-unix</b>.base
<font color="#CC0000">[ERROR]</font> The compilation of ocaml-variants failed at &quot;/home/pad/.opam/opam-init/hooks/sandbox.sh build make -j7 world&quot;.

<font color="#CC0000">#===</font> <b>ERROR</b> <b>while compiling ocaml-variants.4.09.0+musl+static+flambda</b> <font color="#CC0000">==========#</font>
<font color="#C4A000">#</font> <font color="#C4A000">context</font>     2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#b0cb7bc2
<font color="#C4A000">#</font> <font color="#C4A000">path</font>        ~/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda
<font color="#C4A000">#</font> <font color="#C4A000">command</font>     ~/.opam/opam-init/hooks/sandbox.sh build make -j7 world
<font color="#C4A000">#</font> <font color="#C4A000">exit-code</font>   2
<font color="#C4A000">#</font> <font color="#C4A000">env-file</font>    ~/.opam/log/ocaml-variants-16272-6d07ae.env
<font color="#C4A000">#</font> <font color="#C4A000">output-file</font> ~/.opam/log/ocaml-variants-16272-6d07ae.out
<font color="#C4A000">### output ###</font>
<font color="#C4A000"># </font>[...]
<font color="#C4A000"># </font>/usr/bin/ld: spacetime_byt_bpic.o: relocation R_X86_64_32 against `.rodata.str1.8&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: afl_bpic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: unix_bpic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: bigarray_bpic.o: relocation R_X86_64_32S against `.rodata&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: final link failed: Nonrepresentable section on output
<font color="#C4A000"># </font>collect2: error: ld returned 1 exit status
<font color="#C4A000"># </font>Makefile:297: recipe for target &apos;libcamlrun_shared.so&apos; failed
<font color="#C4A000"># </font>make[1]: *** [libcamlrun_shared.so] Error 1
<font color="#C4A000"># </font>make[1]: *** Waiting for unfinished jobs....
<font color="#C4A000"># </font>make[1]: Leaving directory &apos;/home/pad/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda/runtime&apos;
<font color="#C4A000"># </font>Makefile:345: recipe for target &apos;coldstart&apos; failed
<font color="#C4A000"># </font>make: *** [coldstart] Error 2



<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Error report</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">┌─ </font>The following actions <font color="#CC0000">failed</font>
<font color="#CC0000">│ </font><font color="#06989A">λ</font> build <b>ocaml-variants</b> 4.09.0+musl+static+flambda
<font color="#CC0000">└─ </font>
<font color="#06989A">┌─ </font>The following changes have been performed (the rest was aborted)
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-bigarray</b> base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-threads</b>  base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-unix</b>     base
<font color="#06989A">└─ </font>

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>ocaml-variants.4.09.0+musl+static+flambda troubleshooting</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">=&gt; </font>A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    <b>musl-tools</b>

# Run <b>eval $(opam env)</b> to update the current shell environment
Switch initialisation failed: clean up? (&apos;n&apos; will leave the switch partially installed) [Y/n] Y
</pre>

**Comment by aryx** [comment] 2019-11-20 20:55
and I have musl-tools installed (musl-gcc test.c -static  does work)

**Comment by aryx** [comment] 2019-11-20 21:05
I'm under Ubuntu 18.04 LTS

**Comment by Romendakil** [comment] 2019-11-26 11:59
This looks very much like a problem with mixing up 32bit and 64bit libraries.

**Comment by Octachron** [comment] 2019-12-09 14:55
I can reproduce the issue on Ubuntu 18.04 but not 19.10 . cc @shindere .

**Comment by XVilka** [comment] 2019-12-11 11:59
Same problem with Alpine Linux 3.10 and OCaml 4.09:

Using Alpine Linux based container I get this error compiling static ocaml 4.09:
The docker part:
```Dockerfile
FROM alpine:3.10 AS builder
# Install the build dependencies
RUN apk add --no-cache make m4 which patch sudo wget git pkgconfig \
  gcc g++ musl-dev linux-headers libffi libffi-dev pcre perl python3 \
  gmp-dev libressl-dev lzo-dev pcre-dev zlib-dev xz-dev \
  ocaml ocaml-compiler-libs ocaml-ocamldoc opam ocaml-findlib \
  coreutils

RUN opam init --auto-setup --disable-sandboxing --yes && eval `opam env` && \
  opam install --yes  ocamlfind && \
  opam update --yes && export CHECK_IF_PREINSTALLED=false; \
  opam install --yes opam-devel

RUN eval `opam env` && \
  opam switch create 4.09.0+musl+static+flambda && \
  opam switch 4.09.0+musl+static+flambda
```
Note, that exactly the same setup with with a plain 4.09.0 works fine, it is only `musl+static+flambda` fails:
```
STEP 15: RUN eval `opam env` &&         opam switch create 4.09.0+musl+static+flambda &&        opam switch 4.09.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-variants.4.09.0+musl+static+flambda] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at
        "/home/user/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda/./configure
        --prefix=/home/user/.opam/4.09.0+musl+static+flambda CC=musl-gcc
        -Os ASPP=musl-gcc -c --enable-flambda LIBS=-static".

#=== ERROR while compiling ocaml-variants.4.09.0+musl+static+flambda ==========#
# context              2.0.3 | linux/x86_64 |  | https://opam.ocaml.org#0c517cc7
# path                 ~/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda
# command              ~/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda/./configure --prefix=/home/user/.opam/4.09.0+musl+static+flambda CC=musl-gcc -Os ASPP=musl-gcc -c --enable-flambda LIBS=-static
# exit-code            77
# env-file             ~/.opam/log/ocaml-variants-3-a71bb4.env
# output-file          ~/.opam/log/ocaml-variants-3-a71bb4.out
### output ###
# configure: Configuring OCaml version 4.09.0
# checking build system type... x86_64-pc-linux-gnu
# checking host system type... x86_64-pc-linux-gnu
# checking target system type... x86_64-pc-linux-gnu
# checking for ld... ld
# checking how to print strings... printf
# checking for gcc... musl-gcc -Os
# checking whether the C compiler works... no
# configure: error: in `/home/user/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda':
# configure: error: C compiler cannot create executables
# See `config.log' for more details



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-variants 4.09.0+musl+static+flambda
+- 
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
+- 

<><> ocaml-variants.4.09.0+musl+static+flambda troubleshooting ><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially

**Comment by shindere** [comment] 2019-12-13 10:20
Hello,

Anton Kochkov (2019/12/11 03:59 -0800):
> [ERROR] The compilation of ocaml-variants failed at
>         "/home/user/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda/./configure
>         --prefix=/home/user/.opam/4.09.0+musl+static+flambda CC=musl-gcc
>         -Os ASPP=musl-gcc -c --enable-flambda LIBS=-static".

I am wondering whether the arguments to CC and ASPP shouldn't be quoted?

They do not seem to be in the command so perhaps the variables receive
only the first word and the other words are interpreted as options to
configure?

**Comment by XVilka** [comment] 2019-12-26 05:07
@shindere I think yes, otherwise it splits it.

**Comment by shindere** [comment] 2020-02-17 15:28
Would it be possible to show the output of the `config.log` file to try
to understand why the C compiler is detected as not working at such an
early configure stage?

**Comment by avsm** [comment] 2020-02-29 07:11
Looks to me like shared libraries need to be disabled in the compiler configuration, or else it'll fail to relocate on PIE distributions. It seems pointless to generate the .so files in this particular switch anyway.

**Comment by shindere** [comment] 2020-03-02 09:42
Anil Madhavapeddy (2020/02/28 23:11 -0800):
> Looks to me like shared libraries need to be disabled in the compiler
> configuration, or else it'll fail to relocate on PIE distributions. It
> seems pointless to generate the .so files in this particular switch
> anyway.

Yeah, agreed!

**Comment by XVilka** [comment] 2020-03-02 10:50
I just checked with 4.10 switch (same Dockerfile as in https://github.com/ocaml/ocaml/issues/9131#issuecomment-564508959 just with updated switch):
```
STEP 10: RUN eval `opam env` &&   opam switch create 4.10.0+musl+static+flambda &&   opam switch 4.10.0+musl+static+flambda

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-variants.4.10.0+musl+static+flambda] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at
        "/home/user/.opam/4.10.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.10.0+musl+static+flambda/./configure
        --prefix=/home/user/.opam/4.10.0+musl+static+flambda CC=musl-gcc
        CFLAGS=-Os ASPP=musl-gcc -c --enable-flambda LIBS=-static".

#=== ERROR while compiling ocaml-variants.4.10.0+musl+static+flambda ==========#
# context              2.0.5 | linux/x86_64 |  | https://opam.ocaml.org#329ac381
# path                 ~/.opam/4.10.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.10.0+musl+static+flambda
# command              ~/.opam/4.10.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.10.0+musl+static+flambda/./configure --prefix=/home/user/.opam/4.10.0+musl+static+flambda CC=musl-gcc CFLAGS=-Os ASPP=musl-gcc -c --enable-flambda LIBS=-static
# exit-code            77
# env-file             ~/.opam/log/ocaml-variants-3-d0f245.env
# output-file          ~/.opam/log/ocaml-variants-3-d0f245.out
### output ###
# configure: Configuring OCaml version 4.10.0
# checking build system type... x86_64-pc-linux-musl
# checking host system type... x86_64-pc-linux-musl
# checking target system type... x86_64-pc-linux-musl
# checking for ld... ld
# checking how to print strings... printf
# checking for gcc... musl-gcc
# checking whether the C compiler works... no
# configure: error: in `/home/user/.opam/4.10.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.10.0+musl+static+flambda':
# configure: error: C compiler cannot create executables
# See `config.log' for more details



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-variants 4.10.0+musl+static+flambda
+- 
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
+- 
```

Dockerfile:
```Dockerfile
FROM alpine:edge AS builder
MAINTAINER John Doe <jdoe@gmail.com>

# Install the build dependencies
RUN apk add --no-cache make m4 which patch sudo wget git pkgconfig \
        gcc g++ musl-dev linux-headers libffi libffi-dev pcre perl python3 \
        gmp-dev pcre-dev xz-dev gmp xz coreutils \
        ocaml ocaml-compiler-libs ocaml-ocamldoc opam ocaml-findlib

RUN chmod +s `which bwrap`

RUN addgroup -g 1000 -S user && adduser -u 1000 -D -S user -G user
USER user
WORKDIR /home/user

RUN opam init --auto-setup --disable-sandboxing --yes && \
        eval `opam env` && opam install --yes ocamlfind

RUN eval `opam env` && \
  opam switch create 4.10.0+musl+static+flambda && \
  opam switch 4.10.0+musl+static+flambda

```

**Comment by copy** [comment] 2020-03-03 10:41
@XVilka There's no musl-gcc binary on Alpine, that's why compilation fails. You can use a regular switch to create static executables on Alpine, since musl is the default cc.

**Comment by avsm** [comment] 2020-03-16 21:27
I tracked this down. Turns out that the version of musl in Ubuntu 18.04 (1.1.19) has a bug with static linking, so I backported musl 1.1.24 to Bionic and created a PPA with it.

Doing:

```
# add-apt-repository -y ppa:avsm/musl
# apt-get -y install musl-tools
# opam switch create foo ocaml-variants.4.10.0+musl+static+flambda
```

Now works on ubuntu 18.04 with musl 1.1.24, and Ubuntu 19.10 works out of the box as it includes musl.1.1.24 already. I'll close this issue as it appears to be a musl issue and nothing to do with OCaml. Please reopen if this isn't the case.

**Closed as completed by avsm** 2020-03-16 21:27 UTC

**Comment by Zhang-Liao** [comment] 2020-09-27 14:31
I also meet a problem when using Ubuntu 20.04 LTS.

```
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-variants.4.10.0+musl+static+flambda] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at "/home/zhangliao/.opam/opam-init/hooks/sandbox.sh build make -j11 world".

#=== ERROR while compiling ocaml-variants.4.10.0+musl+static+flambda ==========#
# context     2.0.7 | linux/x86_64 |  | https://opam.ocaml.org#6dd388b3
# path        ~/.opam/foo/.opam-switch/build/ocaml-variants.4.10.0+musl+static+flambda
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j11 world
# exit-code   1
# env-file    ~/.opam/log/ocaml-variants-45106-6cc03f.env
# output-file ~/.opam/log/ocaml-variants-45106-6cc03f.out
### output ###
# bwrap: execvp make: No such file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-variants 4.10.0+musl+static+flambda
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─ 

<><> ocaml-variants.4.10.0+musl+static+flambda troubleshooting ><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    musl-tools

# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] y
```

Meanwhile, I have already installed `musl 1.1.24`.

```
test@test:~/Documents$ apt list --installed | grep 'musl'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

musl-dev/focal,now 1.1.24-1 amd64 [installed,automatic]
musl-tools/focal,now 1.1.24-1 amd64 [installed]
musl/focal,now 1.1.24-1 amd64 [installed,automatic]
```

I would be appreciated if anyone could give me some help.

**Comment by gasche** [comment] 2020-09-27 14:38
> bwrap: execvp make: No such file or directory

Do you have `make` installed on your system?

**Comment by nojb** [comment] 2020-09-27 14:38
>     # bwrap: execvp make: No such file or directory

This message seems to indicate that the problem is with `make` rather than with `musl`.

**Comment by Zhang-Liao** [comment] 2020-09-27 14:50
> > ```
> > # bwrap: execvp make: No such file or directory
> > ```
> 
> This message seems to indicate that the problem is with `make` rather than with `musl`.

Thanks for your help! I have solved the error.
