### ISSUE TITLE
Trying to build in M1, getting libraries for x86_64

### ISSUE THREAD

**Issue by querolita** [ocaml/ocaml#12115] opened 2023-03-16 13:39 UTC
I am trying to build a repository in an M1 machine (arm64) but I am getting some linking problems that seem to indicate that the configuration is not correctly set up. In particular, it generates some libraries for Intel (x86_64) but another one for M1 (arm64), so it fails to link. 

Maybe this is related to this other issue I posted in the `ocaml-rs` [repo](https://github.com/zshipko/ocaml-rs/issues/121)

```
 ; ocaml_config =
     { version = "4.14.0"
     ; standard_library_default = "/Users/anais.querol/.opam/mina/lib/ocaml"
     ; standard_library = "/Users/anais.querol/.opam/mina/lib/ocaml"
     ; standard_runtime = "the_standard_runtime_variable_was_deleted"
     ; ccomp_type = "cc"
     ; c_compiler = "cc"
     ; ocamlc_cflags =
         [ "-O2"; "-fno-strict-aliasing"; "-fwrapv"; "-pthread" ]
     ; ocamlc_cppflags = [ "-D_FILE_OFFSET_BITS=64" ]
     ; ocamlopt_cflags =
         [ "-O2"; "-fno-strict-aliasing"; "-fwrapv"; "-pthread" ]
     ; ocamlopt_cppflags = [ "-D_FILE_OFFSET_BITS=64" ]
     ; bytecomp_c_compiler =
         [ "cc"
         ; "-O2"
         ; "-fno-strict-aliasing"
         ; "-fwrapv"
         ; "-pthread"
         ; "-D_FILE_OFFSET_BITS=64"
         ]
     ; bytecomp_c_libraries = [ "-lm"; "-lpthread" ]
     ; native_c_compiler =
         [ "cc"
         ; "-O2"
         ; "-fno-strict-aliasing"
         ; "-fwrapv"
         ; "-pthread"
         ; "-D_FILE_OFFSET_BITS=64"
         ]
     ; native_c_libraries = [ "-lm" ]
     ; native_pack_linker = [ "ld"; "-r"; "-o" ]
     ; cc_profile = []
     ; architecture = "amd64"
     ; model = "default"
     ; int_size = 63
     ; word_size = 64
     ; system = "macosx"
     ; asm = [ "cc"; "-c"; "-Wno-trigraphs" ]
     ; asm_cfi_supported = true
     ; with_frame_pointers = false
     ; ext_exe = ""
     ; ext_obj = ".o"
     ; ext_asm = ".s"
     ; ext_lib = ".a"
     ; ext_dll = ".so"
     ; os_type = "Unix"
     ; default_executable_name = "a.out"
     ; systhread_supported = true
     ; host = "x86_64-apple-darwin21.6.0"
     ; target = "x86_64-apple-darwin21.6.0"
     ; profiling = false
     ; flambda = false
     ; spacetime = false
     ; safe_string = true
     ; exec_magic_number = "Caml1999X031"
     ; cmi_magic_number = "Caml1999I031"
     ; cmo_magic_number = "Caml1999O031"
     ; cma_magic_number = "Caml1999A031"
     ; cmx_magic_number = "Caml1999Y031"
     ; cmxa_magic_number = "Caml1999Z031"
     ; ast_impl_magic_number = "Caml1999M031"
     ; ast_intf_magic_number = "Caml1999N031"
     ; cmxs_magic_number = "Caml1999D031"
     ; cmt_magic_number = "Caml1999T031"
     ; natdynlink_supported = true
     ; supports_shared_libraries = true
     ; windows_unicode = false
     }
```

**Comment by nojb** [comment] 2023-03-16 13:46
Hello, thank you for your report. Unfortunately, it is lacking in detail so it cannot be investigated as it stands. At the very least, precise instructions to reproduce the problem and a description of expected and actual results are needed. And ideally using the compiler directly and not going through any other tool such as Dune to make sure that the issue really is coming from the compiler. Thanks!

**Comment by dbuenzli** [comment] 2023-03-16 14:09
This looks similar to https://github.com/ocaml/opam-repository/issues/19374

Are you sure you are using the xcode C toolchain and that you don't have a third-party C toolchain or install of `binutils` in your PATH ?

**Comment by querolita** [comment] 2023-03-16 14:59
I don't have other C toolchains, just the one in Xcode. 

I am trying to address the issue by telling cargo to use as target for that arm64 library explicitly `x86_64-apple-darwin`, so that at least all of the `.a` libraries are in the same architecture. But I guess this is not ideal.

**Comment by lthls** [comment] 2023-03-16 15:12
The compiler seems to be configured for `x86_64`, which doesn't seem to be what you expected. Could you tell us how you installed the OCaml distribution ? Reinstalling the compiler with the proper architecture support should solve some of your problems.

**Comment by mimoo** [comment] 2023-03-16 15:49
This is for https://github.com/MinaProtocol/mina/ where the flow is to import this [opam.export](https://github.com/MinaProtocol/mina/blob/develop/opam.export) file to setup your switch. Is `ocaml-base-compiler.4.14.0` not the right compiler to install for arm-based platforms?

**Comment by dbuenzli** [comment] 2023-03-16 16:11
> Is ocaml-base-compiler.4.14.0 not the right compiler to install for arm-based platforms?

It is, the package is oblivious of architecture. The architecture is determined from the C toolchain/environment when you install the package.

What is the output of `cc --version` ?

**Comment by querolita** [comment] 2023-03-17 10:06
This is the output for `cc --version`:
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

On another note, when I try to install opam using this command that is supposed to extract the right version for your machine: `bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"`

I get this prompt: 
```
## Using already downloaded "/var/folders/k8/2d6plj6d1zj8_6wc4tv7bp3c0000gp/T//opam-2.1.4-x86_64-macos"
```

Meaning, that it tries to install the one for x86_64, even if my `arch` is `arm64`. 
I downloaded manually the version 2.1.4 for arm64 and installed it. But now I am not sure if this one substituted the previous one, or if there's any command to completely uninstall all of opam and do it all from scratch making sure that the one for M1 is selected.

**Comment by querolita** [comment] 2023-03-17 10:30
Also, the output of `opam config report` is
```
# opam config report
# opam-version         2.1.4 
# self-upgrade         no
# system               arch=arm64 os=macos os-distribution=homebrew os-version=13.2.1
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 3
# repositories         1 (http), 2 (version-controlled) (default repo at 02a2b079)
# pinned               5 (http), 2 (rsync)
# current-switch       mina
# ocaml:native         true
# ocaml:native-tools   true
# ocaml:native-dynlink true
# ocaml:stubsdir       /Users/$USER/.opam/mina/lib/ocaml/stublibs:/Users/$USER/.opam/mina/lib/ocaml
# ocaml:preinstalled   false
# ocaml:compiler       4.14.0
```

**Comment by dbuenzli** [comment] 2023-03-17 10:31
> It is, the package is oblivious of architecture. The architecture is determined from the C toolchain/environment when you install the package.

And `opam` apparently :–) 

> But now I am not sure if this one substituted the previous one,

That depends on where you installed it and your `PATH`. 

Perhaps best is to restart from scratch. Get rid of all these opam binaries (`type opam` should tell you were they are), nuke your `~/.opam` and simply use [brew](https://brew.sh/) to install it (`brew install opam`). There must be enough people using that workflow to make sure it works. It will also be useful to handle external dependencies of opam packages.

**Comment by Octachron** [comment] 2023-06-28 13:08
Since it is not clear is the issue still exists, and it is the kind of  issue where it is hard to track what went and when wrong, I am proposing to close the issue. Don't hesitate to re-open the issue if you find more energy or time to investigate.

**Closed as completed by Octachron** 2023-06-28 13:08 UTC
Labels: submitter-action-needed
