### ISSUE TITLE
Add an alternative to the input_line function to the standard library

### ISSUE THREAD

**Issue by shindere** [ocaml/ocaml#8931] opened 2019-09-10 16:26 UTC
This issue is a follow-up to a discussion started in #8649 and may
be an interesting junior task, as discussed there.

**Comment by gadmm** [comment] 2019-09-12 13:29
If I understand correctly this task refers to the following:

> So @damiendoligez and I discussed this in person and it seems that the
problem is that a program reading a file with input_line will have no
way to distinguish a last-line ending with '\n' from one that has no
line terminator.

> We should add a new function to the standard library [...]

I tried to reproduce, but the one file ending with a new line gave me an additional empty string before raising End_of_file. Can you please describe how to reproduce the issue?

**Comment by shindere** [comment] 2019-09-12 13:33
@damiendoligez?

**Comment by xavierleroy** [comment] 2019-09-12 15:07
This is the behavior @damiendoligez is concerned about, if I understand correctly:
```
let writestring filename s =
  let oc = open_out filename in
  output_string oc s;
  close_out oc
;;
let readline filename =
  let ic = open_in filename in
  let l1 = input_line ic in
  let l2 = try input_line ic with End_of_file -> "<EOF>" in
  close_in ic;
  (l1,l2)
;;
writestring "/tmp/data" "xx\n";;
readline "/tmp/data";;
writestring "/tmp/data" "xx";;
readline "/tmp/data";;
```
Both calls to `readline` return `("xx", "<EOF>")`, even though the files differ by one newline.

I think this behavior of  `input_line` is the one you want most of the time: a line is terminated by a newline or by end-of-file, it doesn't matter which.  For comparing two files, it's not what you want, of course. But I'd rather solve #8649 by writing a different file comparison function than by adding a different `input_line` function to the stdlib.

**Comment by gadmm** [comment] 2019-09-12 16:42
Thanks.

> But I'd rather solve #8649 by writing a different file comparison function

Makes sense. Then there is nothing to do.

**Comment by pmetzger** [comment] 2019-09-12 17:53
FWIW, I have hacked together my own input function, several times, to have a "get line" function that keeps the newline if present. It turns up surprisingly often. If this was common lisp (where seventeen word long function names are normal) calling it "input_line_keeping_newline" or something would be the name. Here I'm less clear on what would be appropriate.

**Comment by shindere** [comment] 2019-09-13 07:18
Xavier Leroy (2019/09/12 08:07 -0700):
> I think this behavior of  `input_line` is the one you want most of the
> time: a line is terminated by a newline or by end-of-file, it doesn't
> matter which.  For comparing two files, it's not what you want, of
> course. But I'd rather solve #8649 by writing a different file
> comparison function than by adding a different `input_line` function
> to the stdlib.

But, AIUI, the problem is made a bit more complicated by the fact that
the comparison function should be tolerant to checkouts of the
repository with Windows-style line terminators. @dra27 on this?

**Comment by damiendoligez** [comment] 2019-09-13 09:10
We could add an optional argument to `input_line` to tell it to keep the newline instead of stripping it. Something like `input_line ~raw:true ic`.

@xavierleroy would you accept something like that?

**Comment by shindere** [comment] 2019-09-13 09:20
Damien Doligez (2019/09/13 02:10 -0700):
> We could add an optional argument to `input_line` to tell it to keep
> the newline instead of stripping it. Something like `input_line
> ~raw:true ic`.

Yeah I had the very same idea re:the choice of the name.

**Comment by dra27** [comment] 2019-09-24 09:24
I've commented on the original PR - personally not convinced about adding a specific function. I'm uneasy about `~raw` w.r.t. Windows/Unix line-ending considerations. That unease may not be justified - I just have an instinct that if you're starting to worry hugely about line-ending kinds or presence then you shouldn't be using high-level text-file processing functions.

**Comment by shindere** [comment] 2019-09-27 09:00
No strong opinion here.

Now that #8983 is around, does this concern vanish and we should simply
close this issue?

**Comment by dra27** [comment] 2019-09-27 09:26
If the function were added, `ocamltest` would use it, but it's very niche. I'd go for closing the issue, but if someone wants to do a pull request with the suggestion of the optional argument then that would be fine. I would worry that it would be easy to incorrectly interpret the `?raw` argument as somehow meaning that the the string would *always* end with `\n` (i.e. it's subtle to understand that there's one specific case where it might not be included)

**Comment by shindere** [comment] 2019-09-27 11:27
David Allsopp (2019/09/27 02:26 -0700):
> If the function were added, `ocamltest` would use it, but it's very
> niche. I'd go for closing the issue, but if someone wants to do a pull
> request with the suggestion of the optional argument then that would
> be fine. I would worry that it would be easy to incorrectly interpret
> the `?raw` argument as somehow meaning that the the string would
> *always* end with `\n` (i.e. it's subtle to understand that there's
> one specific case where it might not be included)

It would then have to be properly documented in the module's interface,
I think.

**Comment by dbuenzli** [comment] 2019-09-27 12:32
`input_line` is a convenience function. I don't think it's worth adding more toggles to it. If you need to be subtle about these things (e.g. writing a proper parser) you will likely end up not using it anyways.

**Comment by Octachron** [comment] 2020-02-25 10:21
Rereading the discussion, I am removing the newcomer job due to the the uncertainty in term of design.

**Comment by damiendoligez** [comment] 2020-07-20 15:44
The consensus seems to be that `input_line` is a convenience function and that its lossiness isn't a problem. When we want to be precise about newlines, we should use a more powerful tool like `ocamllex`.

**Closed as completed by damiendoligez** 2020-07-20 15:44 UTC
