### ISSUE TITLE
Configure failure with OCaml 4.07.1

### ISSUE THREAD

**Issue by IsaacBreen** [ocaml/ocaml#9713] opened 2020-06-26 04:43 UTC
When I try to run `opam switch create 4.07.1+flambda`, I'm told to submit a bug report with the following error: `[ERROR!] Since datatype sizes cannot be guessed when cross-compiling, a hardcoded list is used but your architecture isn't known yet. You need to determine the sizes yourself. Please submit a bug report in order to expand the list.`

Here is the full terminal output. I've substituted [USERNAME] for my username.

```
temp/coqgym » opam switch create 4.07.1+flambda

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ocaml-variants.4.07.1+flambda] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at "/Users/[USERNAME]/.opam/opam-init/hooks/sandbox.sh build
        ./configure -prefix /Users/[USERNAME]/.opam/4.07.1+flambda -with-debug-runtime -flambda -cc cc -aspp cc
        -c".

#=== ERROR while compiling ocaml-variants.4.07.1+flambda ======================#
# context     2.0.7 | macos/x86_64 |  | https://opam.ocaml.org#c189023a
# path        ~/.opam/4.07.1+flambda/.opam-switch/build/ocaml-variants.4.07.1+flambda
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /Users/[USERNAME]/.opam/4.07.1+flambda -with-debug-runtime -flambda -cc cc -aspp cc -c
# exit-code   2
# env-file    ~/.opam/log/ocaml-variants-77222-1872ec.env
# output-file ~/.opam/log/ocaml-variants-77222-1872ec.out
### output ###
# Configuring OCaml version 4.07.1
# Configuring for host x86_64-apple-darwin19.5.0 ...
# Configuring for target x86_64-apple-darwin19.5.0 ...
# Using compiler cc.
# Compiler family and version: gcc-4-8.
# The C compiler is ISO C99 compliant.
# Checking the sizes of integers and pointers...
# [ERROR!] Since datatype sizes cannot be guessed when cross-compiling,
#  a hardcoded list is used but your architecture isn't known yet.
#  You need to determine the sizes yourself.
#  Please submit a bug report in order to expand the list.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build ocaml-variants 4.07.1+flambda
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─

<><> ocaml-variants.4.07.1+flambda troubleshooting ><><><><><><><><><><><><>  🐫
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] y```
```

Here is the output of `opam config report`

```
temp/coqgym » opam config report
# opam config report
# opam-version      2.0.7
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.15.5
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at c189023a)
# pinned            0
# current-switch    4.07.0+fp+flambda
```

**Comment by avsm** [comment] 2020-06-26 10:47
This looks like a core compiler issue rather than with the opam-repository, so transferring it there. Firstly, does any other flambda release of OCaml work (such as 4.10.0+flambda), the most recently released.

**Comment by gasche** [comment] 2020-06-26 11:25
It looks like the failure comes from the `./configure` script. My guess would be that @IsaacBreen is using a recent OSX system whose host triple wasn't known at the time `./configure` was generated. If this guess is correct, a way to avoid this problem could be for the opam package to depend on `autoconf` and then regenerate the `configure` script as first step. This raises interesting questions about forward-compatibility of source releases with an autoconf-generated configure script.

**Comment by xavierleroy** [comment] 2020-06-26 14:04
Note that this is OCaml 4.07, a version that predates the autoconf-generated "configure" script.  Here, we still have the old hand-written "configure" script.  It is complaining (in a roundaboud way) that it could not run `config/auto-aux/sizes.c`: either it didn't compile or it ran with nonzero exit code.  The hardcoded sizes are exclusively for the Windows ports.

The problem is essentially impossible to debug through OPAM.  Could the original poster download a copy of the sources (https://github.com/ocaml/ocaml/archive/4.07.1.tar.gz) and run `./configure -verbose` ?

It could be worth trying a newer version of OCaml, e.g. `opam switch create 4.10.0`, to see if the new configure infrastructure makes a difference or produces more informative diagnostics.

**Comment by xavierleroy** [comment] 2020-06-26 14:09
Also, this part of the output is suspect:
```
# Using compiler cc.
# Compiler family and version: gcc-4-8.
```
macOS 19.5.0 doesn't use GCC, especially not an old version like 4.8, it uses Clang 11.0.  Where does this alternate compiler comes from?  Is it really working?

**Comment by damiendoligez** [comment] 2020-11-26 15:45
@IsaacBreen Are you still interested in solving this, or did you manage to make OCaml work on your own?

**Closed as completed** 2021-06-01 13:43 UTC
