### ISSUE TITLE
Test '/weak-ephe-final/finaliser_handover' is flaky

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#12544] opened 2023-09-11 11:39 UTC
This test has been observed to fail on ae28598bba692d256e351f39f3a18ce0f706e5ca and in the CI of #12541, with the following messages, respectively:

```
Fatal error: exception File "finaliser_handover.ml", line 39, characters 2-8: Assertion failed
```
and
```
[02] file runtime/domain.c; line 1822 ### Assertion failed: caml_gc_phase == Phase_sweep_and_mark_main
```

**Comment by lthls** [comment] 2023-09-11 11:44
Duplicate of #12345

**Comment by shindere** [comment] 2023-09-11 12:07
Indeed. Closing.

**Closed as completed** 2023-09-11 12:10 UTC
