### ISSUE TITLE
Usefulness of Unix.open_process_args* functions is limited by them not respecting PATH environment variable

### ISSUE THREAD

**Issue by frou** [ocaml/ocaml#10083] opened 2020-12-13 10:39 UTC
As an alternative to the other `Unix.open_process*` functions (that take a single string and rely on `Filename.quote_command`), these `Unix.open_process_args*` functions introduced in 4.08 are nice. But crucially they don't currently respect the `PATH` environment variable, limiting their usefulness.

e.g. I'd expect the following to work, since `/usr/bin` is mentioned in my `PATH` and the executable `/usr/bin/uname` exists.

```ocaml
let ic, oc = Unix.open_process_args "uname" [| "uname"; "-a" |]
let status = Unix.close_process (ic, oc)
```

But `status` is `Unix.WEXITED 127` because the executable couldn't be found.

I think this is beacause the implementation is using the `execv` syscall rather than `execvp`.

**Comment by nojb** [comment] 2020-12-13 10:42
Related/duplicate of #10057. I agree that we should probably fix this.

**Comment by frou** [comment] 2020-12-13 10:51
Wow you're fast! You managed to cross-reference them before I did :)

**Closed as completed** 2020-12-21 18:30 UTC
