### ISSUE TITLE
Insufficient precision when printing floats

### ISSUE THREAD

**Issue by glondu** [ocaml/ocaml#10744] opened 2021-11-02 08:31 UTC
OCaml prints floats with 12 digits of precision (look for `%.12g`, in particular in stdlib/stdlib.ml and tools/dumpobj.ml). However, this is not sufficient in general, as shown by the following example:

    # let x = 4643037053177141657L in Int64.(sub x (x |> float_of_bits |> string_of_float |> float_of_string |> bits_of_float));;
    - : int64 = -1L

For IEEE 754 floating-point numbers, 17 digits are sufficient so that the number can be read back without any discrepancy (see _Modern Computer Arithmetic_ by Brent and Zimmermann, section 3.6.1 _Floating-point output_), and they are needed in the above example.

In typing/oprint.ml, something more clever is done (attempts with 12, 15 and 18 digits), which is correct but could be improved.

I think the same function should be used everywhere. It could be a `sprintf "%.17g"`, or something more clever à la typing/oprint.ml that tries to output less digits.

**Comment by dbuenzli** [comment] 2021-11-02 10:17
It's a bit unclear in which context you are getting the problem so the following may not help, but if you really care about floating point interchange a better answer is usually to just use the textual binary representation available via `"%h"`.

**Comment by xavierleroy** [comment] 2021-12-27 16:42
If I remember correctly my old experiments, `sprintf "%.17g"` as implemented in several popular C standard libraries has a tendency to print 2.9999999999999999 where 3 would be correct.  That's the historical reason for using `%.12g` in `string_of_float` and the more sophisticated but more costly algorithm in oprint.ml.

**Comment by xavierleroy** [comment] 2021-12-27 16:43
Also: +1 for using hexadecimal FP format for accurate exchange of FP values.

**Comment by edwintorok** [comment] 2022-12-24 23:37
Duplicate of #11360 (which has a more extensive discussion).

**Comment by nojb** [comment] 2022-12-25 02:17
Duplicate of #11360

**Closed as not planned** 2022-12-25 02:17 UTC
