### ISSUE TITLE
[Manual] remove <div> inside <pre>

### ISSUE THREAD

**Issue by Chris00** [ocaml/ocaml#9109] opened 2019-11-11 12:49 UTC
The HTML rendering of the manual puts `<div>` tags inside `<pre>` while [this is disallowed by the HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre).  This causes problems to processing tools — they may rewrite the code to it is valid.

Example: the [core tutorial examples](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) are rendered as
```html
<pre><div class="caml-input"> 1+2*3;;
</div><div class="caml-output ok">- : int = 7
</div></pre>

<pre><div class="caml-input"> let pi = 4.0 *. atan 1.0;;
</div><div class="caml-output ok">val pi : float = 3.14159265358979312
</div></pre>

<pre><div class="caml-input"> let square x = x *. x;;
</div><div class="caml-output ok">val square : float -&gt; float = &lt;fun&gt;
</div></pre>

<pre><div class="caml-input"> square (sin pi) +. square (cos pi);;
</div><div class="caml-output ok">- : float = 1.
</div></pre>
```
The `<div>` should be replaced by `<span>`.

**Comment by Chris00** [comment] 2019-11-11 12:51
I supppose [those lines](https://github.com/ocaml/ocaml/blob/trunk/manual/manual/macros.hva#L96-L103) are the culprit.  I can submit a PR.

**Comment by sanette** [comment] 2019-11-11 13:09
> The `<div>` should be replaced by `<span>`.

how about using `<code>` instead?

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element

**Comment by Chris00** [comment] 2019-11-11 13:11
Yes, `<code>` is better for the input (maybe not for the output).

**Comment by Octachron** [comment] 2019-11-11 14:05
I think the best is to integrate those changes within #9089

**Comment by Octachron** [comment] 2019-11-28 14:23
This should be fixed in #9089, in a less than perfect way due to some hevea limitation.

**Closed as completed by Octachron** 2019-11-28 14:23 UTC

**Comment by sanette** [comment] 2020-03-13 14:36
I now have the same issue with `<sub>` inside `<pre>`, although I'm not sure they are forbidden, but the `<sub>` is kicked out of the `<pre>` when preprocessed by the ocaml.org machine.

**Comment by Octachron** [comment] 2020-03-13 14:52
Sub is a [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) and is allowed inside `pre`?

**Comment by sanette** [comment] 2020-03-13 14:57
yes, it seems it should be allowed. Does it mean the problem is in Nethtml?

**Comment by sanette** [comment] 2020-03-13 15:03
```
#require "netstring";;
# let s = "The <pre>H<sub>2</sub>O</pre> molecule";;
val s : string = "The <pre>H<sub>2</sub>O</pre> molecule"
# Nethtml.parse_document (Lexing.from_string s);;
- : Nethtml.document list =
[Nethtml.Data "The "; Nethtml.Element ("pre", [], [Nethtml.Data "H"]);
 Nethtml.Element ("sub", [], [Nethtml.Data "2"]); Nethtml.Data "O";
 Nethtml.Data " molecule"]
```

**Comment by Octachron** [comment] 2020-03-13 15:31
It looks like `sub` is explicitly excluded from `pre` in netstring, and I don't know why, it is probably worth it to open an issue on the ocamlnet side .

**Comment by sanette** [comment] 2020-03-13 16:02
if someone with a gitlab account could do it I'd be grateful

**Comment by gerdstolpmann** [comment] 2020-03-30 08:47
The html parser is somewhat outdated. It still encodes the HTML-4 rules, which did not allow anything inside `pre`. The parsing rules are controlled by the `dtd` parameter of `Nethtml.parse_document`. This parameter defaults to `Nethtml.html_40_dtd` but there is also `relaxed_html40_dtd` (you could try that). If the relaxed DTD does also not work for you, there is also the option that you define your own.

Eventually it would be good to also include a DTD that matches current HTML-5. Any input on this is highly welcome on my side.

**Comment by Drup** [comment] 2020-03-30 12:37
I suggest just delegating to [markup](https://github.com/aantron/markup.ml), which is an spec compliant parser for HTML5.

BTW, there is no real DTD for HTML5, it's not a subset of XML like XHTML anymore, there are only rough approximations.
