### ISSUE TITLE
with-dkml ocamlopt ... graphics.cmxa

### ISSUE THREAD

**Issue by ghost** [ocaml/ocaml#12141] opened 2023-03-28 13:32 UTC
sys : win 11
used the recommended DKML installer

Hello,

I try to do this example from https://ocaml.org/docs/first-hour

```
open Graphics;;

open_graph " 640x480";;

for i = 12 downto 1 do
  let radius = i * 20 in
    set_color (if i mod 2 = 0 then red else yellow);
    fill_circle 320 240 radius
done;;

read_line ();;
```

There is not graphics here :
```
ocamlc -where
C:/Users/****/AppData/Local/Programs/DISKUV~1/lib/ocaml
```

It is here:
`C:\Users\****\AppData\Local\opam\playground\lib\graphics`

![im](https://user-images.githubusercontent.com/9338756/228251429-77348800-dd87-4cab-9d65-795e2d00cbbd.png)

```
 with-dkml ocamlfind ocamlopt -o a.exe -I C:\Users\****\AppData\Local\opam\playground\lib\graphics\graphics.cmxa test_graphique.ml
File "test_graphique.ml", line 1, characters 5-13:
1 | open Graphics;;
         ^^^^^^^^
Error: Unbound module Graphics
```

`opam list -a`
gives
![Capture d'écran 2023-03-28 141524](https://user-images.githubusercontent.com/9338756/228253201-2a0404cb-7a5e-4097-b1dd-24e753bf05b0.png)

Can You help me to compile this  ?

Thanks

**Comment by kit-ty-kate** [comment] 2023-03-28 13:39
```
 with-dkml ocamlfind ocamlopt -o a.exe -I C:\Users\****\AppData\Local\opam\playground\lib\graphics\graphics.cmxa test_graphique.ml
 ```
If this is the command you've used I think this is the cause of the problem. The standard way to use packages with ocamlfind is to use its `-package` parameter so the following command should be used instead:
```
 with-dkml ocamlfind ocamlopt -o a.exe -package graphics -linkpkg test_graphique.ml
 ```

**Comment by ghost** [comment] 2023-03-28 13:41
> with-dkml ocamlfind ocamlopt -o a.exe -package graphics -linkpkg test_graphique.ml
ocamlfind: Package `graphics' not found

and with this example from https://diskuv-ocaml.gitlab.io/distributions/dkml/doc/BeyondBasics.html

where i have done 


```
(* let () = print_endline "Hello, World!" *)

open Graphics;;

open_graph " 640x480";;

for i = 12 downto 1 do
  let radius = i * 20 in
    set_color (if i mod 2 = 0 then red else yellow);
    fill_circle 320 240 radius
done;;

read_line ();;
```

I get :
```
dune build
File "helloworld.ml", line 3, characters 5-13:
3 | open Graphics;;
         ^^^^^^^^
Error: Unbound module Graphic
```

```
with-dkml ocamlopt -o a.exe graphics.cmxa test_graphique.ml
File "test_graphique.ml", line 1, characters 5-13:
1 | open Graphics;;
         ^^^^^^^^
Error: Unbound module Graphics
```

**Comment by Octachron** [comment] 2023-03-28 15:32
`Graphics` is a library that you need to declare as a dependency in your dune file with `(libraries graphics)`:
```ocaml
(executable
  (name your_executable_name)
  (libraries graphics)
)
```
I am closing the issue since it is not related to the compiler; but don't hesitate to ask further questions in this issue or at `discuss.ocaml.org`.

**Closed as completed by Octachron** 2023-03-28 15:32 UTC

**Comment by ghost** [comment] 2023-03-28 17:46
> `Graphics` is a library that you need to declare as a dependency in your dune file with `(libraries graphics)`:
> 
> ```ocaml
> (executable
>   (name your_executable_name)
>   (libraries graphics)
> )
> ```
> 
> I am closing the issue since it is not related to the compiler; but don't hesitate to ask further questions in this issue or at `discuss.ocaml.org`.

doesn't work...
I get
```
PS C:\Users\detro\DiskuvOCamlProjects\helloworld> dune build
File "dune", line 3, characters 12-20:
3 |  (libraries graphics ))
                ^^^^^^^^
Error: Library "graphics" not found.
-> required by _build/default/helloworld.exe
-> required by alias all
-> required by alias default
```
and  `with-dkml utop`
![a](https://user-images.githubusercontent.com/9338756/228323809-527dbb02-4a99-44bb-af26-5ac332e6abf5.png)

**Comment by Octachron** [comment] 2023-03-28 17:59
It looks like the graphics library is not installed in the environment. How did you install the graphics library?

**Comment by ghost** [comment] 2023-03-28 18:04
> It looks like the graphics library is not installed in the environment. How did you install the graphics library?

It seems to be installed by defaut.

To reinstall graphics I have done 

`with-dkml opam uninstall graphics`

and 

`with-dkml opam install graphics`

and see it only in 


```
PS C:\Users\detro> ls C:/Users/***/AppData/Local/opam/playground\lib\graphics\


    Répertoire : C:\Users\***\AppData\Local\opam\playground\lib\graphics


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-ar---        28/03/2023     14:11            921 dune-package
-ar---        28/03/2023     14:11          51915 graphics.cma
-ar---        28/03/2023     14:11          10101 graphics.cmi
-ar---        28/03/2023     14:11         108420 graphics.cmt
-ar---        28/03/2023     14:11          69395 graphics.cmti
-ar---        28/03/2023     14:11           3606 graphics.cmx
-ar---        28/03/2023     14:11            611 graphics.cmxa
-ar---        28/03/2023     14:11          54784 graphics.cmxs
-ar---        28/03/2023     14:11          32162 graphics.lib
-ar---        28/03/2023     14:11           8556 graphics.ml
-ar---        28/03/2023     14:11          15717 graphics.mli
-ar---        28/03/2023     14:11          49886 libgraphics_stubs.lib
-ar---        28/03/2023     14:11            203 META
-ar---        28/03/2023     14:11           1099 opam

```

And I see it emphasized with 
`opam list -a`

**Comment by Octachron** [comment] 2023-03-28 18:09
What does `opam switch` return?

**Comment by ghost** [comment] 2023-03-28 18:11
> What does `opam switch` return?
```

PS C:\Users\***> opam switch
#  switch                                                  compiler             description
   C:\Users\***\AppData\Local\Programs\DiskuvOCaml\dkml  ocaml-system.4.14.0  C:\Users\***\AppData\Local\Programs\DiskuvOCaml\dkml
   C:\Users\detro\my-first-switch                          ocaml-system.4.14.0  C:\Users\***\my-first-switch
→  playground                                              ocaml-system.4.14.0  playground

[WARNING] The environment is not in sync with the current switch.
          You should run: (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
PS C:\Users\***>
```

**Comment by Octachron** [comment] 2023-03-28 18:12
You should try to apply the advice on the last line, run:
```bash
(& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
```
and then reinstall graphics.

**Comment by ghost** [comment] 2023-03-28 19:14
> You should try to apply the advice on the last line, run:
> 
> ```shell
> (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
> ```
> 
> and then reinstall graphics.

It is the same problem after doing

`(& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }`

```
PS C:\Users\***> with-dkml opam remove graphics
[NOTE] External dependency handling not supported for OS family 'windows'.
       You can disable this check using 'opam option --global depext=false'
The following actions will be performed:
=== remove 1 package
  λ graphics         5.1.2 (pinned)
=== recompile 4 packages
  ↕ base-bytes       base (pinned)   [uses ocamlfind]
  ↕ ocaml-lsp-server 1.12.2 (pinned) [uses omd]
  ↕ ocamlfind        1.9.1 (pinned)  [uses graphics]
  ↕ omd              1.3.1 (pinned)  [uses ocamlfind]

Proceed with λ 1 removal and ↕ 4 recompilations? [y/n] y
[NOTE] External dependency handling not supported for OS family 'windows'.
       You can disable this check using 'opam option --global depext=false'

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
λ removed   ocaml-lsp-server.1.12.2
▼ retrieved ocamlfind.1.9.1  (cached)
▼ retrieved omd.1.3.1  (cached)
λ removed   omd.1.3.1
λ removed   base-bytes.base
λ removed   ocamlfind.1.9.1
λ removed   graphics.5.1.2
[WARNING] .install file is missing .exe extension for src/findlib/ocamlfind
[WARNING] .install file is missing .exe extension for src/findlib/ocamlfind_opt
[WARNING] Automatically adding .exe to
          C:\Users\***\AppData\Local\opam\playground\.opam-switch\build\ocamlfind.1.9.1\src\findlib\ocamlfind.exe
[WARNING] Automatically adding .exe to
          C:\Users\***\AppData\Local\opam\playground\.opam-switch\build\ocamlfind.1.9.1\src\findlib\ocamlfind_opt.exe
[WARNING] C:\Users\***\AppData\Local\opam\playground\bin\safe_camlp4 is a script; the command won't be available
✶ installed ocamlfind.1.9.1
✶ installed base-bytes.base
✶ installed omd.1.3.1
✶ installed ocaml-lsp-server.1.12.2
Done.

```


and

```

PS C:\Users\***> with-dkml opam install graphics
[NOTE] External dependency handling not supported for OS family 'windows'.
       You can disable this check using 'opam option --global depext=false'
The following actions will be performed:
=== recompile 4 packages
  ↕ base-bytes       base (pinned)   [uses ocamlfind]
  ↕ ocaml-lsp-server 1.12.2 (pinned) [uses omd]
  ↕ ocamlfind        1.9.1 (pinned)  [uses graphics]
  ↕ omd              1.3.1 (pinned)  [uses ocamlfind]
=== install 1 package
  ✶ graphics         5.1.2 (pinned)

Proceed with ↕ 4 recompilations and ✶ 1 installation? [y/n] y
[NOTE] External dependency handling not supported for OS family 'windows'.
       You can disable this check using 'opam option --global depext=false'

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
▼ retrieved ocamlfind.1.9.1  (cached)
▼ retrieved omd.1.3.1  (cached)
λ removed   ocaml-lsp-server.1.12.2
λ removed   omd.1.3.1
λ removed   base-bytes.base
λ removed   ocamlfind.1.9.1
✶ installed graphics.5.1.2
[WARNING] .install file is missing .exe extension for src/findlib/ocamlfind
[WARNING] .install file is missing .exe extension for src/findlib/ocamlfind_opt
[WARNING] Automatically adding .exe to
          C:\Users\***\AppData\Local\opam\playground\.opam-switch\build\ocamlfind.1.9.1\src\findlib\ocamlfind.exe
[WARNING] Automatically adding .exe to
          C:\Users\***\AppData\Local\opam\playground\.opam-switch\build\ocamlfind.1.9.1\src\findlib\ocamlfind_opt.exe
[WARNING] C:\Users\***\AppData\Local\opam\playground\bin\safe_camlp4 is a script; the command won't be available
✶ installed ocamlfind.1.9.1
✶ installed base-bytes.base
✶ installed omd.1.3.1
✶ installed ocaml-lsp-server.1.12.2
Done.
```


```
PS C:\Users\***\DiskuvOCamlProjects\helloworld> dune build
File "dune", line 3, characters 12-20:
3 |  (libraries graphics ))
                ^^^^^^^^
Error: Library "graphics" not found.
-> required by _build/default/helloworld.exe
-> required by alias all
-> required by alias default
```

**Comment by Octachron** [comment] 2023-03-29 08:52
Do you mean that you get the exact same errors? Also note that the dkml tutorial use a local switch that is selected from the current directory. If you are using this layout, it is important that you install opam packages from the same directory; otherwise your projects will not see the installed packages.
