### ISSUE TITLE
`Thread.exit` considered harmful

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/ocaml#9071] opened 2019-10-25 14:52 UTC
I would like to deprecate/remove `Thread.exit`, because it prevents writing resource-safe code.

When a resource is not handled by the GC (for whatever reason), a standard way of allocating it for a limited period of time is to use `Fun.protect` (or a ad-hoc re-implementation thereof). This function guarantees that the `finally` function it is given as parameter will be executed at the end of the execution of the other given closure. However, `Thread.exit` breaks this invariant, since it can terminate the current thread even before the finally function is run.

Not only `Thread.exit` makes it impossible to use reliably such programming idiom, but it also incompatible with GC-based finalizers. Indeed, if  `Thread.exit` is run from within a finalizer, then the `running_finalisation_function` will never be reset, which results in finalizers no longer be run at all by the program! I have related problems for my implementation of Statmemprof.

There is an easy way to replace `Thread.exit`: simply throw a dedicated exception and catch it at the entry point of the thread.

Note that some recent programming languages (e.g., Rust), do not provide such a thread exit function. What Rust provide, `panic`, does perform stack unwinding for cleaning resources.

I know this proposal is likely to be polemic, hence I am not opening a PR, and wait for thoughts of other OCaml developers here.

Cc @gadmm, who nowadays thinks a lot about resource safety in OCaml.

Note that the same issue exists when a thread calls `Unix.fork` : in this case, all threads but one is killed, which causes the same problem as described above.

**Comment by dbuenzli** [comment] 2019-10-25 15:27
It seems I never used `Thread.exit` either publicly or privately in my code. 

The only mention besides the `ocaml` repo I found on my hard drive is in the sources of the ocamlunix book in [this chapter](http://ocaml.github.io/ocamlunix/threads.html#sec152), where it actually warns against using it and suggests to do exactly what you say :

>  Calling Thread.exit is often not a solution either, because we risk not having properly deallocated the thread’s open resources, and in particular the connection.
> 
> One solution consists of raising an exception to signify a fatal stop (for example an Exit exception), causing finalization code to be executed as it is handled.

Did you investigate library usage on `opam` ? E.g. see [here](https://github.com/ocaml/ocaml/pull/8873#issuecomment-521311078) on how to get a source sample.

**Comment by gadmm** [comment] 2019-10-25 16:07
Thanks for the ping, this is an interesting question.

Here's a grep of opam sources: https://gitlab.com/gadmm/stdlib-experiment/raw/master/other/async_audit/thread_exit.

> I know this proposal is likely to be polemic, hence I am not openning a PR, and wait for thoughts of other OCaml developpers here.

I know that here it does not makes a difference because the patch would be trivial, but in case you had code to share, it is also possible to open a draft PR with [RFC] (request for comments) in the title.

More to come on the matter.

**Comment by xavierleroy** [comment] 2019-10-25 17:22
I vaguely remember a time when `Thread.exit` was implemented by.... raising a private exception, said exception being caught in `Thread.create`.  I can't find that code, though.  But would you like this implementation?  It plays nice with `Fun.protect` et al.  It doesn't play nice with
```
try ... with x -> (* do not re-raise x *)
```
but such code is already broken, so we're not making it any worse.

**Comment by jhjourdan** [comment] 2019-10-25 18:09
> I vaguely remember a time when Thread.exit was implemented by.... raising a private exception, said exception being caught in Thread.create. I can't find that code, though. 

Indeed, cf. #8110 and 29b096a3a92496f2128036cf0c78b589ef0c3814.

> It plays nice with Fun.protect et al. It doesn't play nice with
>
> ```
> try ... with x -> (* do not re-raise x *)
> ```
>
> but such code is already broken, so we're not making it any worse.

Indeed, and fixing this was exactly the intent of the commit above.

**Comment by gadmm** [comment] 2019-10-25 21:47
Obviously the resource-conscious programmer must not use `Thread.exit`. Apparently this is already known and documented in some places as @dbuenzli showed.

In addition, it is already impossible to predict which thread is going to run a finalizer (which is properly documented in gc.mli), so you can be sure that nobody relies on calling Thread.exit from finalizers (and similarly for other asynchronous callbacks).

One thing that surfaced in the discussions around resource management is that inside OCaml's historic application domain (logic and language tools), deterministic resource management is less important, and we seem to be happy to just rely on finalisers and the OS to clean-up system resources. On the other hand we are happy to gain the use of asynchronous exceptions, which are currently incompatible with unwind-protect. In this dialect, there is nothing wrong with `Thread.exit`, so it will be hard to argue that deprecating `Thread.exit` now will help fix buggy programs.

(This is going to change with multicore, which will have to make sure to deprecate Thread.exit in their systhreads compatibility layer. The reason is that multicore makes deterministic resource management a central part of its design. For instance stacks are allocated statically, and fibers must be disposed-of by hand and it has been decided not to attach them finalisers by default. So IIUC any code that uses algebraic effects will become resource-sensitive. In fact, at https://github.com/ocaml-multicore/ocaml-multicore/pull/240, Thread.exit is again proposed to be implemented by raising an exception. How to respect backwards compatibility in the wake of multicore is another subject entirely, which goes well beyond Thread.exit.)

I would like to mention that it is not possible to discuss the use of `panic` in Rust for task cancellation without mentioning _poisoning_. Currently in OCaml, somebody who raises an exception for thread termination needs to coordinate with people holding locks to mutable shared memory, and automatically releasing locks is not enough: the shared memory could be left in an inconsistent state. So thread exit cannot happen anywhere. This is solved in Rust by communicating the cancellation across shared containers (setting a "poisoned" flag), in order to relieve the person acquiring a lock from the duty of predicting where panics could happen (by definition, you do not predict panics...). In OCaml this would require a notion of special exception that Mutex, etc., would need to learn to treat specially. It is also necessary to mention that the ability to catch panics is fairly restricted in Rust, so this avoids the problems with code like `try ... with x -> (* do not re-raise x *)`. The idea of raising an exception to terminate a thread is more error-prone and harder to reason about without the assistance from the language.

I thought quite a bit about how to transpose Rust's panic to OCaml in a backwards-compatible way. For that specific issue with code in the wild (or future code from beginners...) that swallows exceptions, I have thought that it would be fairly easy to implement signals whose handler raise an exception just after setting the signal again, such that the exception raises itself again asynchronously as soon as unwinding leaves resource clean-up code (assuming resource-management devices with masking for asynchronous exceptions); or also exceptions that re-raise themselves when discarded (assuming first-class resources in the language that allows giving an effectful destructor to the exception). The idea is to really enforce the rule "a catch-all should re-raise", backwards-compatibly. The report at #8110 comforts me in the idea that this is a real issue. The first of the two ideas is probably the most easily reachable solution (there are PRs implementing masking and `Fun.with_resource`), but the point is that I do not know a short-term solution if one wanted to implement thread exit by raising.

Your problem is much simpler though, and I am not sure there is a need to deprecate anything at this stage. My recommendation is to:

* Document that calling Thread.exit inside finalisers and memprof callbacks is UB, or something along these lines. This is not really a language change: Thread.exit is already unreliable in finalisers unless there is only one thread IIUC (though reality might be more complicated). (For signal handlers one would have to check both the resource-safety and uses in the wild as I do not know if the same reasoning applies; a signal handler that calls Thread.exit will at least forget to set `caml_something_to_do`.)

* Optionally document that Thread.exit interacts poorly with deterministic resource management, along the lines of the doc found by Daniel, http://ocaml.github.io/ocamlunix/threads.html#sec152.

(cc @lpw25 @stedolan)

**Comment by jhjourdan** [comment] 2019-10-26 14:55
> Here's a grep of opam sources: https://gitlab.com/gadmm/stdlib-experiment/raw/master/other/async_audit/thread_exit.

Thanks for this !

I did a bit of exploration. Actually, in most of the case, `Thread.exit ()` is called at position which is very close to the end of the thread's main function so the call is effectively just a no-op. Given that this is the majority of cases confirm my opinion that this function should be deprecated: most of the time, it is misued. In some cases, this requires just a bit of refactoring, but this is really not a big deal. Sometimes, this refactoring will very likely result in the use of an exception, but again, I don't think this is an issue (see uses `sill.1.4`, for example).

In one library, `Thread.exit` is used as part of a public API (see `xapi-stdext.2.1.0/lib/threadext.ml`), so there is no easy fix (well, apart from deprecating this public API...).

The uses where I was not able to understand the surrounding code and figure out what would be an easy migration plan are `bigbro.2.0.4-rev3/linear_connection.ml`, `async_unix.v0.12.0/src/raw_scheduler.ml` and Coq.

There are also uses in the support libraries for JSOO which I don't understand, but the situation is different, since they ues a diferent implementation of threads anyways.

**Comment by jhjourdan** [comment] 2019-10-26 15:00
> Your problem is much simpler though, and I am not sure there is a need to deprecate anything at this stage. My recommendation is to:

I know I can fix my problem with finalisers/memprof in another, easier way. Actually, I can even use GC roots to detect the fact that a thread has ended prematurely and fix the bug of finalisers and provide a sound implementation for memprof. But this is rater hacky, so I prefer raising the question of the more radical solution of deprecating `Thread.exit`.

> It plays nice with Fun.protect et al. It doesn't play nice with [...]

Actually, it does not play nice with another common pattern in OCaml : catching unknown exceptions and wrapping them in others (something that is also mentioned in #8110). This pattern is also used in .... `Fun.protect`, so...

**Comment by xavierleroy** [comment] 2019-10-27 17:18
> Actually, it does not play nice with another common pattern in OCaml : catching unknown exceptions and wrapping them in others (something that is also mentioned in #8110). This pattern is also used in .... Fun.protect, so...

Then the thread would terminate with an "uncaught exception" runtime message, but it would still terminate.  I think this is a very decent behavior for something (raising an exception in a `~finally` function of a `Fun.protect`) that is documented as a "programming error" already.

So, I am in favor of reimplementing `Thread.exit` using an exception, but not in favor of deprecating it.

**Comment by gadmm** [comment] 2019-10-28 01:52
Thank you Jacques-Henri for this exploration. So my take-away is indeed that deprecating Thread.exit would break actual and correct programs and that there does not seem to be a mechanical evolution path. The example of Async is particularly interesting. (Note that xapi-stdext.2.1.0 has the following description: _"This library is provided for a transitionary period only. No new code should use this library."_.)

#### Asynchronous callbacks

> I know I can fix my problem with finalisers/memprof in another, easier way. [...]

Your reply makes me believe that I did not explain my idea the best I could: I do not think you should have to use a hack, and the behaviour of Thread.exit should eventually be made compatible with resource management idioms or removed. I want to be careful about the _how_, and to put it in the broader context of a host of similar issues with resource management. I understand that you conflate two issues because you hope to kill two birds with one stone: 1) the issue with async callbacks, 2) the general issue with it being resource-unsafe.

For 1), let me expand on my "or something along these lines": if you want a safe behaviour, you can just have Thread.exit raise a failure in that condition. Being able to detect (from the runtime) when one is inside an async callback is straightforward to implement, and it is also something meaningful to know, so it may even be useful for other things in the future so it is worth the effort (I can even volunteer to do it). (Also note: IIUC in multicore it is not yet clear where/how finalisers will run, Leo likes to suggest that they should run in their own threads, so a different choice of behaviour here than failure is likely to behave differently in multicore, and we will likely end up turning it into a failure anyway...)

#### Resource safety

> Then the thread would terminate with an "uncaught exception" runtime message, but it would still terminate. I think this is a very decent behavior for something (raising an exception in a `~finally` function of a `Fun.protect`) that is documented as a "programming error" already.

Indeed.

(Though #8110 already mentioned this practice, so we should assume that the same problem can appear elsewhere. An alternative, which I want to advocate to avoid matching and discriminating asynchronous exceptions like Sys.Break, which should be forbidden, is that one should instead have the signal handler raise an indiscernible panic, and the program tests whether the signal handler ran via some flag.)

The real issue to me is that of buggy code that swallows exceptions indiscriminately. One point raised at #8110 is that bugs can arise from the interaction of your code with _other people's code_, where other people remain unaware that their deviation from "best practices" cause bugs remotely. Bugs that can appear when you combine two well-tested and apparently correct components are pernicious. OCaml does not enforce proper exception discipline (and I wonder which proportion of programmers know what it is exactly), so I find it delicate to set this discipline in stone _indirectly_ like this. It is also going to be difficult to have a good picture of the impact of the change: one point at #8110 is that it is hard to debug.

Case in point, aside from "buggy" code, the Async example can give an idea of what people might currently be doing with exceptions. You can indeed imagine programs where components are wrapped in _monitors_ which record exceptions arising from them indiscriminately for later/separate treatment, for whatever architectural purpose. (Notice that Async relies on its own resource-management mechanism.)

Another way to look at it is to ask: would we accept to change the behaviour of `exit` likewise, to replace it with raising some private exception `Program_exit of int`? Because if it works for Thread.exit, I do not see why it should not work for exit, and I personally would be happy to get rid of `exit`. It is resource-unsafe in the same way, and issues with at_exit callbacks can find a better solution this way. If that does not sound possible, then think that Thread.exit might currently be used instead of an exception because of its abortive property.

All this while programmers with strict resource-safety requirements already know that they must raise instead of using Thread.exit.

So I would really like to see Thread.exit fixed properly, because some solution will need to be found for multicore anyway, and the current proposal in multicore indeed seems to be to raise an exception. And I initially thought an exception would be enough, but various aspects of #8110 make me cautious. And it is still better than deprecating. But, I do believe that there is some merit to your analogy with Rust's panic of which I would like to find an equivalent for OCaml, and this is something that I am currently exploring further and would be happy to discuss.

#### My conclusion

Once the issue 1) is separated from issue 2) with the fix I propose, the problem 2) becomes less urgent, and it is a good idea to coordinate with multicore to avoid having to fix it twice. Perhaps no better solution will be found by that time than raising an exception? But at least, given the amount of language changes that I have heard are necessary to make multicore possible, it will probably (hopefully) be as part of a well thought-out transition plan.

(The problem you have found is indeed one among many other fun questions in the same spirit which I got interested in thanks to Leo, so I am glad that you found it and got interested by it. As an example, on the question of asynchronous exceptions, I believe the diagnosis that lead multicore developers to propose their removal should be taken very seriously, and the only alternative to removal that I can propose requires to implement part of the resource-management proposal, which I hope to be able to give first as a library-based version in not too long. And with what it takes to solve the question of asynchronous exceptions, I think we can solve Thread.exit in several ways. If that topic interests you I am happy to keep you in the loop.)

**Comment by dbuenzli** [comment] 2019-10-28 08:28
> Another way to look at it is to ask: would we accept to change the behaviour of `exit` likewise, to replace it with raising some private exception `Program_exit of int`?

At least [this discussion](https://github.com/ocaml/ocaml/pull/685) it was *perceived* that `exit` should be a sink that never returns. I think it will be difficult to get rid of `exit` --- also you do so you will need a mecanism to set the program exit code.

However note that except for persistent synchronisation mecanisms (e.g. file locks, but then is an unsolvable problem for catastrophic failures anyways), ressources are no really a concern for `exit`, your OS reclaims them. This is of course not the case for `Thread.exit` where the program continues to run, so comparing the two seems a bit unfit. 

> So my take-away is indeed that deprecating Thread.exit would break actual and correct programs

I think the words are important here, deprecating things never breaks programs. 

It entices people to move away from the entry point in existing programs and suggests them not to use it in new programs by annoying your build logs. It's only when you remove the deprecated thing that it breaks programs -- at which point you hope no one uses it anymore. 

On the other hand silently changing the semantics of `Thread.exit` *again* by making it raise like is suggested in this thread might actually break programs in unforseen ways, however broken you think they might be. It feels much more risky to me than simply deprecating `Thread.exit`. 

As we have seen `Thread.exit` is dangerous, *should* not be used, and is not an essential primitive. I don't think there's any worth in losing time trying to fix it again. Just deprecate it and let it go. 

Could maybe the people who are not in favour of deprecating `Thread.exit` give a good rationale for why they want to keep it ?

**Comment by gadmm** [comment] 2019-10-29 00:52
> At least [this discussion](https://github.com/ocaml/ocaml/pull/685) it was _perceived_ that `exit` should be a sink that never returns. I think it will be difficult to get rid of `exit` --- also you do so you will need a mecanism to set the program exit code.
> 
> However note that except for persistent synchronisation mecanisms (e.g. file locks, but then is an unsolvable problem for catastrophic failures anyways), ressources are no really a concern for `exit`, your OS reclaims them. This is of course not the case for `Thread.exit` where the program continues to run, so comparing the two seems a bit unfit.

You are right to object that the analogy is not perfect, because exit is safe for OS resources, whereas Thread.exit is only safe for memory and resources that the program is happy to clean up with finalisers as a fallback, which is indeed a lot more restricted. However I mentioned that a lot of programs inside the historical application domain of OCaml use asynchronous exceptions, and those cannot rely on the protect idiom anyway: for these programs, it is not possible to argue that Thread.exit is problematic.

I like that you remind that not all resources are OS resources, and that even resource-management with Fun.protect can currently be unreliable.

(Anyway, my question about exit was rhetorical and I would not like to divert the discussion with it. To me the ideal behaviour and usage recommendation for exit should be exactly as in Rust: https://doc.rust-lang.org/std/process/fn.exit.html, which agrees with your points.)

> I think the words are important here, deprecating things never breaks programs.
> 
> It entices people to move away from the entry point in existing programs and suggests them not to use it in new programs by annoying your build logs. It's only when you remove the deprecated thing that it breaks programs -- at which point you hope no one uses it anymore.

You are entirely right to warn that we should clarify what deprecating means to each other. I take deprecation to mean “plan for future removal, add a compilation warning, and offer an evolution path”.

I went back to read all the recent discussions about backwards-compatibility to avoid reproducing them here.

One fact is that _the choice has been made_ to treat deprecation warnings as fatal errors _purposefully_ to interrupt the user's workflow (https://github.com/ocaml/dune/pull/1850), since this is seen as the only effective way to have them deal with deprecation. It was a choice, there were good points on both sides, and surely "deprecated" has meant something else in the past when I see that `Array.create` (whose existence disturbs no one) has been documented as deprecated in 1999 and never removed.

I find this to be a wise choice, because it encourages deprecaters to be more cautious, so now there needs to be a clear benefit and evolution path for deprecation, and thus one is doubly confident that people ignore the warning less (because it both annoys them, and because they know there is a clear benefit and the warning is actionable). So it will prevent nonserious changes such as force-renaming Array.create into Array.make or force-renaming Pervasives into Stdlib, which would now be hard to understand without knowing the other interpretation of deprecating.

With your interpretation, one can claim not to break anything by deprecating, and then the user just decides to ignore the warnings because they have more urgent matters and forgets about it, and then later the removal ends up actually breaking code (and then of course one is now free to blame the user). So, I do not agree that your interpretation of deprecating is a good thing.

1) Is deprecating Thread.exit beneficial?
2) Is there a clear evolution path?

Is deprecating Thread.exit beneficial? It is definitely, according to the following criterion: if somebody else uses Thread.exit, and I manage my resources deterministically, then they are going to break my code. This is really bad. For a start libraries must not call Thread.exit under my feet which of course no sane library will do (well what if your name is Async? exceptions, exceptions...). So I would be as happy as you if Thread.exit was gone. Now imagine people using OCaml in its original application domains. Thread.exit is not problematic. These people have been using OCaml reliably with asynchronous exceptions for a long time, and they did not seem to complain that OCaml is a resource-unsafe language. Yet I could make the same sort of rock-solid case in favour of removing all asynchronous exceptions as we are doing now.

But is there a clear evolution path? The discussion showed that while there are correct and reliable uses of Thread.exit (useful I do not know), there are examples where there is no simple and straightforward evolution path. As we have seen one cannot just tell users to use an exception instead. If it was ok to do without realistic evolution paths and understanding of the impact, I know a simple fix to the async exception problem. Short of fixing something which is truly broken, it is almost impossible to reason about how some feature can be used in the wild.

> On the other hand silently changing the semantics of `Thread.exit` _again_ by making it raise like is suggested in this thread might actually break programs in unforseen ways, however broken you think they might be. It feels much more risky to me than simply deprecating `Thread.exit`.
> 
> As we have seen `Thread.exit` is dangerous, _should_ not be used, and is not an essential primitive. I don't think there's any worth in losing time trying to fix it again. Just deprecate it and let it go.

You do make good points and I agree with most of them. To be clear, I am no proponent of changing it into raising an exception, for similar reasons as you. I would prefer to be able to remove it and offer a suitable replacement in the longer term, as part of a host of other issues of the same kind.

I claim that once Thread.exit is forbidden to run inside async callbacks, then doing nothing for now _is fine_. We know that people are using OCaml for domains where non-memory resource-management is not a central concern, as witnessed by features they use that are incompatible with strict resource-management requirements. Thread.exit has been making sense there before people started using OCaml as a systems programming language (and pushed unwind-protect abstractions into more pervasive use) and it will keep making sense for them. Whether it is an important primitive, I do not know, but there is valid code that one has to keep supporting. For other people, Thead.exit still behaves as advertised, and they have already been teaching to avoid it. It is a false problem. I also suggested that the documentation of Thread.exit can be improved, which is an appropriate way to follow the natural evolution of a language.

I also claim that the context is different regarding the transition to multicore, because 1) it is not possible to keep Thread.exit as is, and 2) it is only a tiny part of a wider problem regarding resource-management, so it will need a well thought-out transition plan. The challenge is that multicore will have to either reconcile the two dialects somehow, or drop one of them entirely. I want to encourage people to focus on the more general issue.

**Comment by dbuenzli** [comment] 2019-10-29 01:51
> One fact is that _the choice has been made_ to treat deprecation warnings as fatal errors _purposefully_ to interrupt the user's workflow ([ocaml/dune#1850](https://github.com/ocaml/dune/pull/1850)),

I don't want to have this discussion again. 

That's a choice that has been made by a third-party tool that likes to tweak the OCaml compiler defaults to their opinions, that's not how the OCaml compiler works. I personally think it's a wrong choice but that's a usability problem they created for themselves, it's for them to fix it.

As far as the OCaml compiler is concerned deprecating things is not a fatal error and I don't think it should be otherwise we won't ever be able to deprecate things (why not simply remove things directly then ?) and the system will only accrue cruft. 

> 1. Is deprecating Thread.exit beneficial?

Yes. First it gives you a nice warning you should not be using that function because it's broken. Second, I'm not into the details, but if it makes @jhjourdan's work (which I'm keen to get my hands on) easier I'm all for it.

> 2\. Is there a clear evolution path?

Yes. Let your thread finish naturally or escape by throwing an exception.

**Comment by jhjourdan** [comment] 2019-11-06 16:51
I finished my review of the list of uses of `Thread.exit` proposed by @gadmm.

My conclusion is the following: if we deprecate `Thread.exit`, then each of these programs will need fixing at some point (or else live with the deprecation warning and then suffer if the function gets removed). On the other hand, if the implementation is changed to pure OCaml with an exception, then it seems like (except if my understanding of these pieces of code is wrong) the only package that would need fixing would be `Async`, since they use a catch-all `try-with` construct. In Async, the fix would not be very difficult: its authors would need to use a their own dedicated exception which they would special-case in their catch-all construct. It seems like all the other packages use `Thread.exit ()` in a place where an exception could be used very well instead. Actually, `bigbro` would be *fixed* by the use of an exception, since it still relies on the old implementation using exceptions...

I don't care too strongly about which option we choose, but I would very much like if the current implementation were either deprecated or made obsolete. Given that the migration seems much easier with @xavierleroy's proposal of using exception (only Async would need fixing, and the fix is not too complicated), I am in favor of implementing that option. I am going to write a PR soon if nobody complains loudly here.

**Comment by gadmm** [comment] 2019-11-06 17:00
Would it be possible to discuss it in person?

**Comment by xavierleroy** [comment] 2019-11-06 19:10
Thanks a lot, @jhjourdan , for the detailed review.  

@gadmm : I believe you're shooting for the best, and I respect your integrity.  But as you know _le mieux est l'ennemi du bien_, and in this particular case I feel that _le bien_ is to have `Thread.exit` raise an exception, and document this fact prominently.

**Comment by gadmm** [comment] 2019-11-06 21:54
@xavierleroy : Still, if we have to pick a poison, I agree with @dbuenzli that explicit deprecation is less risky than silently deprecating the current behaviour, as he explained:

> silently changing the semantics of Thread.exit again by making it raise like is suggested in this thread might actually break programs in unforeseen ways, however broken you think they might be.

Concrete evidence supports his warning: the bug report at #8110, and the example of Async. The correct conclusion from the review of the opam sample (and I thank @jhjourdan for it) is not “only Async needs to be fixed” (because by far not all ocaml programs have been reviewed, which I consider impossible) but “even modern, expert code can be broken by the change”.

In this case, deprecating `Thread.exit` is not much different because it would simply force the programmers to raise an exception themselves, but it will force them to review the impact, like Daniel said.

Lastly, perhaps the wider issue that interests me, revealed by the current one, is that programmers are apparently expected to follow some “best practices” regarding exception handling (catch-all should be followed by re-raise except at isolation boundaries, serious exceptions should never be caught except with a catch-all). But reading for instance [Real-World OCaml](https://dev.realworldocaml.org/error-handling.html) does not give me the impression that it is better documented and enforced now than at the time of #8110. Is it correct to say that there is a wider issue?

**Comment by dbuenzli** [comment] 2019-11-07 00:55
I personally would be really nervous in making that silently raising again but if @xavierleroy wants to take the responsability :-) 

Another option would be to make it raise *and* deprecate it without a plan for removal. The deprecation message can then indicate both that it should not be used and about the semantic change and be silenced locally by those who think it does not affect them.

Also a question that was not asked and I don't know the answer is what does the `Thread` API become in the multicore work anyways ?

**Comment by jhjourdan** [comment] 2019-11-07 10:21
> Another option would be to make it raise and deprecate it without a plan for removal. The deprecation message can then indicate both that it should not be used and about the semantic change and be silenced locally by those who think it does not affect them.

Ok, Let's do that.

> Also a question that was not asked and I don't know the answer is what does the Thread API become in the multicore work anyways ?

See ocaml-multicore/ocaml-multicore#240. They want to have a compatibility layer where the `Thread library is preserved, but does not offer parallelism (i.e., all the memory operations are atomic).

**Comment by jhwoodyatt** [comment] 2019-12-11 16:56
I've been off playing around in the weeds on and off for months with an update to ocaml-multicore/ocaml-multicore#240 that I finally pushed this morning. Now I finally come to notice this pull request here.

I have little to add to the discussion on the main topic under discussion, but I'd like to put down a marker here for my strong belief that, at least in the multicore runtime, the entire Thread library represents a programming interface that should be considered provisional for backward compatibility purposes only. Making the most of the multicore runtime should entail use of a better programming interface for concurrency, i.e. one that uses an effect scheduler.

**Comment by jhjourdan** [comment] 2020-06-11 14:22
FTR, I have just figured out that the issue is deeper than what we thought, since in OCaml, calling the `Unix.fork` function causes all threads but one to be killed. Obviously, the killed threads had no opportunity to free their resources.

I'm updating the main statement of the issue.

**Comment by gasche** [comment] 2020-06-11 14:35
I'm not sure I understand. Are we talking about threads killed in the parent program or in the fork child? My assumption would be that "all threads but one are killed" in the child program, only the thread that corresponds to the parent's forking thread survives.

The initial message of your PR was about resource safety for non-memory resources; would the proposal of raising an exception be safer than the current behavior of silent killing? I don't know how people reason about resource safety in presence of `fork`; but I have the impression that forking shares many resources instead of duplicating them, and that *not collecting* them from the child may sometimes be safer than double collection. Some resources handled by the OS, such as file descriptors, are duplicated by forking, so "closing" them on both ends is the expected/correct behavior; if in addition we "flush" something, as an indempotent operation, this is fine. But what about resources with a non-idempotent cleanup logic, such as writing a footer to a file?

**Comment by xavierleroy** [comment] 2020-06-11 17:35
I would not give too much though to Unix.fork in multithreaded programs.  The POSIX threads semantics for `fork()` (fork only the calling thread) is very hard to use to begin with, and it is likely that Multicore OCaml will make Unix.fork fail if the program has more than one domain (system thread).

**Comment by jhjourdan** [comment] 2021-06-14 12:57
Still an issue.

**Closed as completed** 2022-01-26 11:35 UTC
