### ISSUE TITLE
arm32 native code output broken

### ISSUE THREAD

**Issue by avsm** [ocaml/ocaml#8578] opened 2019-04-02 16:30 UTC
The changes in https://github.com/ocaml/ocaml/pull/2237 to remove a `call` in native code output seem to have broken arm output on armv7l and armv8 in 32-bit mode.  arm64 is working in my testing, but all the 32-bit backends fail tests fairly dramatically with a number of bus errors.

An example of the failure is in the CI for the ocaml/opam container builds on the Raspberry Pi 3:
https://gitlab.com/ocaml-platform/ocaml-containers/-/jobs/187363959

```
#=== ERROR while compiling ocaml.4.09.0 =======================================#
# context              2.0.3 | linux/arm32 | ocaml-variants.4.09.0+trunk | git://github.com/ocaml/ocaml-beta-repository
# path                 ~/.opam/4.09/.opam-switch/build/ocaml.4.09.0
# command              ~/.opam/4.09/bin/ocaml /home/opam/.opam/4.09/share/ocaml-config/gen_ocaml_config.ml 4.09.0 ocaml
# exit-code            2
# env-file             ~/.opam/log/ocaml-90-dc6e87.env
# output-file          ~/.opam/log/ocaml-90-dc6e87.out
### output ###
# Illegal instruction (core dumped)
# Exception: Failure "Bad return from 'ocamlc -where'".
```

The #2237 comment implies that arm32 wasn't actually tested -- just wanted to check if that was the case in the final merged one, or if I should be hunting elsewhere for the regression in trunk. I had to manually bisect to find this changeset as automatic bisecting of the testsuite is tricky due to unrelated failures on arm32 in the test suite.

(this changeset is only in trunk and not 4.08, which works fine in my builds and testing)

**Comment by xavierleroy** [comment] 2019-04-02 16:36
There was a comment on #2237 stating that it was run through CI precheck, which includes one ARM32 target.  But I didn't check any of that myself.

**Comment by xavierleroy** [comment] 2019-04-02 16:58
CI is blue (OK) for trunk on ARM32 as of today.  The test machine is a Raspberry Pi 3 running Raspbian.

**Comment by avsm** [comment] 2019-04-02 17:44
Hm, so I can reproduce this on two separate machines:

- a rPI3 running Raspbian Jessie `Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux`
- an Ampere arm64 running in 32bit mode via `setarch` into a Raspbian 32-bit userspace: this this is `Linux 1a7a932c1037 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:36:04 UTC 2019 armv8l GNU/Linux`
- the CI job on gitlab.com/ocaml-platform is also a physical rPI3 hosted on Scaleway, that exhibited the problem.

I'm reproducing it via just `git clean -dxf && ./configure && make world.opt && make tests`.  Rerunning it from scratch now on my local rPI3 to make sure I'm not doing something silly...

**Comment by avsm** [comment] 2019-04-02 23:14
Reproduced on the rPi3 with trunk rev 2314abc2ae7d31a8465613e5cbadf78acb18a51d

Running ocamlopt.opt built in the tree bus errors immediately early in the ocaml code. Under gdb:

```
# gdb ./ocamlopt.opt 
<snip>
(gdb) run
Starting program: /root/ocaml/ocamlopt.opt 
Program received signal SIGBUS, Bus error.
0x003303a2 in camlStdlib__hashtbl__entry () at hashtbl.ml:60
60	    try Sys.getenv "OCAMLRUNPARAM" with Not_found ->
(gdb) disassemble
Dump of assembler code for function camlStdlib__hashtbl__entry:
   0x00330368 <+0>:	sub	sp, #8
   0x0033036a <+2>:	str.w	lr, [sp, #4]
   0x0033036e <+6>:	ldr	r1, [pc, #552]	; (0x330598 <camlStdlib__hashtbl__entry+560>)
   0x00330370 <+8>:	ldr	r2, [pc, #544]	; (0x330594 <camlStdlib__hashtbl__entry+556>)
   0x00330372 <+10>:	str	r2, [r1, #116]	; 0x74
   0x00330374 <+12>:	ldr	r3, [pc, #536]	; (0x330590 <camlStdlib__hashtbl__entry+552>)
   0x00330376 <+14>:	str	r3, [r1, #104]	; 0x68
   0x00330378 <+16>:	ldr	r5, [pc, #528]	; (0x33058c <camlStdlib__hashtbl__entry+548>)
   0x0033037a <+18>:	str	r5, [r1, #112]	; 0x70
   0x0033037c <+20>:	ldr	r7, [pc, #520]	; (0x330588 <camlStdlib__hashtbl__entry+544>)
   0x0033037e <+22>:	str	r7, [r1, #108]	; 0x6c
   0x00330380 <+24>:	ldr	r0, [pc, #512]	; (0x330584 <camlStdlib__hashtbl__entry+540>)
   0x00330382 <+26>:	str	r0, [r1, #120]	; 0x78
   0x00330384 <+28>:	ldr	r2, [pc, #504]	; (0x330580 <camlStdlib__hashtbl__entry+536>)
   0x00330386 <+30>:	str	r2, [r1, #124]	; 0x7c
   0x00330388 <+32>:	ldr.w	lr, [pc, #532]	; 0x3305a0 <camlStdlib__hashtbl__entry+568>
   0x0033038c <+36>:	add	lr, pc
   0x0033038e <+38>:	stmdb	sp!, {r8, lr}
   0x00330392 <+42>:	mov	r8, sp
   0x00330394 <+44>:	ldr	r0, [pc, #484]	; (0x33057c <camlStdlib__hashtbl__entry+532>)
   0x00330396 <+46>:	ldr	r7, [pc, #480]	; (0x330578 <camlStdlib__hashtbl__entry+528>)
   0x00330398 <+48>:	bl	0x35ad88 <caml_c_call>
   0x0033039c <+52>:	ldmia.w	sp!, {r8, lr}
   0x003303a0 <+56>:	b.n	0x3303da <camlStdlib__hashtbl__entry+114>
=> 0x003303a2 <+58>:	ldr	r7, [pc, #464]	; (0x330574 <camlStdlib__hashtbl__entry+524>)
   0x003303a4 <+60>:	ldr.w	r12, [r7, #28]
   0x003303a8 <+64>:	cmp	r0, r12
   0x003303aa <+66>:	bne.n	0x3303d6 <camlStdlib__hashtbl__entry+110>
   0x003303ac <+68>:	ldr.w	lr, [pc, #492]	; 0x33059c <camlStdlib__hashtbl__entry+564>
   0x003303b0 <+72>:	add	lr, pc
   0x003303b2 <+74>:	stmdb	sp!, {r8, lr}
   0x003303b6 <+78>:	mov	r8, sp
```

The kernel registers an unhandled prefetch abort (so we in non-exec memory at this point?).

For reference, the changeset before #2237 (a097dfabfd2356fbd90af5850b1061c5bd0e2e29) has this dissassembly for the same function and the test suite doesn't bus error (a few straggling failures, but only a couple of tests)

```
(gdb) disassemble camlStdlib__hashtbl__entry
Dump of assembler code for function camlStdlib__hashtbl__entry:
   0x0032d8b4 <+0>:	sub	sp, #8
   0x0032d8b6 <+2>:	str.w	lr, [sp, #4]
   0x0032d8ba <+6>:	ldr	r1, [pc, #544]	; (0x32dadc <camlStdlib__hashtbl__entry+552>)
   0x0032d8bc <+8>:	ldr	r2, [pc, #536]	; (0x32dad8 <camlStdlib__hashtbl__entry+548>)
   0x0032d8be <+10>:	str	r2, [r1, #116]	; 0x74
   0x0032d8c0 <+12>:	ldr	r3, [pc, #528]	; (0x32dad4 <camlStdlib__hashtbl__entry+544>)
   0x0032d8c2 <+14>:	str	r3, [r1, #104]	; 0x68
   0x0032d8c4 <+16>:	ldr	r5, [pc, #520]	; (0x32dad0 <camlStdlib__hashtbl__entry+540>)
   0x0032d8c6 <+18>:	str	r5, [r1, #112]	; 0x70
   0x0032d8c8 <+20>:	ldr	r7, [pc, #512]	; (0x32dacc <camlStdlib__hashtbl__entry+536>)
   0x0032d8ca <+22>:	str	r7, [r1, #108]	; 0x6c
   0x0032d8cc <+24>:	ldr	r0, [pc, #504]	; (0x32dac8 <camlStdlib__hashtbl__entry+532>)
   0x0032d8ce <+26>:	str	r0, [r1, #120]	; 0x78
   0x0032d8d0 <+28>:	ldr	r2, [pc, #496]	; (0x32dac4 <camlStdlib__hashtbl__entry+528>)
   0x0032d8d2 <+30>:	str	r2, [r1, #124]	; 0x7c
   0x0032d8d4 <+32>:	bl	0x32d90e <camlStdlib__hashtbl__entry+90>
   0x0032d8d8 <+36>:	ldr	r7, [pc, #484]	; (0x32dac0 <camlStdlib__hashtbl__entry+524>)
   0x0032d8da <+38>:	ldr.w	r12, [r7, #28]
   0x0032d8de <+42>:	cmp	r0, r12
   0x0032d8e0 <+44>:	bne.n	0x32d90a <camlStdlib__hashtbl__entry+86>
   0x0032d8e2 <+46>:	bl	0x32d8f6 <camlStdlib__hashtbl__entry+66>
   0x0032d8e6 <+50>:	ldr	r3, [pc, #472]	; (0x32dac0 <camlStdlib__hashtbl__entry+524>)
   0x0032d8e8 <+52>:	ldr	r4, [r3, #28]
   0x0032d8ea <+54>:	cmp	r0, r4
   0x0032d8ec <+56>:	bne.n	0x32d8f2 <camlStdlib__hashtbl__entry+62>
   0x0032d8ee <+58>:	ldr	r0, [pc, #460]	; (0x32dabc <camlStdlib__hashtbl__entry+520>)
   0x0032d8f0 <+60>:	b.n	0x32d920 <camlStdlib__hashtbl__entry+108>
   0x0032d8f2 <+62>:	bl	0x3584d0 <caml_raise_exn>
   0x0032d8f6 <+66>:	stmdb	sp!, {r8, lr}
   0x0032d8fa <+70>:	mov	r8, sp
   0x0032d8fc <+72>:	ldr	r0, [pc, #440]	; (0x32dab8 <camlStdlib__hashtbl__entry+516>)
   0x0032d8fe <+74>:	ldr	r7, [pc, #436]	; (0x32dab4 <camlStdlib__hashtbl__entry+512>)
   0x0032d900 <+76>:	bl	0x358430 <caml_c_call>
```

**Comment by xavierleroy** [comment] 2019-04-03 07:33
I was able to reproduce myself: `ocamlopt.opt` crashes immediately, and none of the tests from the testsuite can be built.  Then CI sees
```
Summary:
    0 tests passed
    0 tests skipped
    0 tests failed
    0 tests not started (parent test skipped or failed)
    0 unexpected errors
    0 tests considered
```
and declares... drumroll... SUCCESS !

**Comment by mshinwell** [comment] 2019-04-03 08:40
I will look at this.

**Comment by xavierleroy** [comment] 2019-04-03 09:45
I suspect this is a Thumb2 vs classic ARM issue.  In Thumb2 the low bit of the PC must be 1, and it may be that the addresses of exception handlers that are pushed in the stack have low bit 0.

**Comment by mshinwell** [comment] 2019-04-03 09:50
Yeah, I was suspecting some kind of interworking problem.  (Well, or at least, Thumb vs ARM even if we're not switching modes.)

**Comment by mshinwell** [comment] 2019-04-03 10:00
@xavierleroy I haven't got a suitable machine to test on until @avsm appears.  Could you try changing the "4" on line 358 of `arm/emit.mlp` to "3"?  That may not be entirely correct as we might need an ARMv6 condition as well to check this is Thumb-2 (maybe?) -- but perhaps it will demonstrate if this is the problem.  (I'm relying on the fact that since instructions are aligned to a power of 2 number of bytes then adding one to the computed distance will always give an odd number without disturbing which instruction is pointed at.)

**Comment by xavierleroy** [comment] 2019-04-03 10:02
I see what you're trying to do, and I think it makes sense.  Will try shortly.  In the meantime you should really get a Raspberry Pi, I though that was standard equipment for all Cambridge residents :-)

**Comment by avsm** [comment] 2019-04-03 10:20
I've given @mshinwell his statutory pi now :-)

**Comment by xavierleroy** [comment] 2019-04-03 10:23
My rPi is still working on the test suite, but results look mostly good so far.

**Comment by avsm** [comment] 2019-04-03 10:57
I'll try the change on the Ampere armv8 32-bit chroot later this afternoon, but I expect that'll be the same result if this was a Thumb _vs_ classic issue

**Comment by xavierleroy** [comment] 2019-04-03 10:59
ocamlopt.opt works, and most of the test suite passes, but there are  Bus error related to dynlink
(tests/lib-dynlink-native, tests/lib-dynlink-initializers, tests/lib-dynlink-pr4229, tests/lib-dynlink-pr4839, tests/lib-dynlink-pr6950).

**Comment by mshinwell** [comment] 2019-04-03 11:12
Thanks for the update.  Let me take this over and I will investigate.

**Comment by mshinwell** [comment] 2019-04-03 12:15
@xavierleroy On the `armv7l-unknown-linux-gnueabihf` box I'm using, with the change of offset from `4` to `3`, the dynlink tests pass.  Did you fully clean your tree after changing the constant before rebuilding?  I have a feeling that changing the emitters does not cause recompilation of `otherlibs/` due to some dependency problem.

**Comment by xavierleroy** [comment] 2019-04-03 13:15
I'll rebuild from scratch and re-test.

**Comment by xavierleroy** [comment] 2019-04-03 14:22
The tests are OK, including the dynlink tests.  Probably a leftover, badly-compiled Dynlink library.

**Comment by mshinwell** [comment] 2019-04-03 14:23
Lovely.  Am I right in thinking that we only emit Thumb-2 and never Thumb-1?  If so we may have covered the semantics now (i.e. we need the bottom bit of the PC set for Thumb-2, and never for ARM mode).

**Comment by xavierleroy** [comment] 2019-04-03 16:11
Well, Thumb-2 is a superset of Thumb-1...  But OCaml generates either classic ARM or full Thumb-2 code, and would not work with a Thumb-1-only architecture.  (I think those disappeared a long time ago.)  So, yes, we only need to respect the ARM/Thumb-2 interworking rule, with bit 0 of code pointers indicating the desired mode.

**Comment by mshinwell** [comment] 2019-04-03 16:22
Please see #8582

**Comment by xavierleroy** [comment] 2019-04-03 16:27
Merged!  Thank you for the quick fix.

**Closed as completed** 2019-04-03 16:27 UTC

**Comment by dra27** [comment] 2019-04-04 09:54
There was one thing still to follow-up with this - namely that ARM32 CI was passing (see https://github.com/ocaml/ocaml/issues/8578#issuecomment-479374246 above!).

#8571 is not sufficient to change this, but #8580 does fix this - see [this precheck test](https://ci.inria.fr/ocaml/job/precheck/236/flambda=false,label=ocaml-arm-32/console) which doesn't have #8582 but does have #8580:

```
Summary:
    0 tests passed
    0 tests skipped
    0 tests failed
    0 tests not started (parent test skipped or failed)
  898 unexpected errors
  898 tests considered
#### Something failed. Exiting with error status.
```

**Comment by avsm** [comment] 2019-04-04 13:06
Also just confirming that all the 32-bit opam/platform CI machines have now succeeded, and are happily pushing multiarch Docker images of 4.09 compilers to https://hub.docker.com/r/ocaml/opam2 again.
