### ISSUE TITLE
Obj.reachable_words on custom_blocks

### ISSUE THREAD

**Issue by dannywillems** [ocaml/ocaml#10729] opened 2021-10-26 16:26 UTC
When dealing with custom blocks, `Obj.reachable_words` does not take in account the size of the allocated custom blocks. See the example project [here](https://gitlab.com/dannywillems/ocaml-reachable-words-custom-blocks-example).
(part of the code pasted here)
```C
// I want to represent 32 bytes. Might be a more complicated structure. Only for the example
// The following lines are the usual custom blocks boilerplate code.
typedef struct foo256_s {
  unsigned char t[256];
} foo256_t;

#define Foo256_val(v) (*((foo256_t **)Data_custom_val(v)))

static void finalize_free_foo256(value v) { free(Foo256_val(v)); }

static struct custom_operations foo256_ops = {"foo256_t",
                                              finalize_free_foo256,
                                              custom_compare_default,
                                              custom_hash_default,
                                              custom_serialize_default,
                                              custom_deserialize_default,
                                              custom_compare_ext_default,
                                              custom_fixed_length_default};

CAMLprim value caml_allocate_foo256_stubs(value unit) {
  CAMLparam1(unit);
  CAMLlocal1(block);
  block = caml_alloc_custom(&foo256_ops, sizeof(foo256_t *), 0, 1);
  void *p = calloc(1, sizeof(foo256_t));
  if (p == NULL)
    caml_raise_out_of_memory();
  foo256_t **d = (foo256_t **)Data_custom_val(block);
  *d = p;
  CAMLreturn(block);
}
```

```ocaml
module Stubs = struct
  type foo256

  external allocate_foo256 : unit -> foo256 = "caml_allocate_foo256_stubs"
end

let () =
  let foo256 = Stubs.allocate_foo256 () in
  Printf.printf "Size for foo256: %d\n" Obj.(reachable_words (magic foo256))
```

The output is `3`. However, I would have expected an output of `6` (`2 + sizeof(foo256_t)`).

Is it the expected behavior of `Obj.reachable_words`?
If it is not expected, using `2 + sizeof` wouldn't be enough?

**Comment by alainfrisch** [comment] 2021-10-26 21:11
AFAICT, Obj.reachable_words correctly counts the number of words of the custom blocks (within the OCaml heap).  The content of the block can be arbitrary, there is no way to know it contains a pointer to some data structure outside the heap, nor to know the size of that data structure.

**Comment by xavierleroy** [comment] 2021-10-27 08:13
@alainfrisch's reply is spot on.  Your stub code stores a pointer to a `foo256_t` in the custom block, so only the size of the pointer is reported.  

Note that you could also elect to store the `foo256_t` "flat" in the custom block:
```
#define Foo256_val(v) (((foo256_t *)Data_custom_val(v)))

CAMLprim value caml_allocate_foo256_stubs(foo256_t f256) {
  CAMLparam1(unit);
  CAMLlocal1(block);
  block = caml_alloc_custom(&foo256_ops, sizeof(foo256_t), 0, 1);
  *Foo256_val(block) = f256;
  CAMLreturn(block);
}
```
Then your 256 bytes will be counted.  However, the solution above can be problematic if your type `foo256_t` requires alignment greater than a machine word (i.e. greater than 8 on a 64-bit host and greater than 4 on a 32-bit host).

**Comment by xavierleroy** [comment] 2021-10-27 08:14
Closing this report, as the behavior of `Obj.reachable_words` here is as intended.

**Closed as completed by xavierleroy** 2021-10-27 08:14 UTC
Labels: not-a-bug

**Comment by dannywillems** [comment] 2021-11-29 15:29
> @alainfrisch's reply is spot on. Your stub code stores a pointer to a `foo256_t` in the custom block, so only the size of the pointer is reported.
> 
> Note that you could also elect to store the `foo256_t` "flat" in the custom block:
> 
> ```
> #define Foo256_val(v) (((foo256_t *)Data_custom_val(v)))
> 
> CAMLprim value caml_allocate_foo256_stubs(foo256_t f256) {
>   CAMLparam1(unit);
>   CAMLlocal1(block);
>   block = caml_alloc_custom(&foo256_ops, sizeof(foo256_t), 0, 1);
>   *Foo256_val(block) = f256;
>   CAMLreturn(block);
> }
> ```
> 
> Then your 256 bytes will be counted. However, the solution above can be problematic if your type `foo256_t` requires alignment greater than a machine word (i.e. greater than 8 on a 64-bit host and greater than 4 on a 32-bit host).

I implemented this idea in https://gitlab.com/dannywillems/ocaml-bls12-381/-/merge_requests/144. Works perfectly and there is a significant gain in performance (as the operations on the algebraic structure are in ns). Thanks!

**Comment by dannywillems** [comment] 2021-12-02 11:14
> However, the solution above can be problematic if your type foo256_t requires alignment greater than a machine word

Can you explain why pls? Does sizeof not take care of the alignment?

**Comment by xavierleroy** [comment] 2021-12-03 17:01
> Can you explain why pls? Does sizeof not take care of the alignment?

Oh, no, it's not enough.  Caml objects in the heap are made of words (4 bytes on 32-bit platforms, 8 bytes on 64-bit platforms), and pointers into the heap like `Data_custom_val(v)` are word-aligned.  `caml_alloc_custom` is not able to align to a bigger alignment, even if the size of the custom data is greater than the word size.

Here is an example  of what could go wrong.  Say you're on a 32-bit platform and your `foo256_t` is
```
   typedef struct { double d[4]; } foo256_t;
```
When accessing the double FP numbers `d[i]`, the C compiler will assume they are 8-aligned, and generate load and store instructions that may crash if they are not.  Yet, `caml_alloc_custom` can produce `Data_custom_val` pointers that are word-aligned but not 8-aligned, i.e. pointers equal to 4 modulo 8.
