### ISSUE TITLE
`ocamlopt.opt` passes erroneous flags to `ld`

### ISSUE THREAD

**Issue by emchristiansen** [ocaml/ocaml#12080] opened 2023-03-06 01:44 UTC
The `ocamlopt.opt` compiler passes erroneous flags to `ld`.
Specifically, it may pass `-shared-libgcc`, which isn't a flag that `ld` takes.

I previously [reported this issue with `dune`](https://github.com/ocaml/dune/issues/7073), though it appears to be a bug in `ocamlopt.opt` itself.
See that issue for reproducibility instructions.

Specifically, in the above context, `dune` will produce a command like:

```
(cd _build/default && /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -o lib/foo.exe.o -output-complete-obj /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/stdlib-shims/stdlib_shims.cmxa /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/integers/integers.cmxa -I /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/integers /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/zarith/zarith.cmxa -I /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/zarith /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/class_group_vdf/class_group_vdf.cmxa -I /home/ubuntu/scratch/rust-ocaml-starter-3/_opam/lib/class_group_vdf lib/.foo.eobjs/native/dune__exe__Foo.cmx -verbose)
```

The output looks like this:

<img width="1728" alt="Screenshot 2023-03-05 at 7 39 04 PM" src="https://user-images.githubusercontent.com/225668/223000693-3b5ee987-c413-40c9-9c34-89629e433e12.png">

Note that `ocamlopt.opt` has invoked `ld` with the flag `-shared-libgcc`, which is not a supported flag.

I've tested this on both `4.14.1` and `5.0.0` in Ubuntu 22.04 with new switches and everything up-to-date.

**Comment by gasche** [comment] 2023-03-06 06:48
I believe that your analysis that this is an ocamlopt issue is erroneous. In https://github.com/ocaml/dune/issues/7073#issuecomment-1443813106 in the original issue it is pointed out that the flag comes from a user package, whichever is producing class_group_vdf. This is probably an error with the build system of that package.

It might be that the issue is that the package for some reason needs some flags passed to the C compiler, but not to the C linker, so the `-ccopt` option we provide is too coarse-grained. But it may also be that the build system should be fixed to not pass linker-unsafe flags, or that the package is meant to be used with a specific linker that supports this flag. One can hardly tell without knowing about the package, so you should report the bug there for now.

**Closed as completed by gasche** 2023-03-06 06:48 UTC

**Comment by xavierleroy** [comment] 2023-03-06 10:44
I agree that the issue can probably be fixed at the level of the class_group_vdf package.  But we might still have a problem.  Link-time options and libraries that are stored in OCaml libraries e.g. by `ocamlmklib` are normally passed to the C compiler driver (`cc`, `gcc`, `clang`) when linking an executable (`ocamlopt -o prog.exe`).  But it looks like they can also be passed directly to the linker `ld` when using `ocamlopt -output-obj`.   It could be more reasonable to never call `ld` directly, and always go through `cc`.

**Comment by shindere** [comment] 2023-03-06 10:51
Xavier Leroy (2023/03/06 02:44 -0800):
> I agree that the issue can probably be fixed at the level of the
> class_group_vdf package.  But we might still have a problem.
> Link-time options and libraries that are stored in OCaml libraries
> e.g. by `ocamlmklib` are normally passed to the C compiler driver
> (`cc`, `gcc`, `clang`) when linking an executable (`ocamlopt -o
> prog.exe`).  But it looks like they can also be passed directly to the
> linker `ld` when using `ocamlopt -output-obj`.   It could be more
> reasonable to never call `ld` directly, and always go through `cc`.

I think that's also what we did for calling the assembler: going through
`cc` rather than calling `as` directly to make the calls simpler, rather
than trying to execute lessprocesses.
